### ISSUE TITLE
The macro form (defmethod invoke-with-temporary-page...) was not expanded successfully

### ISSUE THREAD

**Issue by abuhussain** [McCLIM/McCLIM#1012]
Building the latest version of McClim via Quicklisp fails on Embeddable Common Lisp running on OpenBSD SPARC64. This is a new issue and is only present in the *latest* available version of McClim.
I have reproduced it in two different machines with similar configuration and the result is the same.

Here is an excerpt of the error my compiler is throwing:

in file text-formatting.lisp, position 4396
at (DEFGENERIC INVOKE-WITH-TEMPORARY-PAGE...).
The macro form...was not expanded successfully.
Error detected:
Not a proper list (FUNCALL #'(SETF .STREAM-CURSOR-POSITION-STAR.) G73 G72 . G71)ASDF could not load mcclim because COMPILE-FILE ERROR while ...

Any ideas of what could be causing this behaviour in this platform?

**Comment by dkochmanski** [comment]
Hey, I believe that we've fixed this problem in https://github.com/McCLIM/McCLIM/commit/569147bdff41ebf627dd6ee66edb59d4c0ebe282, by latest available do you mean "the latest available in quicklisp"?

**Comment by abuhussain** [comment]
Hi, yes, I mean 'the latest available in quicklisp'. For now, I will try to patch that file individually and report if I have built successfully

**Comment by dkochmanski** [comment]
if it still fails please reopen the issue.
