### ISSUE TITLE
frame-exit works only inside a clim frame top level loop

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1043]
If I call the function `frame-exit` from slime repl the frame doesn't exit. 

This is due to the fact that `frame-exit` method only signal the `frame-exit` condition so if this is not handled the application frame doesn't exit, and the condition is handled in the `run-frame-top-level :around` method. So the frame exit only if the function is called from a clim application (can be also a application different to the `frame-exit` argument), if it is called from slime repl or also from the port event process  the frame doesn't exit.

Maybe this is correct because the spec said that `frame-exit` signal the condition anyway I ask if this is correct.

**Comment by dkochmanski** [comment]
I think that ithe function ~frame-exit~ is meant to be called from inside the CLIM loop, and you are right - the spec seems to support that opinion. Also, note that there are functions like ~destroy-frame~ and ~disown-frame~ which doesn't seem to have this restriction (each has a different meaning).

**Comment by admich** [comment]
Ok, so this is not an issue and I can close it.
