### ISSUE TITLE
Layout protocol

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1045]
I think that McCLIM implementation of layout protocol have some problem. Here some issue:

1. `change-space-requirements` is called from `redisplay-frame-pane`
   on `clim-stream-pane` unless one of `pane-user-{width,height...}`
   is `:compute`. But the space requirement of a clim-pane change only
   if one of the `pane-user-{width,height...}` is :compute, exactly
   the opposite.
2. `change-space-requirements` calls `change-space-requirements` on
   the parent, but a pane can not know if the space requirements of
   its parent will change or not, this is must be a decision of the
   parent. So `change-space-requirements` must only call
   `note-space-requirements-changed` and then the parent decide what
   to do.
3. Due to 1. and 2 `layout-frame` is called too much, e.g. in the Data
   Graph Toy examples it is called each time a new point is drawn
   (once each second)
4. :resize-frame initargs. This is a problem in the specification,
   this argument is cited in `change-space-requirements` description
   as a define-application-frame keywords but then it is not described
   there.
5. `restraining-pane` is defined but not implemented. Also Franz and
   LispWorks CLIM didnn't define it, but Lucid CLIM yes (its written
   in LispWorks CLIM manual, so inside Lispworks Ltd there are two
   closed source CLIM implementation LispWors and Lucid, I didn't
   known).
6. pane slot `space-requirement` and its accessor
   `pane-space-requirement` is defined two times, in `basic-pane` and
   in `layout-protocol-mixin`.
7. I don't understand why there are `pane-current-width` and
   `pane-current-height` to known the actual dimension on a pane there
   is already `sheet-region`.

**Comment by admich** [comment]
Another problem in the layout protocol is the following:
8. If I change the layout of an application with `(setf
   (frame-current-layout))` (e.g. n Clouseau with CTRL-i ) the
   application frame is resized (in a stacking wm). I don't think this
   is what a user want.

**Comment by dkochmanski** [comment]
I've recently noticed some problems which partially overlap with your remarks, most notably regarding frequent changes of the space requirements.

**Comment by scymtym** [comment]
#1050 has been integrated without technically merging it.
