### ISSUE TITLE
execute-frame-command does not trigger redisplay if called manually

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#1078]
In the application below second and third button should increase the counter and trigger the application pane redisplay, however the third button which calls execute-frame-command does not do that. This ticket may get a bit tricky to solve correctly, because execute-frame-command is (or should be) a thread safe operation, so we should also check whether executing command from another thread also triggers redisplay.

```common-lisp
(in-package #:clim-user)

(define-application-frame foobar ()
  ((counter :initform 0 :accessor counter))
  (:panes (app :application :display-function
               (lambda (frame stream)
                 (format stream "banzai: ~a" (counter frame))))
          (bt1 :push-button
               :label "naive increase"
               :activate-callback #'(lambda (pane &rest args)
                                      (declare (ignore pane args))
                                      (com-increase)))
          (bt2 :push-button
               :label "redisplay increase"
               :activate-callback
               #'(lambda (pane &rest args
                          &aux
                            (frame *application-frame*)
                            (stream (frame-standard-output frame)))
                   (declare (ignore pane args))
                   (com-increase)
                   (redisplay-frame-pane frame stream)))
          (bt3 :push-button
               :label "command increase"
               :activate-callback
               #'(lambda (pane &rest args
                          &aux (frame *application-frame*))
                   (declare (ignore pane args))
                   (execute-frame-command frame '(com-increase)))))
  (:layouts (def (vertically ()
                   app
                   (horizontally () bt1 bt2 bt3)))))

(define-foobar-command com-increase ()
  (incf (counter *application-frame*)))

(run-frame-top-level (make-application-frame 'foobar))
```

**Comment by ebrasca** [comment]
I think this may be the solution #1082

**Comment by ebrasca** [comment]
It come from https://github.com/McCLIM/McCLIM/blob/master/Libraries/ESA/esa.lisp#L840

**Comment by admich** [comment]
I think this is not an issue `execute-frame-command` is for execute not for redisplay, it is inside the command loop that after execution there is the redisplay (like in repl if you call eval outside the repl it doesn't call print).

So if you call manually `execute-frame-command` than you need to call manually `redisplay-frame-panes`.

In solution like #1082 the frame is redisplayed two times for each command inside the command loop. An application can also want to redefine the top level to not have the redisplay after each command.

If we want ee can think about a system to inject command inside the command loop with a command queue.

**Comment by dkochmanski** [comment]
When a pane has `:display-time :command-loop`, then that pane should be redisplayed after the command execution.

**Comment by admich** [comment]
Yes but inside the command loop. From Symbolic CLIM user guide I understand that the default frame top level works like a repl but with commands `read-frame-command` is the read part, `execute-frame-command` is the execute part and `redisplay-frame-panes` is the print part. If we trigger the rediplay from inside the execution it is harder to understand what happened and its easy to redisplay too often and we lost the possibility for an application to customize  the default top level loop.

I check clim-tos and there, ad I understand,  `execute-frame-command` doesn't call `redisplay-frame-panes`. Instead the frame has a command queue and if a command it's called from another thread a command event (for some reason called `presentation-event`) is generated. When the event is handled the command is pushed in the command queue. In this way the commands called from other  threads are called inside the command loop, and therfore they trigger the redisplay.

**Comment by dkochmanski** [comment]
I agree with your interpretation. We are basically half way there, because we do queue the event, however we are simply calling the from the handler, instead of making it return from read-frame-command (and execute in a frame)

```
(defmethod execute-frame-command ((frame application-frame) command)
  ;; ### FIXME: I'd like a different method than checking for
  ;; *application-frame* to decide, which process processes which
  ;; frames command loop. Perhaps looking ath the process slot?
  ;; --GB 2005-11-28
  (check-type command cons)
  (cond ((eq *application-frame* frame)
         (restart-case
             (apply (command-name command) (command-arguments command))
           (try-again ()
            :report (lambda (stream)
                      (format stream "Try executing the command ~S again." (command-name command)))
            (execute-frame-command frame command))))
        (t
         (let ((eq (sheet-event-queue (frame-top-level-sheet frame))))
           (event-queue-append eq (make-instance 'execute-command-event
                                                  :sheet frame
                                                  :command command))))))

(defmethod handle-event ((frame application-frame) (event execute-command-event))
  (execute-frame-command frame (execute-command-event-command event)))
```

**Comment by dkochmanski** [comment]
here's my proposal for fixing the issue: https://github.com/McCLIM/McCLIM/pull/1107

**Comment by dkochmanski** [comment]
fixed in master.
