### ISSUE TITLE
McClim failing to build on OpenBSD 6.8

### ISSUE THREAD

**Issue by abuhussain** [McCLIM/McCLIM#1088]
Yep, it's me again: the annoying guy trying to make mcclim work on OpenBSD, albeit this time actually using a more current ECL.

Build environment: 
Lisp implementation name: ECL
Lisp implementation version: 20.4.24
OS: OpenBSD 6.8 Stable
Hardware Architecture: SPARC64
McClim version: mcclim-20201016-git (latest available on Quicklisp)

What actually **is** happening is difficult to describe, however: After (ql:quickload "mcclim") and a whole lot of successfuly compiled files, the last message I get from the ECL compiler is that it finished compiling decls.lisp. Right after that, it just hangs. ECL does not exit or generate a core dump, ^-C has no effect, and one has to force-kill the ecl process. But: there is no processor activity while this is taking place, judging by 0,00% CPU usage listed by 'top'. Is there a way to somehow turn on more verbose compiling or creating/analysing a core dump so I can provide more information? Or has someone experienced this same behaviour in other platforms? I haven't experienced this behaviour with any other library in Quicklisp, even the bigger ones - e.g. Ironclad builds OK, and I have enough RAM on this box so I know that's also not a problem.

**Comment by scymtym** [comment]
Hi. I don't know much about ECL or OpenBSD, but one way to close in on the issue could be running the whole ECL process under `strace` or something similar and check whether the hanging is related to some interaction with the operating system like a blocking system call or an unexpected signal.

**Comment by abuhussain** [comment]
> 
> 
> Hi. I don't know much about ECL or OpenBSD, but one way to close in on the issue could be running the whole ECL process under `strace` or something similar and check whether the hanging is related to some interaction with the operating system like a blocking system call or an unexpected signal.

Yea on OpenBSD we've got ktrace, haven't thought about it yet. I'll try it out and let you know if I find anything meaningful.

**Comment by dkochmanski** [comment]
Hey, I've quickly looked into the issue. The problematic library is flexichain; I'm investigating the issue. It is present in the newest release and develop branch (of ecl) - the develop branch actually hints, that there is probably a missing call to with_disabled_interrupts. I'll keep you posted.

**Comment by dkochmanski** [comment]
Fixed: https://gitlab.com/embeddable-common-lisp/ecl/-/issues/610
Band-aid before ecl release: https://github.com/robert-strandh/Flexichain/pull/8

See the commit message in ecl repository for more details. Closing this issue, because McCLIM is not at fault and it has been addressed in other repositories.

Thanks for the report!
