### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [McCLIM/McCLIM#1111]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 91ac6a722e0f0356555a96804b1e459190a0a2c6

*clim-pdf* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10008D8083}>: The name "CLIM-POSTSCRIPT" does not designate any package.

```

*clim-pdf/test* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10008D8083}>: The name "CLIM-POSTSCRIPT" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2020-12-12/failure-report/mcclim.html)

**Comment by dkochmanski** [comment]
thanks, fixed in master. if it still fails for you please reopen.
