### ISSUE TITLE
make-table-array and empty column-based table

### ISSUE THREAD

**Issue by csrhodes** [McCLIM/McCLIM#1116]
I was able to get a crash in redisplay by displaying a table with a column but no cells; approximate test case is:

```
(let ((table (make-instance 'clim:standard-table-output-record))
               (column (make-instance 'clim:standard-column-output-record))
               (row (make-instance 'clim:standard-row-output-record)))
  (clim:add-output-record column table)
  (climi::make-table-array table))
```

(The call to `make-array-table` should return an array of arrays, but this returns an array containing `nil`, which causes a type error in `adjust-table-cells`).

A fix that works for me is to replace the `1` in:

https://github.com/McCLIM/McCLIM/blob/b222ab786fdf3c726c17bbb6311dc61cbf694fa0/Core/clim-core/table-formatting.lisp#L503

with `(if row-based 1 0)`.  (It's possible that a rewrite of `make-table-array` would make it clearer).

**Comment by scymtym** [comment]
Reproduced in b222ab786.

**Comment by dkochmanski** [comment]
adding a snippet for convenience

```
(let ((table (make-instance 'clim:standard-table-output-record))
      (column (make-instance 'clim:standard-column-output-record)))
  (clim:add-output-record column table)
  (clim:adjust-table-cells table nil))
```
