### ISSUE TITLE
How to use fcitx in Linux?

### ISSUE THREAD

**Issue by C-Entropy** [McCLIM/McCLIM#1128]
Can't switch fcitx input method.
According to [this](https://groups.google.com/g/fcitx-dev/c/Ef7aJI-j9T4), I suppose we either have to use existing xim(xlib)/xcb-imdkit(xcb) , or write one our own Mc-IM(clx) .
Any advice?

**Comment by dkochmanski** [comment]
I'd rather write Mc-IM that is not dependent on CLX (at least directly); that said no work is currently pending on this front.

**Comment by C-Entropy** [comment]
@dkochmanski I have beginning working on clx-im a bit, could you tell what is the benefits for Mc-IM? I thought that clx-im could support more than McCLIM, if there are other gui based on clx but not McCLIM.

**Comment by dkochmanski** [comment]
clx-im is definetely useful too. as of why climim would be beneficial - it would be easier to reuse it in new backends (i.e opengl)

**Comment by dkochmanski** [comment]
since the discussion moved to the clx repository I'm closing this issue to avoid duplication.

**Comment by C-Entropy** [comment]
I will try to take IM part away, so that it will be easier to port IM to other GUI set, once I have come to CLX-IM. But due to my personal interest, right now I am playing with musictag, so the CLX-IM may not come that quicklu, lol.

**Comment by C-Entropy** [comment]
I thinks this should be reopen since there is still some work to combine input method here. The clx-xim one just responsible to input method protocol, so if you want to make it work with mcclim, you still have to invoking it manually, which may need some work.
