### ISSUE TITLE
Accepting-value-test: accepting-with-gadgets with own-window t 

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1129]
In "Accepting-value-test" accepting-with-gadgets with own-window t doesn't work. The gadgets aren't displayed correctly and the application seems freeze.

**Comment by admich** [comment]
The problem start here with commit f792608321fb7fcdc271abba3ebd2ab4c9bb9974

**Comment by dkochmanski** [comment]
fixed in #1220
