### ISSUE TITLE
Missing implementation for note-command-enabled / -disabled and redisplaying the menu bar flashes

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1145]
I like the new modern menu navigation style (#1091), but it seems that one thing that has been lost is that changing menu commands' enabled / disabled status does not change whether the corresponding menu items are grayed out when they are displayed. I would expect this to be controlled through note-command-enabled / -disabled but there's a comment on these functions "XXX These should force the redisplay of the menu bar. They don't yet".

My application changes commands' enabled / disabled status dynamically, and it's important that this is reflected in whether the menu items can be selected or not. In the short term I've patched my application's code as follows:

```
(in-package :clim-user)

(defmethod note-command-enabled (frame-manager frame command-name)
  ;; since command enabled/disabled status is specific to an instance of a frame,
  ;; we flag the status update there
  (setf (frame-properties frame 'command-status-changed) t))

(defmethod note-command-disabled (frame-manager frame command-name)
  (setf (frame-properties frame 'command-status-changed) t))

(defmethod handle-event :before ((client climi::hmenu-pane) event)
  ;; force redisplay of frame's command table menu if a command has been enabled or
  ;; disabled since the menu was last (re-)displayed
  (let ((frame (pane-frame client)))
    (when (frame-properties frame 'command-status-changed)
      (setf (frame-command-table frame) (frame-command-table frame)))))

(defmethod (setf frame-command-table) :before (command-table frame)
  (setf (frame-properties frame 'command-status-changed) nil))
```

This works at a basic level, but the user experience is poor: redisplaying the menu bar causes the frame's contents to flash and other panes to be briefly resized. In my case there is an application pane below the menu bar which ends up being scrolled up by one line - not nice.

Is it possible to make redisplaying the menu bar work more smoothly?

**Comment by dkochmanski** [comment]
yes, I will take a closer look after I'm finished with double buffering. Good catch!

**Comment by dkochmanski** [comment]
fixed in master. I've changed (mainly) two things:
- updating the menu is wrapped in changing-space-requirements, so if the resulting size is the same as the former one, there shouldn't be a flash caused by the size change
- when disabling and enabling a command, I'm updating only specific leaf buttons (so changes are minimal and it doesn't cons)
