### ISSUE TITLE
Bug in pattern output when pane has been scrolled

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1150]
In application panes, patterns draw OK but are not recorded (or perhaps not redisplayed) properly. Run this:

```
(in-package :clim-user)

(defparameter +pattern+
  (make-pattern
    #2A((0 0 1 1 0 0 1 1)
        (1 1 0 0 1 1 0 0)
        (0 0 1 1 0 0 1 1)
        (1 1 0 0 1 1 0 0)
        (0 0 1 1 0 0 1 1)
        (1 1 0 0 1 1 0 0)
        (0 0 1 1 0 0 1 1)
        (1 1 0 0 1 1 0 0))
    (list +white+ +black+)))

(define-application-frame drawtest () ()
  (:panes
    (p1
      (make-pane 'application-pane
        :display-function 'display-pattern)))
  (:layouts
    (default
      (scrolling () p1))))

(define-presentation-type foo ())

(define-drawtest-command com-select-string
    ((data 'foo :gesture :select))
  (declare (ignore data)))

(defun display-pattern (frame stream)
  (declare (ignore frame))
  (window-clear stream)
  (loop for x from 4 below 400 by 100
    do
    (loop for y from 4 below 400 by 100
      do
      (with-output-as-presentation (stream "a" 'foo :single-box t)
        (draw-pattern* stream +pattern+ x y)
        (draw-rectangle* stream (+ x 20) y (+ x 28) (+ y 8) :filled nil)
        (draw-text* stream "a" (+ x 40) y :align-y :top)))))
 
(run-frame-top-level (make-application-frame 'drawtest))
```

Move the mouse over the presentations. When moving out of a presentation, the rectangle and text remain (expected) but the pattern disappears (unexpected). When the frame is resized larger to expose new content, the patterns that should be newly exposed are not displayed. However, they are displayed if the pane is scrolled.

One particularly odd thing: the top left pattern never completely disappears, but it can get cut down to its bottom right 4x4 quadrant.

**Comment by john-a-carroll** [comment]
I've inspected the output records, and those corresponding to the patterns have a standard-translation transformation that is the same as their position relative to the origin of the parent stream. Is it possible that during replay this transformation is incorrectly applied relative to the top left of the output record?

Here's the bottom right pattern, at position (304, 312) in the parent stream:

```
The object is a STANDARD-OBJECT of type CLIM-INTERNALS::DRAW-RECTANGLE-OUTPUT-RECORD.
0. COORDINATES: #(304 304 312 312)
1. PARENT: #<STANDARD-PRESENTATION 304:350,303.5:161351/512 FOO {10101F5DE3}>
2. INK: #<CLIM-EXTENSIONS:TRANSFORMED-PATTERN {10101F6303}>
3. CLIPPING-REGION: #<CLIM-INTERNALS::EVERYWHERE-REGION {1000FD8A63}>
4. STREAM: #<CLIM-CLX::|CLX-41716-CLIM:APPLICATION-PANE| P1 {100FF42BC3}>
5. LINE-STYLE: #<STANDARD-LINE-STYLE :UNIT :NORMAL :THICKNESS 1 :JOINT-SHAPE :MITER :CAP-SHAPE :BUTT :DASHES NIL>
6. LEFT: 304
7. TOP: 304
8. RIGHT: 312
9. BOTTOM: 312
10. FILLED: T
> 2

The object is a STANDARD-OBJECT of type CLIM-EXTENSIONS:TRANSFORMED-PATTERN.
0. TRANSFORMATION: #<CLIM-INTERNALS::STANDARD-TRANSLATION :DX 304 :DY 304>
1. DESIGN: #<CLIM-INTERNALS::INDEXED-PATTERN {1026D17533}>
```

**Comment by john-a-carroll** [comment]
In any case, since the pattern is used as the ink for filling a rectangle, surely it shouldn't be translated at all?

**Comment by john-a-carroll** [comment]
This issue seems to be partly resolved in the latest version, from earlier today. BUT... only when the frame is scrolled fully to the top and the left.

To see the buggy behaviour, run the code above, reduce the window size and scroll down and/or right. The patterns still disappear.

**Comment by dkochmanski** [comment]
this larger pattern reveals, that the problem is with clipping, not the pattern itself:
```
(defparameter +pattern+
  (make-pattern
    #2A((0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3)
        (2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3))
    (list +blue+ +red+ +green+ +black+)))
```

![image](https://user-images.githubusercontent.com/6871201/113898794-7bbc6980-97cc-11eb-9b4c-0ce2ddf08ffe.png)

**Comment by dkochmanski** [comment]
fixed. the issue was local to the clx backend (i.e it did not originate in the core) - namely when computing the design, the mask did not account for the device transformation. as noted in #1180, issues had the same underlying bug. thanks for the report.

**Comment by john-a-carroll** [comment]
@dkochmanski thank you for fixing this issue!
