### ISSUE TITLE
build fails on master

### ISSUE THREAD

**Issue by nsrahmad** [McCLIM/McCLIM#1161]
with error:
```lisp
; Loading "clim-examples"
......

; file: /home/nsrahmad/common-lisp/McCLIM/Backends/CLX/medium.lisp
; in: DEFMETHOD MEDIUM-DRAW-ELLIPSE* (CLX-MEDIUM T T T T T T T T T)
;     (CLIM-CLX::TR (CLIM-BACKEND:MEDIUM-NATIVE-TRANSFORMATION CLIM:MEDIUM)
;      CLIM-CLX::CENTER-X CLIM-CLX::CENTER-Y)
; 
; caught ERROR:
;   The LET binding spec (TR (MEDIUM-NATIVE-TRANSFORMATION MEDIUM) CENTER-X
;                         CENTER-Y) is malformed.
```
That malformed let is here:
https://github.com/McCLIM/McCLIM/blob/b54f8b1379d472e4ba605c9f2e1fc5a1a1aae78a/Backends/CLX/medium.lisp#L705

**Comment by dkochmanski** [comment]
Interesting, sbcl doesn't have this issue (nor failures in the second issue). I'm on it (thanks for the report, I should test on three implementations before making such changes).

**Comment by nsrahmad** [comment]
If you read RSS feeds you may subscribe to http://report.quicklisp.org/feeds/project/mcclim.rss , which showed today http://report.quicklisp.org/2021-03-04/failure-report/mcclim.html
