### ISSUE TITLE
Regressions in scrolling: output bunching and thumb size

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1170]
```
(in-package :clim-user)

(define-application-frame output-test () ()
  (:panes
    (p1
      (make-pane 'application-pane
        :display-time t)))
  (:layouts
    (default
      (scrolling () (spacing (:thickness 3 :background +white+) p1)))))

(define-output-test-command com-run ()
  (loop for i from 0 to 100
      do (format t "~R~%" i) (sleep 0.1)))

(define-command-table output-test
  :menu (("Run" :command com-run)))

(run-frame-top-level (make-application-frame 'output-test))
```

The application pane fails to scroll while the `Run` command is in progress. Once output reaches the bottom of the application pane it bunches up at the bottom in an increasingly black splotch, and is only drawn legibly once the command finishes. The same thing happens without the spacing layout pane.

My system uses such an application frame for showing the user diagnostics and progress logs from CPU-intensive computations – the unreadable output is pretty bad for the user experience.

Relatedly, both scroll bar thumbs are wrongly sized, since they allow the window to be scrolled even when the content fits in the respective dimension. Scroll bars seem to be computed based on the size of the application pane, not the size of the pane they immediately enclose (the spacing pane in this case).

Although in general scrolling is much better than it used to be (thanks!), both of these issues are recent regressions: since late January I believe.

**Comment by dkochmanski** [comment]
not scrolling on new output is an issue which dates back to when delayed repaint was introduced. I will remove the optimization, because calling on delayed sheets dispatch-repaint leads to this issue while calling repaint-sheet confuses drei.

**Comment by john-a-carroll** [comment]
Thanks, that's very helpful.
