### ISSUE TITLE
Old clim application SLS

### ISSUE THREAD

**Issue by idurand** [McCLIM/McCLIM#1183]
Hi everybody,

In june I must give a little demo of a quite old McClim application (SLS)
https://dept-info.labri.fr/~idurand/SLS/

A few weeks ago, I compiled and run the app without any problem.
Today though, I had to update and install some new packages in order to compile.
The compilation gave a lot of warnings and the executions fails:

Did some specification change? 
At the time, I have no time no inclination to dive into McClim.
If some of you has a quick answer that would solve the problem, it would be welcome.

The code is git clonable at git clone https://idurand@bitbucket.org/idurand/smots.git
The execution error is given below.

Best regards,
Irène

CL-USER> (asdf:make "visu-smots")
T
CL-USER> (visu-smots::start)
The function VISU-SMOTS::MAKE-MENU-BAR is undefined.
   [Condition of type UNDEFINED-FUNCTION]

Restarts:
 0: [CONTINUE] Retry calling VISU-SMOTS::MAKE-MENU-BAR.
 1: [USE-VALUE] Call specified function.
 2: [RETURN-VALUE] Return specified values.
 3: [RETURN-NOTHING] Return zero values.
 4: [RETRY] Retry SLIME REPL evaluation request.
 5: [*ABORT] Return to SLIME's top level.
 --more--

Backtrace:
  0: ("undefined function" VISU-SMOTS::MENUBAR-COMMAND-TABLE)
  1: ((:METHOD CLIM:GENERATE-PANES (CLIM:STANDARD-FRAME-MANAGER VISU-SMOTS::VISU-SMOTS)) #<CLIM-CLX::CLX-FRAME-MANAGER {103BB713F3}> #<VISU-SMOTS::VISU-SMOTS {103B997493}>) [fast-method]
  2: ((SB-PCL::EMF CLIM:GENERATE-PANES) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-FRAME-MANAGER {103BB713F3}> #<VISU-SMOTS::VISU-SMOTS {103B997493}>)
  3: ((:METHOD CLIM:ADOPT-FRAME (CLIM:STANDARD-FRAME-MANAGER CLIM:STANDARD-APPLICATION-FRAME)) #<CLIM-CLX::CLX-FRAME-MANAGER {103BB713F3}> #<VISU-SMOTS::VISU-SMOTS {103B997493}>) [fast-method]
  4: ((SB-PCL::EMF CLIM:ADOPT-FRAME) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-FRAME-MANAGER {103BB713F3}> #<VISU-SMOTS::VISU-SMOTS {103B997493}>)
  5: ((:METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)) #<VISU-SMOTS::VISU-SMOTS {103B997493}>) [fast-method]
  6: (VISU-SMOTS::RUN-TEST VISU-SMOTS::VISU-SMOTS)
  7: (VISU-SMOTS::INTERFACE)
  8: (VISU-SMOTS::START)
  9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (VISU-SMOTS::START) #<NULL-LEXENV>)
 10: (EVAL (VISU-SMOTS::START))
 --more--

**Comment by dkochmanski** [comment]
visu-smots application frame uses an internal function `climi::make-menu-bar` so strictly speaking it is not a regression in McCLIM. The fix is to use the menu-bar supplied by the frame manager by utilising the :menu-bar option to define-application-frame. Here's a diff that makes visu-smots start for me:

```diff
diff --git a/Visu/interface.lisp b/Visu/interface.lisp
index 0cf0284..08a6632 100644
--- a/Visu/interface.lisp
+++ b/Visu/interface.lisp
@@ -240,6 +240,7 @@
 
 (define-application-frame visu-smots ()
   ()
+  (:menu-bar menubar-command-table)
   (:panes
    (problem-pane
     (make-pane 'clim-stream-pane
@@ -256,8 +257,9 @@
    (result-pane
     (make-pane 'clim-stream-pane :name 'result-pane))
    (interactor-pane :interactor)
-;;   (display-pane :application
-;;              :display-function 'draw-display)
+   ;;   (display-pane :application
+   ;;           :display-function 'draw-display)
+   #+ (or)
    (menu-bar
     (climi::make-menu-bar 'menubar-command-table))
    ;; ;;    (make-pane 'text-field :value *data-directory*
@@ -289,7 +291,7 @@
    ;;                     (com-stop)))
    (clear
     :push-button
-    :label "clear"                    ;:max-width 100 :max-height 100
+    :label "clear"                      ;:max-width 100 :max-height 100
     :activate-callback (lambda (x)
                         (declare (ignore x))
                         (com-clear)))
@@ -338,7 +340,6 @@
   (:layouts
    (default
        (vertically (:width 800)
-        menu-bar
         (vertically ()
           (horizontally (:height 100) interactor-pane)
           (scrolling (:height 150) problem-pane)
```

**Comment by dkochmanski** [comment]
I'm closing this ticket; if you feel that it is not solved then please reopen.

**Comment by idurand** [comment]
It worked. Thanks a lot Daniel.
