### ISSUE TITLE
CLIM:SHEET-REGION in Smots

### ISSUE THREAD

**Issue by idurand** [McCLIM/McCLIM#1184]
Hi,

It's me again with my old McClim application.
https://idurand@bitbucket.org/idurand/smots.git

When I do the following commands:
I get an error with CLIM:SHEET-REGION that did not happend before.
Did something change with this function?

Thanks for your help.
Irène

----------------------------------------
CL-USER> (asdf:make "visu-smots")
T
CL-USER> (visu-smots::start)
----------------------------------------
Command: Load Spec
spec filename: trains.txt
Command: Random Sword
----------------------------------------
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-REGION (4)>
when called with arguments
  (NIL).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [TRY-AGAIN] Try executing the command VISU-SMOTS::COM-RANDOM-SWORD again.
 2: [ABORT] Return to application command loop.
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1009E41B63}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-REGION (4)> NIL) [fast-method]
  1: ((LAMBDA (SB-PCL::.ARG0. SB-INT:&MORE SB-PCL::.MORE-CONTEXT. SB-PCL::.MORE-COUNT.) :IN "/home/idurand/quicklisp/setup.lisp") #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-REGION (4)> NIL)
  2: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM:SHEET-REGION (4)> (NIL))
  3: (VISU-SMOTS::GET-HEIGHT NIL)
  4: (VISU-SMOTS::DRAW-AXIS NIL)
  5: (VISU-SMOTS::DRAW-CANVAS #<VISU-SMOTS::SMOTS-DISPLAY {106E8BC9B3}> NIL)
  6: (VISU-SMOTS::DRAW-DISPLAY #<unused argument> NIL)
  7: (VISU-SMOTS::UPDATE-DISPLAY)

2
  8: (VISU-SMOTS::SET-AND-DISPLAY-CURRENT-SWORD [{#1=a#2=,#3=e#2##4=c#2##5=d#2##6=f}#7={#1##2##8=b#2##4##2##5#}#7#{#1##2##8##2##4##2##5#}#7#{#1##2##4##2##5##2##6#}#7#{#1##2##8##2##3##2##4##2##5#}#7#{#1##2#..
  9: (VISU-SMOTS::COM-RANDOM-SWORD)
 10: ((:METHOD CLIM:EXECUTE-FRAME-COMMAND (CLIM:STANDARD-APPLICATION-FRAME T)) #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}> (VISU-SMOTS::COM-RANDOM-SWORD)) [fast-method]
 11: ((FLET CALL-NEXT-METHOD :IN "/home/idurand/smots/Visu/interface.lisp"))
 12: ((:METHOD CLIM:EXECUTE-FRAME-COMMAND :AROUND (CLIM:APPLICATION-FRAME T)) #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}> (VISU-SMOTS::COM-RANDOM-SWORD)) [fast-method]
 13: ((FLET CLIM-INTERNALS::EXECUTE-COMMAND :IN CLIM:DEFAULT-FRAME-TOP-LEVEL))
 14: ((:METHOD CLIM:DEFAULT-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)) #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}> :COMMAND-PARSER CLIM:COMMAND-LINE-COMMAND-PARSER :COMMAND-UNPARSER CLIM:COMMAND-LINE-COMMAND-UNP..
 15: ((SB-PCL::EMF CLIM:DEFAULT-FRAME-TOP-LEVEL) #<unused argument> #<unused argument> #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}>)
 16: ((LAMBDA (#:FRAME-ARG0) :IN "/home/idurand/smots/Visu/interface.lisp") #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}>)
 17: ((:METHOD CLIM:RUN-FRAME-TOP-LEVEL (CLIM:APPLICATION-FRAME)) #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}>) [fast-method]
 18: ((FLET CALL-NEXT-METHOD :IN "/home/idurand/quicklisp/dists/quicklisp/software/mcclim-20210411-git/Core/clim-core/frames/frames.lisp"))
 19: ((:METHOD CLIM:RUN-FRAME-TOP-LEVEL :AROUND (CLIM:APPLICATION-FRAME)) #<VISU-SMOTS::VISU-SMOTS {106E8BEAC3}>) [fast-method]
 -

**Comment by dkochmanski** [comment]
Hey. One technical remark for reporting: if you quote a code to prevent the formatting, put it in three backquotes like these:

    ```
    put the code here
    ```

That said, the problem is that the function `update-display` is called despite *display-pane* being nil.

It is nil, because the pane is commented out in visu-smots application frame definition (I've marked relevant parts with `^^^^^^`):

```
(define-application-frame visu-smots ()
  ()
  (:menu-bar menubar-command-table)
  (:panes
   (problem-pane
    (make-pane 'clim-stream-pane
	       :name 'problem-pane))
   (sexpr-pane
    (make-pane 'clim-stream-pane
	       :name 'sexpr-pane))
   (slanguage-pane
    (make-pane 'clim-stream-pane
	       :name 'slanguage-pane))
   (sword-pane
    (make-pane 'clim-stream-pane
	       :name 'sword-pane))
   (result-pane
    (make-pane 'clim-stream-pane :name 'result-pane))
   (interactor-pane :interactor)
   ;;   (display-pane :application
   ;;		 :display-function 'draw-display)
   ;; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   (menu-bar :menu-pane)
   ;; ;;    (make-pane 'text-field :value *data-directory*
   ;;     (make-pane 'data-directory-field :height 4 :width :compute
   ;; 	       :display-function 'display-ddp
   ;; ;;	       :activate-callback (lambda (x) (change-data-directory x))
   ;;        ))
   (data-directory-field
    :text-field
    :editable-p nil
    :value *data-directory* :height 4)
   ;;    (make-pane 'data-directory-field
   ;;	       :height 4 
   ;; 	       :armed t
   ;; 	       :display-function 'display-ddp
   ;;	       :incremental-redisplay t
   ;;	       ))
   (quit
    :push-button
    :label "Quit"
    :activate-callback (lambda (x)
			 (declare (ignore x))
			 (com-quit)))
   ;;    (stop
   ;;     :push-button
   ;;     :label "Stop"
   ;;     :activate-callback (lambda (x)
   ;; 			 (declare (ignore x))
   ;; 			   (com-stop)))
   (clear
    :push-button
    :label "clear"                      ;:max-width 100 :max-height 100
    :activate-callback (lambda (x)
			 (declare (ignore x))
			 (com-clear)))
   (mark-button
    :toggle-button
    :label "Marks"
    :indicator-type :one-of
    :value *show-mark*
    :value-changed-callback
    (lambda (gadget value)
      (declare (ignore gadget value))
      (com-toggle-mark)))
   (egraph-button
    :toggle-button
    :label "Egraphs"
    :indicator-type :one-of
    :value *egraph-mode*
    :value-changed-callback
    (lambda (gadget value)
      (declare (ignore gadget value))
      (com-toggle-egraph-mode)))
   ;;    (process-button
   ;;     :toggle-button
   ;;     :label "Processes"
   ;;     :indicator-type :one-of
   ;;     :value *with-processes*
   ;;     :value-changed-callback
   ;;     (lambda (gadget value)
   ;;       (declare (ignore gadget value))
   ;;       (com-toggle-processes)))
   ;;    (processname-pane
   ;;     :text-field
   ;;     :editable-p nil
   ;;     :value (normalize-string "no running process" +largeur-texte+))
   ;;    (progress-pane
   ;;     :text-field
   ;;     :editable-p nil
   ;;     :value (normalize-string "-" +largeur-texte+))
   (display-button
    :push-button
    :label "Show graphic display in a separate window"
    :activate-callback (lambda (x)
			 (declare (ignore x))
			 (com-display-window)))
   )
  (:layouts
   (default
       (vertically (:width 800)
	 menu-bar
	 (vertically ()
	   (horizontally (:height 100) interactor-pane)
	   (scrolling (:height 150) problem-pane)
	   (scrolling (:height 150) sexpr-pane)
	   (horizontally (:height 100)
	     (scrolling () sword-pane)
	     (scrolling () slanguage-pane))
	   (scrolling (:height 100) result-pane)
;;	   (scrolling (:height 100) display-pane)
;; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	   )
	 (horizontally ()
	   quit clear data-directory-field egraph-button display-button mark-button)))))
```

So the method `default-frame-top-level :before` when setting *display-pane* by calling
```
(setf *display-pane* (climi::find-pane-named *application-frame* 'display-pane))
```

binds it to nil. there are two solutions to the problem:
- add back the display-pane
- add checks in functions relying on the display-pane
The latter could be done with this diff:

```diff
diff --git a/Visu/toy.lisp b/Visu/toy.lisp
index f906acb..f285ed8 100644
--- a/Visu/toy.lisp
+++ b/Visu/toy.lisp
@@ -54,10 +54,12 @@
   (scroll-extent *problem-pane* 0 0))
 
 (defun update-display ()
-  (draw-display nil *display-pane*))
+  (when *display-pane*
+   (draw-display nil *display-pane*)))
 
 (defun clear-display ()
-  (window-clear *display-pane*))
+  (when *display-pane*
+    (window-clear *display-pane*)))
 
 (defun display-current-problem ()
   (clear-problem-pane)
```
