### ISSUE TITLE
Menu commands not executed when run inside WITH-INPUT-CONTEXT

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#1187]
This issue was introduced with change 3b78bb2f8471c2cbcc9c65bf1c3d8b32c65f0dc0

Example code here: https://github.com/lokedhs/clim-test/blob/master/menu-test2.lisp

When running the program and selecting the "quit" menu option, the function `FOO-QUIT` should be called which should print a message. This does not happen, and it seems as though the command is ignored. The default handler is executed instead which can be seen by the message "other command type".

**Comment by dkochmanski** [comment]
the method read-frame-command doesn't return a command in this code. if you redefine it to:
```
(defmethod clim:read-frame-command ((frame foo-frame) &key (stream *standard-input*))
  (let ((result (clim:accept 'foo-expression-or-command :stream stream)))
    (log:info "result = ~s" result)
    result))
```
then the command is executed.

probably a more correct approach would involve a loop that returns when the command is read, and loops over when it is an expression. closing for now.
