### ISSUE TITLE
Some symbols in CLIM-BACKEND package is specific to clx backend

### ISSUE THREAD

**Issue by ailisp** [McCLIM/McCLIM#119]
They are not in spec and not used in code outside CLIM-CLX package, I think they should not be generic functions appear in decls.lisp file but private functions or methods in CLIM-CLX package. They are: (I have checked via slime-xref and grep -nHr)

- mirror-transformation ; (this stands for a (make-translation-transformation mirror-top-left-corner-x-in-parent-coord mirror-top-left-corner-y-in-parent-coord), only works as a private utility in clx
- medium-draw-glyph ; (glyph seems to be a clx only notion)
- port-mirror-height ; (this and port-mirror-width is not used, even in clx it only use for debug (#+nil) currently, maybe useful in the future? 
- port-mirror-width 
- port-motion-hints ; motion hints is a X notion, means not to send pointer motion event until button pressed, this is possible on Windows if we write event handler to discard motion event until button pressed event and then send these filtered event to clim, but this can't lead to performance increase since Windows will still catch these events, while in X, clim can tell X not to record these events from origin. I checked beagle backend as well, but it just warn this is not supported. Even for clx, port-motion-hints and (setf port-motion-hints) are not used by any code (and also not used by the whole mcclim). So this may also be CLIM-CLX specific?

**Comment by dkochmanski** [comment]
Hey, sorry for late response. If these symbols are not part of the spec and referred only in `clim-clx` they shouldn't be in `decls.lisp` indeed.

**Comment by ailisp** [comment]
I find there are other symbols and will continue list them here. If I make
the Windows Backend work, I think I could categories climb symbols into
three kinds: must implement to make mcclim work (like medium-draw-*);
optional if implement can enhance functionalities (like native mirror of
gadgets); platform specific functions that other platforms do not have.
This may be helpful for others want to implement a backend.

2016年12月6日 下午4:02，"Daniel Kochmanski" <notifications@github.com>写道：

**Comment by dkochmanski** [comment]
this will be very helpful for internal documentation, yes

**Comment by nsrahmad** [comment]
At various points in time, All of the above mentioned funtions are removed as redundant.
