### ISSUE TITLE
When should the PORT slot of the APPLICATION-FRAME be filled in?

### ISSUE THREAD

**Issue by splittist** [McCLIM/McCLIM#1195]
This question arose because `OPEN-WINDOW-STREAM` fails.

There is a call in `MAYBE-ADD-AUXILIARY-PANES` to `(PORT frame)`, when trying to `MAKE-INSTANCE` the `'VRACK-PANE` for the menu bar. But `MAYBE-ADD-AUXILIARY-PANES` is called within `GENERATE-PANES :AFTER` before the `FRAME` is adopted by the `TOP-LEVEL-SHEET`.  Because (?) `A-WINDOW-STREAM` is a `STANDARD-EXTENDED-INPUT-STREAM` before it is a `STANDARD-APPLICATION-FRAME`, the `PORT` accessor method on `STANDARD-SHEET-INPUT-MIXIN` is called rather than the `PORT` method on `STANDARD-APPLICATION-FRAME`, returning NIL rather than the `PORT` of the `FRAME-MANAGER` (which the latter method would give).

So `MAKE-MEDIUM` is called with `NIL` as port when trying to create the `VRACK-PANE`.

**Comment by dkochmanski** [comment]
as you have pointed out, the issue is that this class should be first and foremost a frame, only after that a sheet.
