### ISSUE TITLE
About commit: frame-manager: better reinitialization

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#1204]
About commit 09183857f8ea0300032ebd6e43b89c2a5055e9ac I think that beause in the spec is written that the frame top-level-sheet is an ancestor of (frame-panes frame)  but not the direct parent, instead of:
```(sheet-disown-child top-level-sheet panes)```
is better:
```(sheet-disown-child (sheet-parent panes) panes)```

**Comment by dkochmanski** [comment]
I agree that spec says that it may be a putative ancestor.

> The value returned by frame-panes will be a descendents of the value of frame-top-level-sheet.

That said:
- both disown-frame-panes and adopt-frame-panes are internal protocols that work in tandem (and adopt-frame-panes makes the top level sheet the direct ancestor of panes - after your last commit at least)
- assuming that it is not the direct ancestor we have three strategies that make sense:

1. as you say, panes are disowned by their parent (the parent may be something else than top level sheet)
```
(sheet-disown-child (sheet-parent panes) panes))
```

2. wrappers around frame panes should also be disowned (arguably makes more sense because it "clerars" the tpl sheet)
```
(sheet-disown-child tpl-sheet (find-direct-tpl-child panes))
```

3. make a shortcut and take the advantage of knowing that we adopt directy to tpl sheet
```
(assert (eq (sheet-parent panes) tpl-sheet))
(sheet-disown-child tpl-sheet panes)
```

**Comment by admich** [comment]
Ofcourse for the actual state of McCLIM code all solutions are good, but also 
```
(sheet-disown-child tpl-sheet (sheet-child tpl-sheet))
```
was good because tpl-sheet is a single child sheet now.

For future extension I think that the first solution is the better. For example some  weird future frame-manger could have more than one application under the same tpl-sheet and so its not necessary/desiderable to clear the tpl as the second solution does.

**Comment by admich** [comment]
Ofcourse for the actual state of McCLIM code all solutions are good, but also 
```
(sheet-disown-child tpl-sheet (sheet-child tpl-sheet))
```
was good because tpl-sheet is a single child sheet now.

For future extension I think that the first solution is the better. For example some  weird future frame-manger could have more than one application under the same tpl-sheet and so its not necessary/desiderable to clear the tpl as the second solution does.

**Comment by dkochmanski** [comment]
The second solution clears the tpl-sheet from only the branch that has the frame panes, i.e assuming that there is a wrapper with extra menu and pdoc that is not included in frame panes we have:

```
             +--- (vbox menu layout-1 pdoc)
             |
tpl-sheet ---+--- layout-2

(sheet-disown-child (sheet-parent layout-1) layout-1))

             +--- (vbox menu pdoc)
             |
tpl-sheet ---+--- layout-2

;; vs this, where we remove the direct child
-----------------------------------------------------------

             +--- (vbox menu layout-1 pdoc)
             |
tpl-sheet ---+--- layout-2

; (find-direct-tpl-child layout-1) -> vbox
(sheet-disown-child tpl-sheet (find-direct-tpl-child layout-1))

tpl-sheet ---+--- layout-2
```

**Comment by dkochmanski** [comment]
n.b the commit in question was precisely to do that - I've started sketching a demo with a frame/frame-manager having a bboard pane that "hosts" other frames.

**Comment by admich** [comment]
You convinced me the second solution is the best and more flexible. After it is implemented my commit about frame-panes and pointer-doc can be reverted.

ps: another funny frame-manager could have a shared (between applications) pdoc and menu (like Mac)

**Comment by dkochmanski** [comment]
regarding shared pdoc and menu, there is also another interesting use case: frames that are panes of other panes. then the master pane "owns" the menu and the pdoc. example: embed the inspector and the listener as panes in some code editor.
