### ISSUE TITLE
Presentation popup menu regression

### ISSUE THREAD

**Issue by jmorrison** [McCLIM/McCLIM#1245]
The below works (albeit printing the strings as sequences) on quicklisp vintage 20 DEC 2020 ("mcclim-20201220-git"), and fails on most recent git clone.  Ends up in the debugger.  Click right on the "menu OK" lists brings up expected menu, but on recent McCLIM clicking right on "menu NOT ok" cons cells lands you in the debugger.  Sorry if this is Pilot Error, and expected behavior.

```
(ql:quickload :mcclim)

(in-package :clim-user)

;; presentation type 
(define-presentation-type thang ())
(define-presentation-method present (object (type thang) stream view &key)
  (declare (ignore view))
  (print-object object stream)
  (terpri stream))

(define-application-frame test-thangs ()
  ((thangs
    :initform
    '(("menu ok" 2)
      ("menu ok" 4)
      ("menu NOT ok" . 2)
      ("menu NOT ok" . 4))
    ))
  (:panes
   (output
    :application
    :display-time :command-loop
    :display-function 'display-thangs)
   (interactor
    :interactor))
  (:layouts
   (default (vertically () output interactor))))

(defmethod display-thangs ((frame test-thangs) stream)
  (dolist (item (slot-value frame 'thangs))
    (present item 'thang :stream stream)))

(define-test-thangs-command (com-select-thang
			     :menu "Select Thang"
			     :name "Select Thang")
    ((thang 'thang :gesture :select))
  (format t "select thang ~s~%" thang))

(run-frame-top-level (make-application-frame 'test-thangs))
```

**Comment by jmorrison** [comment]
Should have mentioned I got hit with this when my quicklisp GUI app started failing on recent McCLIM versions.  Quicklisp's "dists" are described by cons cells of date/URL pairing.  I had various commands put on the versions, including "install."

**Comment by dkochmanski** [comment]
Hey, I'm not sure which commit caused the regression, but the fix is straightforward. Thanks for the report.

**Comment by jmorrison** [comment]
Hi Daniel;

Thank you for the "thank you," but it is I who thank YOU, and all the other
contributors, past, present, and future, for all your hard work.  And it is
indeed a beautiful piece of work (says John, who has used many a GUI
toolkit in his day).

-jm
