### ISSUE TITLE
Keyword parameters leaks internal implementation details

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#1275]
When creating a command with a &KEY parameter and the parameter is not specified when calling the command, the parameter gets assigned the value `CLIM-INTERNALS::%UNSUPPLIED-ARGUMENT-MARKER%` instead of NIL.

The following example demonstrates the issue: https://github.com/lokedhs/clim-test/blob/master/simple-multi-arg.lisp

To reproduce the problem, type "bar" followed by space, then a single word for arg0, and then press return. The command will print its arguments, and the output is as follows:

```
  Result: ((SIMPLE-MULTI-ARG::BAR-COMMAND "foo"))
arg0="foo" key-arg=CLIM-INTERNALS::%UNSUPPLIED-ARGUMENT-MARKER%
```

**Comment by dkochmanski** [comment]
the specification mentions a `default` parameter to specify the default value. defaulting to nil in general doesn't make sense unless the argument presentation type is null. there is also a parameter `when` to make the argument "inactive" under certain conditions.
