### ISSUE TITLE
find-concrete-class in clx backend can be more generic

### ISSUE THREAD

**Issue by ailisp** [McCLIM/McCLIM#128]
When using clx backend, and call something like `(make-pane 'push-button)`, the `make-pane-1` method for clx backend will be called. This method first find push-button's corresponding concrete pane class (push-button-pane). Then will check whether it has been mirrored to a native push button, if so create corresponding mirrored push button as result.

The problem is the looking for push-button-pane process is dynamic and every time create pane it calls find-concrete-pane-class, (clx/frame-manager.lisp, line 66) which calls three helper function to find the same result. I think it's unnecessary here since the concrete class for each abstract gadget should always be same for a given backend. A parameter indicate which abstract class map to which concrete class is enough, more simple and more efficient.

Also, the make-pane-1 logic is quite generic. As I observed, it works in the same way in beagle and graphic-forms backend as clx:
```lisp
(defmethod make-pane-1 ((fm one-of-frame-manager-class) (frame application-frame) type &rest args)
  (apply #'make-instance
	 (maybe-mirroring (find-concrete-pane-class type))
	 :frame frame
	 :manager fm
	 :port (port frame)
	 args))
```
The differences between backends are just `maybe-mirroring` and `find-concrete-pane-class`, and they are constant mappings (concrete to mirrored class mapping, abstract to concrete class mapping), so may be it should be enough to provide `make-pane-1` a default method for `clim:frame-manager` class and  change `find-concrete-pane-class` to generic function of frame manager. (mostly same among backends so also provide a generic function), and modify clx's maybe-mirroring to directly return mapping result based on a defparameter for clx. I am not sure whether this make sense. Thanks and happy new year!

**Comment by dkochmanski** [comment]
`find-concrete-pane-class` is CLX-specific. There should be no problem with making it a generic function- but I think it's not worth a fuss, because user will have to define method for find-concrete-pane-class instead of make-pane-1 (you gain nothing except extra abstraction, you have to define one method anyway).

**Comment by gas2serra** [comment]
Hi @ailisp,
I looked at your code, it is very interesting. I like a lot your solution about a server backend. I think it will be useful for many backends because It is a lot simpler making and debugging a single threaded backend. Is it working? Will be nice to have a "standard-server-backend-mixin".

I have seen you are using full-mirrored-sheet-mixin. Have you tried to use "single-mirrored-sheet-mixin"? I'm asking because it will be nice to test it with a different backend. Do you have intention to use "native window gadgets"?

I have seen you have problems with "double-buffering". At the moment we use a dirty workaround, we need something better. Do you find a good solution?

Regards,
Alessandro

**Comment by ailisp** [comment]
Hi Alessandro,

Thanks for your suggestions. Currently only 1/4 of demodemo works, and now
I imitate your code on backends to make more demos working.  As for
standard-server-backend-mixin, I may have to postpone this later.

I will try to switch to single-mirrored-sheet-mixin, however, I have a
question, kind of silly, if non top-level sheets not mirrored, how to
figure out pointer-enter and pointer-leave events. When mirrored, these are
emitted by X. I found you call xlib:create-window in realize-mirror for
basic-pane (which is called on non top level sheet). so these non top level
panes have corresponding foreign object in X, they are still "mirrored"? Or
my conception of mirroring is wrong.

For native gadgets, I have intention to use native window gadgets, provide
both frame managers as in beagle backend. For double-buffering, do you mean
the def of (invoke-)with-double-buffering or flickering when resize or open
a new window with lots of gadgets then gadgets don't show up at the same
time?

Sincerely,

Bo

2017-01-08 6:24 GMT-05:00 gas2serra <notifications@github.com>:

**Comment by gas2serra** [comment]
In single-mirrored-sheet-mixin a non top-level-sheet has not a corresponding foreign object in X and it is not mirrored. You can use standard-handled-event-port-mixin (Standard/events.lisp). This class distributes all pointer events (pointer-enter, pointer-leave, pointer grabbing, ...) to the correct sheet. It is used by CLXv3. You can test it using 

```
(require :mcclim-clxv3/pretty)
(setf clim:*default-server-path*  (list :clxv3))
...
```
The problem with single-mirrored-sheet-mixin is that you con't use native window gadgets.

I intended invoke-with-double-buffering.

The flickering is another problem. We need to find a solution for it. I think it principally depends on async repaint. A sheet can repaint itself (sending drawing commands to the server) if it wants (for example when its size changes). It will be better if it will be a backend to ask to a sheet to repaint itself (as used by CLIMatis).

Regards,
Alessandro

**Comment by ailisp** [comment]
Sorry, I wrongly suppose the menu as non mirrored. I found in clxv3 backend
all other sheets except menu and option-pane pop up a mirrored pane. I find
this method seems not be called anywhere when run the demodemo:
```lisp
(defmethod clim-clx::%realize-mirror ((port clxv3-port) (sheet basic-sheet))
  (format *trace-output* "%realize-mirror called on non mirrored sheet
~a~%" sheet) ; I add this
  (clim-clx::realize-mirror-aux port sheet
              :event-mask *event-mask*
                      :border-width 0
                      :map (sheet-enabled-p sheet)))

;; format to *trace-output* works as this method print things in REPL
(defmethod clim-clx::realize-mirror ((port clxv3-port) (sheet
mirrored-sheet-mixin))
  (format *trace-output* "realize-mirror called on mirrored sheet ~a ~%"
sheet)
  (clim-clx::%realize-mirror port sheet))
```
So can we remove this method `clim-clx::%realize-mirror ((port clxv3-port)
(sheet basic-sheet))`?
And standard-handled-event-port-mixin is great, I didn't know that manage
pointer enter/leave/grab event. Thank you.
As for double-buffering, I don't have much experience on it, I will have
some experiment first.

2017-01-08 16:03 GMT-05:00 gas2serra <notifications@github.com>:

**Comment by gas2serra** [comment]
Umm, I did not remember... I think we can remove `clim-clx::%realize-mirror ((port clxv3-port) (sheet basic-sheet))`.

Let me know if you will find other problems.

Alessandro

**Comment by ailisp** [comment]
@gas2serra 
I've tried the single-mirrored mixin but get into a strange problem, events are generally working, but displaying is not correct. Did you have similar problem when write CLXv3 backend?
[https://github.com/ailisp/mcclim-graphic-forms/blob/master/single.png](https://github.com/ailisp/mcclim-graphic-forms/blob/master/single.png)

**Comment by gas2serra** [comment]
I can not test your code because I have not  a PC with window. 
Anyway, usually the problem is related to have wrong coordinates. For example, looking at your code (in the git) it seem to me that you have forgotten to use 
```
(with-transformed-position ((sheet-native-transformation
                                (medium-sheet medium)) x y)

```    
in:

`(defmethod medium-draw-text* ((medium graphic-forms-medium) string x y
`


I know, clx and clxv3 share the same font cache. They can't be used together.

**Comment by gas2serra** [comment]
Another problem may be the clipping region, you must convert the coordinates. Try to disable it.

**Comment by ailisp** [comment]
Thank you. You are right.This solved part of display questions. I'll try to
fix others. I think single mirrored sheet can work correctly with windows
backend, remain issues are related to coordinate calculation on windows.

2017年1月11日 上午5:09，"gas2serra" <notifications@github.com>写道：

**Comment by ailisp** [comment]
@gas2serra
Unfortunately, currently I tried two approaches but neither works as for single-mirrored sheet backends on windows. This is not to say your work on single-mirrored-sheet-mixin not correct, it's excellent. But Windows is quite unscientific that for a mirrored window it only has one graphic-context (called device context or DC on windows' api). So for different medium options, it can't keep a gc object like what clx-medium did:
```lisp
(defclass clx-medium (basic-medium)
  ((gc :initform nil) ...))
```
Because if only top-level window is mirrored, there is only one gc, modify to it influence other panes that already painted. Therefore, it's hard to implement a medium-gcontext generic function.

Another approach may be draw each medium into memory pixmap-like object, then at reasonable time draw these pixmaps to the mirrored top-level sheet, and for each pixmap-like object can have it's own DC. But these pixmap-like objects are still foreign object and they don't take care of window hierarchy as child windows do, in my testing, the toplevel window's repaint take place after push-button on it, so the push-button disappear. In a word this approach use native objects but not take advantage of native objects can provide (window hierarchy).

I think due to windows' limitation (single gc), it may need extra effort to use single-mirrored-sheet-mixin, so i plan to implement full-mirrored-sheet version first.

**Comment by gas2serra** [comment]
@ailisp 
Sorry to give you a wrong advice. Let me know if "full-mirrored-sheet" is fine.
Alessandro

**Comment by ailisp** [comment]
@gas2serra 
Sorry for late response. Your suggestion is quite useful indeed. I'm not very familiar with Windows API so it will take time to verify all aspects for full-mirrored-sheet, currently it works fine. I will let you know when demo-demo work. :-)

**Comment by nsrahmad** [comment]
`find-concrete-class` no longer exists.
