### ISSUE TITLE
Can't start with freetype: System "mcclim-fontconfig" not found

### ISSUE THREAD

**Issue by stacksmith** [McCLIM/McCLIM#1281]
Following the instructions on wiki:
```
 (pushnew :mcclim-ffi-freetype cl:*features*)
 (ql:quickload :mcclim)

System "mcclim-fontconfig" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
Restarts:...
```
Just quickloading mcclim and running demos works fine.

Ubuntu 20.04, SBCL 2.2.3

**Comment by dkochmanski** [comment]
Hey, thanks for the report. what does
`(ql:system-apropos "mcclim-fontconfig")` say?

did you try clearing up your ~/.cache/common-lisp ?

are you sure that there is no stale mcclim in your local-projects (or other asdf location)? (if so, try pulling newest changes)

**Comment by stacksmith** [comment]
It was something with my system... I updated quicklisp, and things started working as expected.  Thank you and sorry to trouble.
