### ISSUE TITLE
SCROLL-EXTENT ceased to work.

### ISSUE THREAD

**Issue by maxz** [McCLIM/McCLIM#1305]
In the current Git version, `scroll-extent` does not work anymore.

Commit [`87b045ea2e64a35b999a089ab0580fa1d2b10be1`](https://github.com/McCLIM/McCLIM/commit/87b045ea2e64a35b999a089ab0580fa1d2b10be1) broke it.

I had a minimal example with multiple tabs, but then I discovered that `scroll-extent` does not work at all and it just seemed to work in some cases because you changed the behaviour of the scrollbar and therefor it appeared like one of my workarounds for the old behaviour was still working.

```
;;;; -*- Coding: utf-8; Mode: Lisp; indent-tabs-mode: nil -*-                                       

(ql:quickload :mcclim :silent t)

(defpackage #:scroll-extent-bug
  (:use #:clim-lisp)
  (:import-from #:clim
                #:define-application-frame
                #:draw-rectangle*
                #:make-application-frame
                #:run-frame-top-level
                #:scroll-extent
                #:view))

(in-package #:scroll-extent-bug)

(defparameter *pane* nil)

(define-application-frame scroll-extent-bug ()
  ()
  (:panes
   (buggy-pane :application
               :max-height 500
               :width 500
               :scroll-bars :horizontal
               :incremental-redisplay nil
               :display-function #'draw-something)))

(defun draw-something (frame pane)
  (declare (ignore frame))
  (setq *pane* pane)
  (loop for i below 50
        do (draw-rectangle* pane (* i 50) 20 (+ (* i 50) 20) 40))
  ;; Try to scroll to 200.                  
  ;; This worked before.                                                                            
  (scroll-extent pane 200 0))

(define-scroll-extent-bug-command (com-scroll-extent-to-800
                                   :menu t)
    ()
  ;; Try to scroll to 800 after selecting the command.                                              
  ;; This also worked before.                                                 
  (scroll-extent *pane* 800 0))

(run-frame-top-level (make-application-frame 'scroll-extent-bug))
```

**Comment by dkochmanski** [comment]
technically it is not a bug, however it is a frequently raised issue; you try to
scroll the window to a location that is not available at the time you scroll

in the first occurance, the pane fully fits in the viewport, because it is not
resized yet (i.e you try to scroll in the same operation you draw)

in the second occurance, you first scroll to 800 alright, but then the sheet is
redisplayed (so it is cleared - then it fits in the viewport and scrolling is
adjusted, and then you draw new content)

the first one may be addressed by calling change-space-requirements before scroll-extent

the second by incorporating incremental redisplay or display-time nil

n.b there is no chance that the command com-scroll-extent-to-800 worked before
(contrary to the comment)

**Comment by maxz** [comment]
> technically it is not a bug, however it is a frequently raised issue; you try to scroll the window to a location that is not available at the time you scroll

Ok, thanks. It seems counter-intuitive, especially since it worked before. But I see the point.

> the first one may be addressed by calling change-space-requirements before scroll-extent

`scroll-space-requirements` works in the example program, but not in my real program. So I will have to investigate this further. There is no obvious reason for this difference to me right now.

> the second by incorporating incremental redisplay or display-time nil

Incremental redisplay sadly has its own set of issues and is less performant than a full redraw in my use case.
I'm pretty sure this is a bug but I have to create a proper minimal program which displays this behaviour.

I yet have to try the `display-time` solution.

> n.b there is no chance that the command com-scroll-extent-to-800 worked before (contrary to the comment)

That is correct. I meant that it triggered a scroll to 200. Not that it actually scrolled to 800. The redraw always overwrites that part. It's an inaccurate description which crept in while trying it in the two different versions.

**Comment by maxz** [comment]
I did still not test setting `display-time` to nil, but `change-space-requirements` solves my problem good enough for now.
