### ISSUE TITLE
Specifying a pane's text-style in list format causes an error

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#1313]
According to the CLIM specification, a text style can be specified as a 3-element list or as the result of calling make-text-style. However, the former causes a no applicable method error in `text-style-equalp`.

Run the following:

```
(in-package :clim-user)

#+(or)
(defun app-text-style ()
  (make-text-style :sans-serif :roman :large)) ; OK

(defun app-text-style ()
  (list :sans-serif :roman :large)) ; causes error

(define-application-frame text-style-test ()
    ()
  (:panes
    (app-pane
      (make-pane 'application-pane
        :text-style (app-text-style)
        :display-function 'output-text)))
  (:layouts
    (default
      (scrolling (:scroll-bars :both :width 500 :height 600)
        app-pane))))

(defun output-text (frame stream &rest rest)
  (declare (ignore frame rest))
  (write-char #\a stream)
  (write-char #\b stream))

(run-frame-top-level (make-application-frame 'text-style-test))
```

Here's the error message and a partial backtrace:

```
debugger invoked on a SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread
#<THREAD "main thread" RUNNING {1001524073}>:
  There is no applicable method for the generic function
    #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::TEXT-STYLE-EQUALP (2)>
  when called with arguments
    ((:SANS-SERIF :ROMAN :LARGE) (:SANS-SERIF :ROMAN :LARGE)).

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001524073}>
0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::TEXT-STYLE-EQUALP (2)> (:SANS-SERIF :ROMAN :LARGE) (:SANS-SERIF :ROMAN :LARGE)) [fast-method]
1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::TEXT-STYLE-EQUALP (2)> (#1=(:SANS-SERIF :ROMAN :LARGE) #1#))
2: ((:METHOD ADD-STRING-OUTPUT-TO-TEXT-RECORD (CLIM-INTERNALS::STANDARD-TEXT-DISPLAYED-OUTPUT-RECORD T T T T T T T)) #<CLIM-INTERNALS::STANDARD-TEXT-DISPLAYED-OUTPUT-RECORD 0,0 ("a") {1008691A33}> "b" 0 1 (:SANS-SERIF :ROMAN :LARGE) 11 1341/64 17109/1024) [fast-method]
3: (CLIM-INTERNALS::SEOS-WRITE-STRING #<CLIM-CLX::|CLX-854-CLIM:APPLICATION-PANE| APP-PANE {1001B3ACD3}> "b" 0 1)
4: ((:METHOD STREAM-WRITE-CHAR (STANDARD-EXTENDED-OUTPUT-STREAM T)) #<CLIM-CLX::|CLX-854-CLIM:APPLICATION-PANE| APP-PANE {1001B3ACD3}> #\b) [fast-method]
5: (WRITE-CHAR #\b #<CLIM-CLX::|CLX-854-CLIM:APPLICATION-PANE| APP-PANE {1001B3ACD3}>)
6: (CLIM-INTERNALS::INVOKE-DISPLAY-FUNCTION #<TEXT-STYLE-TEST {1004D1AF23}> #<CLIM-CLX::|CLX-854-CLIM:APPLICATION-PANE| APP-PANE {1001B3ACD3}>)
```

The following fixes the issue - but perhaps there's a better way.

```
(defmethod text-style-equalp ((style1 list)
                              (style2 list))
  (equal style1 style2))
```

**Comment by john-a-carroll** [comment]
I've realised that my last suggestion isn't sufficient. `text-style-equalp` needs to work for either argument being a text style object or a style spec (a 3-element list of family, face, and size). In addition, style specs should be parsed (perhaps by `parse-text-style*`) into a canonical form before comparison.

**Comment by dkochmanski** [comment]
this is insufficient for a few reasons:
- extended text styles use hash tables to have eq between strings
- sizes are normalized (vide parse-text-style* as you have noted)

that said, I'm skeptical whether text-style-equalp should handle lists at all. also I'm surprised that the list passes thorough to match-output-record. After a bit of investigation it seems that pane is initialized just fine (initialize-instance methods calls make-text-style), but medium is initialized with a list.

I'll commit a fix shortly, thanks for the report.

**Comment by dkochmanski** [comment]
the issue stems from the fact that `permanent-sheet-output-mixin` is before `basic-pane` for the `clim-stream-pane`. The first class has initialize-instance method that engrafts the medium (among other things sets `medium-text-style` to `pane-text-style`), and only after that the second class has initialize-instance method that sets the slot `text-style` (used by `pane-text-style`) to `(make-text-style ,@text-style)`.

**Comment by dkochmanski** [comment]
on the other hand, where is it said that the user may pass a list as an initialization argument as a text style? After some consideration I'm inclined to signal an error when the pane is created with a list as a text-style `initarg`.

I'm leaving the issue open and waiting for further input.

**Comment by john-a-carroll** [comment]
Thanks for investigating. Unfortunately, I don't think this issue is clear-cut. In the CLIM 2 specification, section 29.2.1 'Pane Initialization Options' describes `:text-style` as 

> the default text style that should be used for any sort of pane that supports text output

It does not say what is allowable as a "text style", and in particular it does _not_ link to the text style protocol section 11.1, which describes the class `text-style`.
 
Elsewhere, there are at least 3 functions or macros which take a 'text-style' argument which is explicitly stated to be either a text-style object or a "style spec" (a list of the family, face, and size). These are: `with-text-style`, `invoke-with-text-style`, `draw-text` (and also presumably `draw-text*`).

> **11.1.1 Text Style Protocol and Text Style Suboptions**
> **parse-text-style** _style-spec_
> ...
> _style-spec_ may be a **text-style** object or a device font, in which case it is returned as is, or it may be a list of the family, face, and size (that is, a "style spec"), ...
> This function is for efficiency, since a number of common functions that take a style object as an argument can also take a style spec, in particular **draw-text**.
> 
> **11.2 Text Style Binding Forms**
> **with-text-style** _(medium text-style) &body body_
> **invoke-with-text-style** _medium continuation text-style_
> ...
> _text-style_ may either a text style object or a style spec (that is, a list of the a family, a face code, and a size).
> 

A further consideration is that the [Symbolics CLIM 2.0 User's Guide](http://www.bitsavers.org/pdf/symbolics/software/genera_8/Common_Lisp_Interface_Manager__CLIM__Release_2.0.pdf) (p. 1355) and the [Franz CLIM 2.2 User Guide](https://franz.com/support/documentation/current/doc/clim-ug.pdf) (p. 195) give the following example, in which a pane is created with a style spec:

```
(clim:define-application-frame puzzle
    (transaction-recording-mixin clim:standard-application-frame)
  ((puzzle :initform (make-array '(4 4))
       :accessor puzzle-puzzle))
 (:default-initargs :pathname "puzzle-log.text")
 (:panes
  (display :application
       :display-function 'draw-puzzle
       :text-style '(:fix :bold :very-large)
       :incremental-redisplay t
       :text-cursor nil
       :width :compute :height :compute
       :end-of-page-action :allow
       :end-of-line-action :allow))
 (:layouts
  (:default display)))
```

The LispWorks [Common Lisp Interface Manager User Guide Version 2.0](http://www.lispworks.com/documentation/lw80/clim/clim.htm) (section 9.3) contains a similar example. I've verified that the example works in Franz Allegro CL 10.0. However, one could choose to ignore this, since it's merely an example and it doesn't appear in the CLIM 2 Specification.

Apologies for the length of this response! I really don't feel very strongly about this issue, but it tripped up one of my users, who uses both the Allegro CLIM and the McCLIM versions of my application.

**Comment by dkochmanski** [comment]
Thanks for providing this analysis. I think that we should stipulate, that the initialization argument must be a text-style object because:

- "text style" is closer semantically to "text style object" than "text style spec", just like "package" is closer to "package object" than "package designator"

- pragmatically speaking, we'd need to do either a lot of plubming to handle text style specs also in mediums - either by defining :around methods on (setf medium-text-style) or defining (quite many(!)) methods working with text-styles to specialize on lists - in other words increased complexity for little benefit

I agree that it is not a clear cut issue, but I think that the least we can do is to update the specification in our repository to mention text-style /object/ and to signal eagerly an error if a list is used as the initialization argument (i.e stipulate the slot types for both pane and medium).

I wouldn't mind handling lists there (and that was the initial intention of the author for the pane code apparently), but looking how much code is needed for complete handling of it I don't think that its worth it.

**Comment by john-a-carroll** [comment]
I might be overlooking something here, but wouldn't it work to just call parse-text-style on any :text-style option when creating a pane? Then if the :text-style were a style spec, this would immediately be converted to a text-style object.

If this has undesirable consequences then I agree with your suggestion of signalling an error eagerly.

**Comment by dkochmanski** [comment]
while I'm aware that the code could be structured differently, I'm not certain how - without a potency to introduce a regressions; this is what's currently going on (with various simplifications):

```
initialize-instance :after basic-pane
  (when (consp text-style)
    (setf (pane-text-style pane) (make-text-style ,@text-style)))
```

```
initialize-instance :after sheet-with-permanent-medium-mixin
  (engraft-medium)
```

```
engraft-medium :after
  (setf (medium-text-style medium) (pane-text-style pane))
```

`clim-stream-pane` inherits from `basic-pane` that inherits from `permanent-medium-sheet-output-mixin`, so the initialize-instance method for `permanent-medium-sheet-output-mixin` comes before the method for `basic-pane`, so we engraft the medium with a list.

We could add also parse-text-style (or make-text-style) to engraft-medium, but the fact remains, that calling pane-text-style from initialize-instance methods called before the basic-pane specific one will receive the list, so the potency of "gotcha" remains for unsuspecting future developers. Moreover, if we want to be **consistent**, we should also allow passing a list as a text-style the the medium constructor for both text-style and default-text-style, so we need to cover both initialize-instance of the basic-medium and the setf methods. In the best case we need to add three methods (`initialize-instance` handling initargs, `(setf medium-text-style)` and `(setf medium-default-text-style)`).

The problem with text-style that is not yet fully initialized also applies then to a medium. Suppose that a backend defines a class `(defclass my-medium (text-renderer basic-medium) ())`, and the text-renderer class maps eagerly the text style to some resource on the display server (i.e a font) - then the text-renderer /also/ needs to call parse-text-style in its initialize-instance method if they want a text-style.

On the other hand if we declare the type of text-style slot as a class text-style, then some compilers will signal an error eagerly (ccl on default settings, sbcl on high safety settings). Doing so spares us the initialize-instance method for basic-pane.

All in all these changes are not big, but McCLIM is massive as it is, so we should rather strive to reduce cognitive effort to make it easier to understand the codebase (imo).

**Comment by john-a-carroll** [comment]
Thank you for the explanation. I agree completely that it's important to control the complexity of the codebase, otherwise it will become more and more difficult to diagnose issues, and - in the worst case - become unmaintainable. Please do whatever you think best.

**Comment by dkochmanski** [comment]
thanks; I've commited a change that
a) checks the type for basic-pane (to signal an error for code passing a list)
b) adds type declarations to slots in basic-pane and basic-medium
c) explicitly says for the :text-style option "text style object" in the spec
