### ISSUE TITLE
Input is invisible in Calculator Demo

### ISSUE THREAD

**Issue by Homo-carbonis** [McCLIM/McCLIM#1334]
In xwayland values in the screen area of the calculator demo only show up for a fraction of a second then disappears.
![20230308_15h57m08s_grim](https://user-images.githubusercontent.com/47869153/223763655-76969215-cd7b-4b86-bb8b-20dd0f0ec3fc.png)

Also if the input reaches the edge of the screen it fails with "Invalid index 1 for (SIMPLE-VECTOR 1) , should be a non-negative integer below 1."

**Comment by dkochmanski** [comment]
please try the current master branch. the new input editor addresses this regression.

**Comment by Homo-carbonis** [comment]
Yes, it's fixed in master. I was still in the quicklisp version. Sorry about that.

**Comment by dkochmanski** [comment]
No worries, the regression should not land in quicklisp in the first place. Thanks for the report.
