### ISSUE TITLE
Drawing zero-length strings crashes the X11 server

### ISSUE THREAD

**Issue by robert-strandh** [McCLIM/McCLIM#151]
Using DRAW-TEXT* to draw an empty string crashes my X11 server.

I *think* the CLX function that is called as a result of DRAW-TEXT* is
the function FONT-DRAW-GLYPHS, but I am not sure of that, and I don't
particularly want to crash my X server in order to find out.

**Comment by gas2serra** [comment]
I try the following code in the listener without any error:

```
(MAP-OVER-FRAMES
 (LAMBDA (X)
   (WHEN (STRING= (FRAME-NAME X) "LISTENER")
     (DRAW-TEXT* (FIND-PANE-NAMED X 'CLIM-LISTENER::INTERACTOR) "" 100 100))))
```

I'm using the master branches of McClim and CLX.
Can you give me more info?

**Comment by robert-strandh** [comment]
I have tried to reproduce this problem in an independent application,
but failed.  I think we should leave this for now until I have a
better idea of the context for the crash.

**Comment by gas2serra** [comment]
In the last few days my X server crashed when I was using mcclim. I think it is not directly related to mcclim. May be it arose when I update another cl library or the xorg package.

**Comment by dkochmanski** [comment]
I'm closing this for now until we have a reproducible case.

**Comment by dkochmanski** [comment]
Related to https://github.com/robert-strandh/McCLIM/issues/145 (reopening only one) and https://github.com/slyrus/clim-crasher/ .

Apparently new Xorg version have this sanitized.That said we should fix it in CLX to skip over empty strings.

**Comment by nsrahmad** [comment]
Fixed in CLX.
