### ISSUE TITLE
Implement methods on compose-in for in-compositum.

### ISSUE THREAD

**Issue by robert-strandh** [McCLIM/McCLIM#162]
In the file Core/clim-basic/design.lisp, two methods on the generic
function COMPOSE-IN look like this:

````
#+nyi
(defmethod compose-in ((ink opacity) (mask in-compositum))
  (declare (ignorable ink mask))
  )

#+nyi
(defmethod compose-in ((ink color) (mask in-compositum))
  (declare (ignorable ink mask))
  )
````

where `nyi' stands for not-yet-implemented.  The task consists of
implementing these two methods.

**Comment by nsrahmad** [comment]
These methods are implemented now.
