### ISSUE TITLE
Stream panes doesn't support :word-wrap end-of-line-action

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#249]
Currently there is only character-wrapping. There should be some way of doing word-wrapping as well.

Here is some sample code that implements this. It has some problems:

  - If the wrapping happens at a space, the next line will start with a space. This case should be handled by removing the space.
  - The code uses SBCL-specific features in order to properly break the string.
  - Because of https://github.com/robert-strandh/McCLIM/issues/254 it's not possible to properly determine the width of pane, so this code just arbitrarily subtracts 18 from the width.

```
(defun present-text-with-wordwrap (stream text)
  (let ((words (sb-unicode:words text)))
    (loop
      with pane-width = (- (clim:bounding-rectangle-width stream) 18) ;; add some extra space to accommodate the scrollbar
      for word in words
      unless (equal word #.(princ-to-string #\Newline))
      do (let ((x (clim:cursor-position (clim:stream-text-cursor stream))))
           (when (> (+ x (clim:stream-string-width stream word)) pane-width)
             (format stream "~%"))
           (format stream "~a" word)))))

(defun present-multiline-with-wordwrap (text stream)
  (loop
    with start = nil
    for i from 0 below (length text)
    if (eql (aref text i) #\Newline)
      do (progn
           (when (and start (> i start))
             (present-text-with-wordwrap stream (subseq text start i))
             (setq start nil))
           (format stream "nl~%"))
    else
      do (progn
           (when (null start)
             (setq start i)))
    finally (when start
              (present-text-with-wordwrap stream (subseq text start)))))
```

**Comment by gas2serra** [comment]
'application pane' is based on 'clim-stream-pane' and has a really simple wrapping behavior. If you need something with a better text layout you must use a gadget (such as text-editor). 
The best way to use a stream-pane is to allow both vertically and horizontally scrolling.

**Comment by lokedhs** [comment]
I don't agree. The most common use for application panes is to output text, and having proper word wrap is a natural assumption. My code above kind of achieves this, and I think it's very reasonable to assume this behaviour to be the default.

With regards to TEXT-EDITOR, that is not a solution since it has even worse wrapping behaviour than stream panes. It doesn't wrap at all. See https://github.com/robert-strandh/McCLIM/issues/247

**Comment by dkochmanski** [comment]
IMHO we should fix text-editor. Changing defaults for the application-pane would be violation of the specification, so I oppose to making that default. On the other hand adding new possible value for end-of-line-action, say `wrap-word` and documenting it is a good idea for extension. See:
http://bauhh.dyndns.org:8000/clim-spec/edit/apropos?q=end-of-line-action

**Comment by lokedhs** [comment]
That would make sense. My main concern is that there is no standardised way to get word wrapping at the moment.

**Comment by dkochmanski** [comment]
I have changed a name to reflect the issue current state. That said, I'm not sure how hard would it be to implement word wrapping, given that we may write to the stream char-by-char (we don't know at real time when to break the line, because there might be upcoming space ahead).

**Comment by dkochmanski** [comment]
fixed in develop (option is called `:wrap*`).
