### ISSUE TITLE
When resizing the window, the content of application panes should be reflowed

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#250]
To reproduce, simply output some text so the the content is wrapped at the right-hand edge. Then resize the window. One would expect the content to reflow at this point so that the text occupies the full width of the window. Instead, nothing happens until you do a full repaint.

**Comment by dkochmanski** [comment]
This isn't correct. Display is triggered depending on `:display-time` value for the pane: http://bauhh.dyndns.org:8000/clim-spec/edit/apropos?q=display-time

Flow of the pane is determined at the display time. One way to fix that would be handling the resize-event and calling redisplay-pane. See https://gist.github.com/knusbaum/00f14f0ad04234eec4669a29c309d81c .

You could define `:after` method for method:

```
 handle-event ((sheet standard-mirrored-sheet-mixin)
			 (event window-configuration-event))
```

**Comment by dkochmanski** [comment]
superseded by #970.
