### ISSUE TITLE
[$400] Fix Beagle backend.

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#27]
Beagle backend loads fine, but can't render anything due to:

```
There is no applicable method for the generic function:
#<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::PORT-LOOKUP-MIRROR #x3020010F6E7F>
when called with arguments:
(NIL #<TOP-LEVEL-SHEET-PANE CLIM-INTERNALS::TOP-LEVEL-SHEET #x3020039DCBCD>)
```

(tested by hhdave from #clim irc channel)

**Comment by dkochmanski** [comment]
Beagle backend should work reasonably well on CCL and OSX platform (should load, start demos and work fine with most of them).

**Comment by dkochmanski** [comment]
Some backend documentation is provided in the Manual (you may build it in Documentation/Manual/Texinfo) - in chapter developer manual.

**Comment by phoe** [comment]
I have loaded CCL 1.11 on macOS 10.11.6 and attempted to load beagle from Quicklisp's McCLIM `20170725-git`.

Beagle attempts to load a symbol called `CLIMI:%SHEET-MIRROR-TRANSFORMATION` and fails because there is no such symbol.

**Comment by dkochmanski** [comment]
beagle is going to be removed before next release. if someone implements it we'll merge that back.
