### ISSUE TITLE
clx-fb: image viewer demo: can't show png image

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#286]
Error when displaying image. On "normal" CLX backend image is shown correctly. Image in question:

![cab_view](https://user-images.githubusercontent.com/6871201/27854328-b4991686-6166-11e7-9eaf-79727a8ae5d0.png)

Steps to reproduce:
1. run image viewer demo
2. select attached image to be displayed

Observed:
Image draw error (doesn't invoke debugger, what is good, just text on image area)

Expected:
Image is drawn.

@gas2serra

**Comment by gas2serra** [comment]
Umm. I'll test it.

**Comment by dkochmanski** [comment]
fixed in master branch
