### ISSUE TITLE
[launchpad #548662]  define-presentation-type and :inherit-from

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#371]
https://bugs.launchpad.net/mcclim/+bug/548662

From http://bauhh.dyndns.org:8000/clim-spec/23-3.html#_4663
"If inherit-from is unsupplied, it defaults as follows: If name is or names a CLOS class, then the type inherits from the presentation type corresponding to the direct superclasses of that CLOS class (using and to specify multiple inheritance). Otherwise, the type named by name inherits from standard-object."
McClim has troubles with that, attached test files shows an error on the command "Test".
"Presentation type specifier NIL does not match the name CLIM-USER::FOO"

**Comment by dkochmanski** [comment]
And the "attached" test

```common-lisp
(in-package :clim-user)

(define-application-frame test ()
  ()
  (:panes
   (interactor :interactor))
  (:layouts
   (default
       interactor)))

(defclass foo () ())
(defclass bar (foo) ())

(define-presentation-type foo ())
(define-presentation-type bar ()
  :inherit-from 'foo)

(define-presentation-method present (object (type foo) stream view &key)
  (declare (ignore view))
  (print "HELLO" stream))

(define-test-command (com-test :name t :menu t) ()
  (present (make-instance 'bar)))

(defun test ()
  (run-frame-top-level (make-application-frame 'test)))
```

**Comment by nsrahmad** [comment]
No longer valid. Test case runs just fine.
