### ISSUE TITLE
Writing the same text multiplt times causes visual artifacts

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#374]
The problem is most commonly seen when a `HANDLE-REPAINT` method draws some text. If the same text is drawn on top of the old (identical) text, the text will gradually become bolder.

What seems to happen is that the repaint method does not clear its background before repainting, and the antialiasing applied when drawing text will make the next text blend together with the old text.

An obvious workaround is to manually clear the background before painting the text, and it's not clear if there are any better solutions for this.

**Comment by abridgewater** [comment]
An analysis of the CLIM II spec shows that calling QUEUE-REPAINT or REPAINT-SHEET on a sheet that does not clear to background (or does not have its region completely covered by child sheets that do so) would yield this result for anything involving a non-integral alpha channel, or anything where the alpha channel changes between repaints.

It's actually not _obvious_ from the spec, being a derived effect of the repaint protocol combined with the available set of sheet region operations, and is rather nonintuitive for those used to WinAPI and X11 (for which child windows are removed from parent window repaint regions), but it is what it is.

**Comment by nsrahmad** [comment]
Not really a bug.
