### ISSUE TITLE
Listener context menu mouse-over highlighting is weird

### ISSUE THREAD

**Issue by abridgewater** [McCLIM/McCLIM#376]
To reproduce:

1. Start a fresh CLIM-LISTENER.
2. Enter and evaluate some expression, such as (+ 3 4).
3. Right-click the entered expression to open the context menu.
4. Mouse-over the menu items, noting how they are highlighted as you do so.

The "expression as literal" menu item seems to be highlighted reasonably, but the "Describe" item is weird.

**Comment by abridgewater** [comment]
Still occurs as of 2018-02-08, but after some discussion on IRC it appears that "weird" should be quantified.  First, it is rendered as comma-separated atoms, rather than as a lisp list.  Second, it involves _seven_ separate boxes when highlighted by mouseover.  Two screenshots attached (somehow not including the mouse cursor).

![screenshot at 2018-02-07 23 58 41](https://user-images.githubusercontent.com/469380/35956492-3322fbf4-0c64-11e8-8c6e-1c2acbafc93b.png)
![screenshot at 2018-02-07 23 59 08](https://user-images.githubusercontent.com/469380/35956493-3335e39a-0c64-11e8-8e80-de3e27d654a9.png)

**Comment by wmannis** [comment]
I'd do a pull request for this, but it might be too blunt (the McCLIM codebase is still often a mystery to me).  But in the function `draw-standard-menu` in Core/clim-core/menu-choose.lisp, under the `:item` ecase changing this:

```common-lisp
                           (with-text-style
                               (stream (menu-item-option
                                        item :style
                                        '(:sans-serif nil nil)))
                             (with-output-as-presentation
                                 (stream
                                  item
                                  `((,name ,@params)
                                    :description ,(getf (menu-item-options item) :documentation)
                                    ,@options))
                               (funcall item-printer item stream)))))))
```
to this:
```common-lisp
                           (with-text-style
                               (stream (menu-item-option
                                        item :style
                                        '(:sans-serif nil nil)))
                             (with-output-as-presentation
                                 (stream
                                  item
                                  `((,name ,@params)
                                    :description ,(getf (menu-item-options item) :documentation)
                                    ,@options)    ;;; <----
                                  :single-box t)  ;;; <----
                               (funcall item-printer item stream)))))))
```
seems to fix the issue without introducing any new insanities I could find (but my search may not have been sufficiently comprehensive).

**Comment by dkochmanski** [comment]
Making pull requests is an encouraged metod of proposing fixes (easier to test and review), it won't be too blunt :-) looks good to me, please make PR and after some extra testing I'll probably merge it. Nice catch.

**Comment by wmannis** [comment]
I've just made a pull request for the boxing issue.

As for the commas...

<img width="466" alt="textual-menu-view" src="https://user-images.githubusercontent.com/11655511/36923964-8d8fc196-1e32-11e8-81e1-161000f5fe95.png">

The textual view of several sequence types is massaged to look nice for normal text, rather than the list or vector notation programmers expect. If you specialize the `present` presentation method on `textual-menu-view` you can format the menu item to show a list `(as a list)`. It makes the most sense to put that into the Listener app itself, but it could I suppose go into `clim-core/presentation-defs.lisp`.  Where would you like the updates for that?

**Comment by dkochmanski** [comment]
I think that comma-less presentation by default in the listener is fine, because it is enhanced repl (hence it should show nicely what would programmer expect).  So I would skip this endavour.

**Comment by wmannis** [comment]
> Yes, it would be best done in the Listener (not in the core).

Shall I submit another pull request for that, then?

**Comment by dkochmanski** [comment]
Yes.

Dnia 10 marca 2018 21:19:56 CET, wmannis <notifications@github.com> napisał(a):
>> Yes, it would be best done in the Listener (not in the core).
>
>Shall I submit another pull request for that, then?

-- Sent from Android.

**Comment by dkochmanski** [comment]
fixed in master.
