### ISSUE TITLE
ACCEPTING-VALUES dialog command keystrokes are undocumented and non-discoverable

### ISSUE THREAD

**Issue by abridgewater** [McCLIM/McCLIM#386]
In an ACCEPTING-VALUES dialog, either within a stream pane or as a separate window, none of the command keystrokes for navigating between input fields (`M-n` and `M-p`), aborting (cancelling?) the dialog (`C-z`, although `C-c` works for other reasons), or accepting the dialog results (`C-]`, for some reason) are easily discovered. Nor does there appear to be any mention of these keyboard shortcuts in the documentation.

**Comment by abridgewater** [comment]
I have since found the wiki page https://github.com/robert-strandh/McCLIM/wiki/Gesture which includes a bare description of the relevant keys in the section "textual-dialog". This is a very bare description, not what I would want to see as a user, and there is no reference to the wiki anywhere in the git repository (checked via "git grep -i wiki"), which leaves these still as effectively undocumented.

**Comment by duuqnd** [comment]
Pull request #907 adds `C-[`, but more importantly, `M-RET` as a more intuitive keybinding for confirming in accepting-values.

**Comment by nsrahmad** [comment]
Fixed with #907
