### ISSUE TITLE
Pressing Alt while in the listener scrolls the interactor to the bottom

### ISSUE THREAD

**Issue by abridgewater** [McCLIM/McCLIM#393]
Easy to reproduce, and irritating if you've scrolled up to refer to something and need to flip back and forth between the Listener and another application for whatever reason, such as entering an issue report into github.

**Comment by dkochmanski** [comment]
it is noteworthy, that it is not just any alt. On my keyboard, it is right alt bound to `iso-level3-shift`. Pressing left alt doesn't have any effect on scrolling.

**Comment by nsrahmad** [comment]
No longer valid.
