### ISSUE TITLE
[$200] Text rotation is not supported

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#400]
See drawing test "07) Text Rotation". None of the text is rotated. It's not clear that this is required to work by the spec, but, IMO, this is an important feature and we should fix it.

**Comment by abridgewater** [comment]
CLIM II, 12.5.1, DRAW-TEXT and DRAW-TEXT*:

> It is permissible for CLIM implementations to ignore _transform-glyphs_ if it is too expensive to implement.

That said, I'd certainly account it as a nice-to-have, and if you're using a truetype rasterizer anyway then it shouldn't be all that difficult, should it?

**Comment by dkochmanski** [comment]
For this bounty to be accepted rotation should work on both clx-fb and clx backend

**Comment by lokedhs** [comment]
The freetype renderer has implemented support for text transforms. As part of this work, the draw-text-output-record was reworked to store the transformation that should be used. This means that the call to `MEDIUM-DRAW-TEXT` now accepts a `TRANSFORMATION` parameter that should be used to render the individual characters.

**Comment by dkochmanski** [comment]
this change has been reverted (in a branch which is not merged yet) in favour of a graphics-state mixin for recording medium transformation. I'm going to implement transformations in truetype before merging this branch.

**Comment by dkochmanski** [comment]
text rotation *is* supported in ttf renderer (branch merged to master already). major refactor of font infrastructure took place in a meantime.
