### ISSUE TITLE
command gesture accelerator :delete doesn't work.

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#427]
The gesture accelerator :delete  doesn't work (for example in address-book demo the com-delete-address command).   All the gesture defined as :shift and a pointer-button-press don't work

**Comment by dkochmanski** [comment]
bug confirmed, thanks for the report.

**Comment by admich** [comment]
Actually the gesture works (for example in address-book demo if you click with shift + middle button the address is deleted) but the presentation is not highlighted when you press the shift key.

**Comment by scymtym** [comment]
@admich do the changes in #868 help?

**Comment by admich** [comment]
Yes #868 solves the problem. The problem was in `dispatch-event :around` method for `((pane text-selection-mixin) (event pointer-motion-event))`. The version in #868 is ok.

**Comment by admich** [comment]
#868 was merged and now :delete gesture works so this issue can be closed
