### ISSUE TITLE
(BUG) Help -> right click-> cancel ==> the interactor vanishes

### ISSUE THREAD

**Issue by bamboospirit** [McCLIM/McCLIM#438]
Using SBCL 1.4.1, mcclim-20180131 , linux 32bit 
```lisp
; /tmp/t.lisp
(ql:quickload :mcclim)

(defpackage #:app.gui
  (:use #:clim #:clim-lisp))

(in-package #:app.gui)

(define-application-frame superapp ()
 ()
 (:panes (int :interactor :height 200 :width 600))
 (:layouts (default (vertically () int))))

(defun app-main ()
 (run-frame-top-level (make-application-frame 'superapp)))

(app-main)
```

1. (load "/tmp/t")
2. type Help in the interactor
3. press Enter
4. right click on the inputbox (it's filled with "Keyboard" by default)
5. left click on Cancel

Everything in the interactor vanishes, the window becomes blank. 
The prompt actually jumps somewhere above the window, outside the visible range - if you press a few ctrl-C the Interactor's prompt comes down a bit and becomes visible again.

**Comment by dkochmanski** [comment]
This is fixed after recent border changes.
