### ISSUE TITLE
Misc Tests / List Pane Dialog is broken

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#448]
Running the "Misc Tests" test "List Pane Dialog" yields the following error:

There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::SELECT-QUERY (2)>
when called with arguments
  (#<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {103C970A93}>
   #<CLIM-INTERNALS::QUERY {1040BE5563}>
   #<CLIM-INTERNALS::ACCEPTING-VALUES-RECORD X 945/2:1135/2 Y 511/32:4981/32  CLIM-DEMO::ABBREV {1040F5BA83}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [ABORT] Return to application command loop
 2: [ABORT] Return to application command loop
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {102F907F93}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::SELECT-QUERY (2)> #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {103C970A93}> #<CLIM-INTERNALS::QUERY {1040BE5563}> #<CLIM-I..
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::SELECT-QUERY (2)> (#<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {103C970A93}> #<CLIM-INTERNALS::QUERY {1040BE5563}> #<CLIM-I..
  2: (CLIM-INTERNALS::COM-SELECT-QUERY CLIM-DEMO::ABBREV)
  3: ((FLET "FORM-FUN-43" :IN CLIM-INTERNALS::INVOKE-ACCEPTING-VALUES))
  4: ((FLET "FORM-FUN-31" :IN CLIM-INTERNALS::INVOKE-ACCEPTING-VALUES))
  5: (CLIM-INTERNALS::INVOKE-ACCEPTING-VALUES #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::OUTPUT {103164A853}> #<CLOSURE (FLET "ACCEPTING-VALUES-CONTINUATION0" :IN "/home/sly/projects/McCLIM/Examples..
  6: ((LAMBDA (STREAM) :IN "/home/sly/projects/McCLIM/Examples/misc-tests.lisp") #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::OUTPUT {103164A853}>)
  7: ((LAMBDA (CLIM:PANE CLIM-DEMO::ITEM) :IN CLIM:GENERATE-PANES) #<unused argument> #S(CLIM-DEMO::MISC-TEST :NAME "List Pane Dialog" :DESCRIPTION "Tests a list pane gadget in an accepting-values dialog."..
  8: (CLIM-INTERNALS::INVOKE-CALLBACK #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<FUNCTION (LAMBDA (CLIM:PANE CLIM-DEMO::ITEM) :IN CLIM:GENERATE-PANES) {2368860B}> #S(CLIM-D..
  9: ((:METHOD CLIM:VALUE-CHANGED-CALLBACK (CLIM:VALUE-GADGET T T T)) #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<unused argument> #<unused argument> #S(CLIM-DEMO::MISC-TEST..
 10: ((SB-PCL::EMF CLIM:VALUE-CHANGED-CALLBACK) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<CLIM-DEMO::MISC-TESTS {10312273D3}> #:GADGE..
 11: ((:METHOD (SETF CLIM:GADGET-VALUE) :AROUND (T CLIM:VALUE-GADGET)) #S(CLIM-DEMO::MISC-TEST :NAME "List Pane Dialog" :DESCRIPTION "Tests a list pane gadget in an accepting-values dialog." :DRAWER #<FUNC..
 12: (CLIM-INTERNALS::GENERIC-LIST-PANE-SELECT-ITEM #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #S(CLIM-DEMO::MISC-TEST :NAME "List Pane Dialog" :DESCRIPTION "Tests a list pan..
 13: (CLIM-INTERNALS::GENERIC-LIST-PANE-HANDLE-CLICK #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> 58 120 0)
 14: (CLIM-INTERNALS::GENERIC-LIST-PANE-HANDLE-CLICK-FROM-EVENT #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<CLIM:POINTER-BUTTON-PRESS-EVENT {103C6EDF53}>)
 15: ((:METHOD CLIM:HANDLE-EVENT (CLIM:GENERIC-LIST-PANE CLIM:POINTER-BUTTON-PRESS-EVENT)) #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<CLIM:POINTER-BUTTON-PRESS-EVENT {103C6..
 16: ((FLET CALL-NEXT-METHOD :IN "/home/sly/projects/McCLIM/Core/clim-core/gadgets.lisp"))
 17: ((:METHOD CLIM:HANDLE-EVENT :AROUND (CLIM:BASIC-GADGET CLIM:DEVICE-EVENT)) #<CLIM-CLX::CLX-GENERIC-LIST-PANE-DUMMY CLIM-DEMO::SELECTOR {1031D575B3}> #<CLIM:POINTER-BUTTON-PRESS-EVENT {103C6EDF53}>) [f..
 18: (CLIM-INTERNALS::HANDLE-NON-STREAM-EVENT #<CLIM-INTERNALS::PORT-EVENT-QUEUE {1027CB9A13}>)
 19: ((:METHOD CLIM:STREAM-INPUT-WAIT (CLIM:STANDARD-EXTENDED-INPUT-STREAM)) #<CLIM-CLX::CLX-APPLICATION-PANE-DUMMY CLIM-DEMO::OUTPUT {103164A853}> :TIMEOUT NIL :INPUT-WAIT-TEST #<FUNCTION CLIM-INTERNALS::..

**Comment by nsrahmad** [comment]
except you are off by one!
The `List Pane Dialog` test —next to `Line Widths`— is broken.

**Comment by nsrahmad** [comment]
fixed with #631
