### ISSUE TITLE
Output records are not redrawn properly

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#476]
When adding an output record to a stream, those records are not redrawn properly under certain circumstances.

To reproduce using the test program below, start by running `(SIMPLE-TEXT:OPEN-FOO-FRAME)`:

![bug1](https://user-images.githubusercontent.com/1028755/39284191-add820a0-4944-11e8-8886-94cc346cb740.png)

The green rectangle is drawn normally, while the blue one is drawn by recording a rectangle to an output record and then adding this output record to the stream.

Next, press RETURN in the command pane:

![bug2](https://user-images.githubusercontent.com/1028755/39284237-e6fca202-4944-11e8-8324-760d72bc55b8.png)

This causes the blue rectangle to disappear.

Next, resize the window to make it smaller than the rectangle:

![bug4](https://user-images.githubusercontent.com/1028755/39284317-34db4514-4945-11e8-9c49-ebdac3842315.png)

Finally, resize the window again to reveal the blue rectangle:

![bug5](https://user-images.githubusercontent.com/1028755/39284331-45e3e49c-4945-11e8-9cea-1998d7ccbd0a.png)

**Comment by lokedhs** [comment]
Here is the test code:

(defpackage :simple-text
  (:use :cl)
  (:export #:open-foo-frame))

(in-package :simple-text)

(declaim (optimize (speed 0) (safety 3) (debug 3)))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (unless (find-package "CLIM")
    (sb-ext:restrict-compiler-policy 'safety 3)
    (sb-ext:restrict-compiler-policy 'debug 3)
    (ql:quickload "mcclim"))
  (unless (find-package "LOG4CL")
    (ql:quickload "log4cl")))

(defun draw-test-rectangle (stream x y colour)
  (clim:draw-rectangle* stream x y (+ x 100) (+ y 50) :ink colour :filled nil))

(defun display-text-content (frame stream)
  (declare (ignore frame)) 
  (draw-test-rectangle stream 10 10 clim:+green+)
  (let ((rec (clim:with-output-to-output-record (stream)
               (draw-test-rectangle stream 50 50 clim:+blue+))))
    (clim:stream-add-output-record stream rec)))

(clim:define-application-frame foo-frame ()
  ()
  (:panes (text-content :application
                        :display-function 'display-text-content)
          (interaction-pane :interactor))
  (:layouts (default (clim:vertically ()
                       text-content
                       interaction-pane))))

(defun open-foo-frame ()
  (let ((frame (clim:make-application-frame 'foo-frame)))
    (clim:run-frame-top-level frame)))

**Comment by nsrahmad** [comment]
Fixed, not sure exactly when.
