### ISSUE TITLE
Creating pane with different class of output history requires instance rather than class

### ISSUE THREAD

**Issue by robert-strandh** [McCLIM/McCLIM#477]
According to the specification, this program ought to work:

<pre>
(in-package :common-lisp-user)

(defpackage :my-first-app
  (:use :clim :clim-lisp)
  (:export run-my-first-app))

(in-package :my-first-app)

(define-application-frame my-first-clim-app ()
  ()
  (:panes
   (my-interactor :interactor
                  :output-record 'standard-sequence-output-history
		  :height 400
		  :width 600))
  (:layouts
    (my-default my-interactor)))

(defun run-my-first-app ()
  (run-frame-top-level (make-application-frame 'my-first-clim-app))
</pre>

But I have to write this instead to get the desired effect:

<pre>
(in-package :common-lisp-user)

(defpackage :my-first-app
  (:use :clim :clim-lisp)
  (:export run-my-first-app))

(in-package :my-first-app)

(define-application-frame my-first-clim-app ()
  ()
  (:panes
   (my-interactor :interactor
                  :output-record
                  (make-instance 'standard-sequence-output-history)
		  :height 400
		  :width 600))
  (:layouts
    (my-default my-interactor)))

(defun run-my-first-app ()
  (run-frame-top-level (make-application-frame 'my-first-clim-app)))
</pre>

**Comment by nsrahmad** [comment]
McCLIM here follows the Franz guide (if you see the documentation of `stream-output-history` in Franz user guide, you will see an example).
[Relevant commit](https://github.com/antifuchs/mcclim/commit/ade86a395727e02c737a833dd3d2471839dbefd7) by Timothy Moore.
