### ISSUE TITLE
Starting the inspector from a command results in output in interactor pane.

### ISSUE THREAD

**Issue by robert-strandh** [McCLIM/McCLIM#478]
In this program:

<pre>
(in-package :common-lisp-user)

(defpackage :my-first-app
  (:use :clim :clim-lisp)
  (:export run-my-first-app))

(in-package :my-first-app)

(define-application-frame my-first-clim-app ()
  ()
  (:panes
   (my-interactor :interactor
		  :height 400
		  :width 600))
  (:layouts
    (my-default my-interactor)))

(define-my-first-clim-app-command (com-inspect :name t) ()
  (clouseau:inspector *application-frame*))

(defun run-my-first-app ()
  (run-frame-top-level (make-application-frame 'my-first-clim-app)))
</pre>

when the command inspect is invoked, there is visible output in the interactor pane.  Mostly, several occurrences of NIL.

**Comment by nsrahmad** [comment]
Fixed with 939e1b2232f0d0f927598bdd3ff6d13b2de446c6
