### ISSUE TITLE
How should transformation on text be implemented?

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#480]
The current implementation of text transformations works, sometimes. However, when more than one transformation is applied, things get wonky real quick.

To run the test program, the proposed `freetype2` branch must be used: https://github.com/lokedhs/McCLIM/tree/freetype2

The test program below displays the following content:

![screenshot from 2018-05-07 21-20-14](https://user-images.githubusercontent.com/1028755/39703949-79977b28-523c-11e8-90cf-9aed36a4c016.png)

Note that the transformations used in the example code works fine if they are drawn directly, without the use of a presentation method.

The way the `freetype2` implements text transformations is by adding a new keyword parameter `:TRANSFORMATION` to `MEDIUM-DRAW-TEXT*`. Before this change, no text transformations were possible and the only thing that could be transformed was the X and Y coordinates of the starting point. After this change, `MEDIUM-DRAW-TEXT` receives untransformed coordinates as well as a transformation that should be applied.

This change was not enough, as it was also necessary to store the transformation in the output record for `DRAW-TEXT*`. Here is the relevant change: https://github.com/lokedhs/McCLIM/commit/ce89b1d189c7b92567fe25bdbc671031cff94c09#diff-30e9ff26c0505c1f647b70862d9d4af1L898

I believe that one mistake I made when implementing this was to read the active transformation from the medium when creating the output record. I don't actually think that this is the correct thing to do, but I'm not sure what should be done instead. Here is the change I made to read the transformation: https://github.com/lokedhs/McCLIM/commit/ce89b1d189c7b92567fe25bdbc671031cff94c09#diff-30e9ff26c0505c1f647b70862d9d4af1L536

Perhaps the active transformation when an output record is replayed should be merged with the transformation that was recorded in the output record itself?

**Comment by nsrahmad** [comment]
It's already implemented now.
