### ISSUE TITLE
unhandled memory fault in scigraph with mcclim-freetype-ffi

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#489]
Using the newly merged mcclim-freetype-ffi stuff (yeah for the merge!), I get the following error when running my scigraph-demo::make-indometh-graph-frame:

  0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X7F190E801680))
  1: ("foreign function: call_into_lisp")
  2: ("foreign function: funcall2")
  3: ("foreign function: handle_trap")
  4: ("foreign function: #x41B140")
  5: (CLIM-FREETYPE::MAKE-GLYPH-LIST #<CLIM-FREETYPE::FREETYPE-FONT FACE #<CLIM-FREETYPE::FREETYPE-FONT-FACE DejaVu Sans, Book> SIZE 12> "O" :LTR)
  6: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CLIM-CLX::FONT-TEXT-EXTENTS))
  7: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
  8: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CLIM-CLX::FONT-TEXT-EXTENTS) {7F190CA74AFB}> #<SB-THREAD:MUTEX "Anonymous recursive lock" owner: #<SB-THRE..
  9: ((:METHOD CLIM-CLX::FONT-TEXT-EXTENTS (CLIM-FREETYPE::FREETYPE-FONT T)) #<CLIM-FREETYPE::FREETYPE-FONT FACE #<CLIM-FREETYPE::FREETYPE-FONT-FACE DejaVu Sans, Book> SIZE 12> "O" :START 0 :END 1 :TRANSLA..
 10: ((:METHOD TEXT-SIZE (CLIM-CLX::CLX-MEDIUM T)) #<unavailable argument> #<unavailable argument> :TEXT-STYLE #<unavailable argument> :START #<unavailable argument> :END #<unavailable argument>) [fast-met..
 11: ((:METHOD STREAM-TEXT-MARGIN (STANDARD-EXTENDED-OUTPUT-STREAM)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>) [fast-method]
 12: (CLIM-INTERNALS::SEOS-WRITE-STRING #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> "L" 0 1)
 13: ((:METHOD STREAM-WRITE-STRING (STANDARD-EXTENDED-OUTPUT-STREAM T)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> "L" 0 NIL) [fast-method]
 14: (SB-IMPL::%WRITE-STRING "L" #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> 0 NIL)
 15: ((LABELS SB-IMPL::HANDLE-IT :IN SB-KERNEL:OUTPUT-OBJECT) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>)
 16: (PRINC "L" #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>)
 17: ("~A: " #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> "L")
 18: (FORMAT #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<FUNCTION "~A: " {2352D93B}> "L")
 19: (FORMAT #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<FUNCTION "~A: " {2352D93B}> "L") [more]
 20: ((:METHOD CLIM-INTERNALS::FRAME-PRINT-POINTER-DOCUMENTATION (STANDARD-APPLICATION-FRAME T T T T)) #<unused argument> (((CLIM:COMMAND :COMMAND-TABLE #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {10153C9D03}>)..
 21: ((FLET "UPDATING-OUTPUT-CONTINUATION13" :IN CLIM-INTERNALS::FRAME-UPDATE-POINTER-DOCUMENTATION) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>)
 22: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<CLOSURE (FLET "CONTINUATIO..
 23: (CLIM-INTERNALS::%INVOKE-UPDATING #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D143FB3}> #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% ..
 24: ((:METHOD CLIM-INTERNALS::COMPUTE-NEW-OUTPUT-RECORDS-1 (STANDARD-UPDATING-OUTPUT-RECORD T T)) #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D143FB3}> #<CLIM-CLX::CLX-691-POINTER..
 25: ((:METHOD INVOKE-UPDATING-OUTPUT (CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN T T T T T T)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<CLOS..
 26: ((FLET "UPDATING-OUTPUT-CONTINUATION12" :IN CLIM-INTERNALS::FRAME-UPDATE-POINTER-DOCUMENTATION) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>)
 27: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<CLOSURE (FLET "CONTINUATIO..
 28: (CLIM-INTERNALS::%INVOKE-UPDATING #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D141F93}> #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% ..
 29: ((:METHOD CLIM-INTERNALS::COMPUTE-NEW-OUTPUT-RECORDS-1 (STANDARD-UPDATING-OUTPUT-RECORD T T)) #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D141F93}> #<CLIM-CLX::CLX-691-POINTER..
 30: ((FLET "CONTINUATION7" :IN COMPUTE-NEW-OUTPUT-RECORDS) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}>)
 31: ((:METHOD INVOKE-WITH-OUTPUT-RECORDING-OPTIONS (OUTPUT-RECORDING-STREAM T T T)) #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE CLIM-INTERNALS::%POINTER-DOCUMENTATION% {10173FB043}> #<CLOSURE (FLET "CO..
 32: ((:METHOD COMPUTE-NEW-OUTPUT-RECORDS (STANDARD-UPDATING-OUTPUT-RECORD T)) #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D141F93}> #<CLIM-CLX::CLX-691-POINTER-DOCUMENTATION-PANE ..
 33: ((:METHOD REDISPLAY-OUTPUT-RECORD (UPDATING-OUTPUT-RECORD CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN)) #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  1 {101D141F93}> #<CLIM-CLX::CLX-..
 34: ((:METHOD CLIM-INTERNALS::FRAME-UPDATE-POINTER-DOCUMENTATION (STANDARD-APPLICATION-FRAME T T T)) #<GRAPH-VIEWER {1016D68633}> (((CLIM:COMMAND :COMMAND-TABLE #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {1015..
 35: ((SB-PCL::EMF CLIM-INTERNALS::FRAME-INPUT-CONTEXT-TRACK-POINTER) #<unused argument> #<unused argument> #<GRAPH-VIEWER {1016D68633}> (((CLIM:COMMAND :COMMAND-TABLE #<STANDARD-COMMAND-TABLE GRAPH-VIEWER..
 36: (HIGHLIGHT-APPLICABLE-PRESENTATION #<GRAPH-VIEWER {1016D68633}> #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> (((CLIM:COMMAND :COMMAND-TABLE #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {10153C9..
 37: ((:METHOD STREAM-READ-GESTURE (STANDARD-EXTENDED-INPUT-STREAM)) #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNCTION CLIM-INTERNALS::INPUT-CO..
 38: ((SB-PCL::EMF STREAM-READ-GESTURE) #<unused argument> #<unused argument> #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNCTION CLIM-INTERNALS:..
 39: ((:METHOD STREAM-READ-GESTURE :AROUND (CLIM-INTERNALS::DEAD-KEY-MERGING-MIXIN)) #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :TIMEOUT NIL :PEEK-P NIL :INPUT-WAIT-TEST #<FUNCTION CLIM-INT..
 40: (READ-COMMAND #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {10153C9D03}> :STREAM #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :COMMAND-PARSER NIL :COMMAND-UNPARSER NIL :PARTIAL-COMMAND-PARSER N..
 41: (READ-COMMAND-USING-KEYSTROKES #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {10153C9D03}> NIL :STREAM #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :COMMAND-PARSER NIL :COMMAND-UNPARSER NIL :PAR..
 42: (READ-COMMAND #<STANDARD-COMMAND-TABLE GRAPH-VIEWER {10153C9D03}> :STREAM #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}> :COMMAND-PARSER NIL :COMMAND-UNPARSER NIL :PARTIAL-COMMAND-PARSER N..
 43: ((:METHOD READ-FRAME-COMMAND :AROUND (T)) #<GRAPH-VIEWER {1016D68633}> :STREAM #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}>) [fast-method]
 44: ((:METHOD READ-FRAME-COMMAND :AROUND (APPLICATION-FRAME)) #<GRAPH-VIEWER {1016D68633}> :STREAM #<CLIM-CLX::CLX-691-APPLICATION-PANE DISPLAY {10170BD613}>) [fast-method]
 45: ((:METHOD DEFAULT-FRAME-TOP-LEVEL (APPLICATION-FRAME)) #<GRAPH-VIEWER {1016D68633}> :COMMAND-PARSER COMMAND-LINE-COMMAND-PARSER :COMMAND-UNPARSER COMMAND-LINE-COMMAND-UNPARSER :PARTIAL-COMMAND-PARSER ..
 46: (SCIGRAPH-TOP-LEVEL #<GRAPH-VIEWER {1016D68633}>)
 47: ((:METHOD RUN-FRAME-TOP-LEVEL (APPLICATION-FRAME)) #<GRAPH-VIEWER {1016D68633}>) [fast-method]
 48: ((:METHOD RUN-FRAME-TOP-LEVEL :AROUND (APPLICATION-FRAME)) #<GRAPH-VIEWER {1016D68633}>) [fast-method]
 49: ((:METHOD DWIM::START-FRAME (T)) #<GRAPH-VIEWER {1016D68633}> :WAIT-UNTIL-DONE T :MASTER NIL :BACKING-STORE :WHEN-MAPPED) [fast-method]
 50: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 51: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 52: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 53: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 54: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 55: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F190CA76D4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 56: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Frame Top Level" RUNNING {1017D27A03}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1017D279AB}> NIL)
 57: ("foreign function: call_into_lisp")
 58: ("foreign function: new_thread_trampoline")

**Comment by nsrahmad** [comment]
If you still experience this problem, Look at [https://github.com/McCLIM/McCLIM/wiki/Freetype#building-executables](https://github.com/McCLIM/McCLIM/wiki/Freetype#building-executables).
