### ISSUE TITLE
McCLIM fails to load on CLISP.

### ISSUE THREAD

**Issue by karlosz** [McCLIM/McCLIM#520]
McCLIM depends on static-vectors which doesn't support CLISP.

**Comment by dkochmanski** [comment]
Hey, I can't find such dependency in McCLIM so it is probably indirect. Could you narrow down a dependency chain so we know, which McCLIM dependencies cause this library to be pulled?

**Comment by karlosz** [comment]
Okay, so mcclim-image -> opticl -> pngload -> static-vectors.

**Comment by dkochmanski** [comment]
@slyrus modified upstream opticl to load old code on clisp.

@karlosz could you see if McCLIM works with upstream opticl on clisp?

**Comment by slyrus** [comment]
@karlosz just checking to see if this is still broken for you. thanks!

**Comment by kpoeck** [comment]
@slyrus what would be the best way to do the same thing for clasp that you just did for abcl and clisp?

**Comment by karlosz** [comment]
@slyrus @dkochmanski 
Just tried opticl master. Confirmed that it fixes the static vectors issue when loading McCLIM.

**Comment by dkochmanski** [comment]
closing issue in that case.
