### ISSUE TITLE
Command argument presentation types not evaluated

### ISSUE THREAD

**Issue by heshrobe** [McCLIM/McCLIM#540]
Hi,

I'm an old time CLIM user going back to my days at Symbolics.  I've been using the Allegro version for years and years.  Just started to see if McClim is up to the task of supporting my body of code.

An issue that bit me is that in the release I have command arguments to define-command aren't evaluated (except for a hack that doesn't work for my code)

The following comment is in the code for define-command:

  ;; Argument types shouldn't be evaluated. Unfortunately in McCLIM
  ;; they are, and in all McCLIM applications up to day types are
  ;; quoted. To preserve backward compatibility we honor this, but we
  ;; don't evaluate types which are not quoted, but rather add the
  ;; quotation ourself.
  ;;
  ;; Thanks to that we should achieve compatibility with other CLIMs
  ;; without breaking already existing applications (unless they did
  ;; some fancy computation in `define-command' macro which isn't
  ;; conforming anyway).

But that isn't what the CLIM 2 Spec says:

"name-and-options and body are not evaluated. In the argument descriptions, the parameter variable name is not evaluated, and everything else is evaluated at run-time when argument parsing reaches that argument, except that the value for :when is evaluated when parsing reaches the keyword arguments, and :gesture isn’t evaluated at all."

**Comment by dkochmanski** [comment]
You are right. I've made that commit and misread the spec. OTOH I agree with comment in here (http://bauhh.dyndns.org:8000/clim-spec/27-1.html#_1380) that it is arguable if the whole evaluation thing is intuitive. That doesn't change a fact, that it was a wrong thing to do.

Is a solution, where atomic presentation type specifier won't be evaluated and list will be evaluated acceptable to you? That way for the most typical case it will reasemble more method specialization and it won't break code created for McCLIM after the unfortunate commit.

**Comment by heshrobe** [comment]
Daniel,

Thanks for the rapid reply.  I can’t think of any reason why your proposal wouldn’t work.  The key reason that you need evaluation is when you have a presentation type with arguments (e.g. (foo bar)) and the argument itself is the value of a previous argument.  A very common case of this is arg1 names a particular object and argument 2 is some sort of set of things associated with the object.  That was the thing that tripped up my code.

By the way, I hadn’t paid much attention to McClim since I thought it had gone moribund (incorrectly, I’m happy to learn).  I wasn’t one of the original implementers when I was at Symbolics, but I do the know the original code pretty well and I’ve fixed large problems in earlier releases in the Allegro version of the original CLIM.  I’d be happy to make contributions and participate as part of the team in my "copious free time”.

Howie

> On Sep 13, 2018, at 2:09 PM, Daniel Kochmanski <notifications@github.com> wrote:
> 
> You are right. I've made that commit and misread the spec. OTOH I agree with comment in here (http://bauhh.dyndns.org:8000/clim-spec/27-1.html#_1380) that it is arguable if the whole evaluation thing is intuitive. That doesn't change a fact, that it was a wrong thing to do.
> 
> Is a solution, where atomic presentation type specifier won't be evaluated and list will be evaluated acceptable to you? That way for the most typical case it will reasemble more method specialization and it won't break code created for McCLIM after the unfortunate commit.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
Hey Howard,

I've implemented a fix (with an additional step of validating keywords for being constants at the macro expansion time). I'm waiting for others to review it.

Regarding contributions – I'm very happy about that offer. We could definitely use some help, especially from a person who used the "original" CLIM.

Daniel
