### ISSUE TITLE
Redesign copy&paste mechanism in McCLIM

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#544]
The purpose of this bug is to discuss an improvement to the copy&paste mechanism in McCLIM. As not everything is obvious, I would like to start by giving some background information.

In the text below, the words _selection_ and _clipboard_ and used interchangeably. In the prototype API, the word _clipboard_ is used as a generic name to refer to the concept of copy&paste. It is also used in the pair _clipboard_ and _selection_, referring to the two ways of selecting content (i.e. what is called `PRIMARY` and `CLIPBOARD` in the X11 model).

### X11 clipboard model

The original X11 model mostly worked with what is called the _primary selection_. In most X11 applications, this is the text which is highlighted when you click and drag over a piece of text.

Later, the concept of the _clipboard_ was introduced. From the point of view of the API's, it works exactly the same as the selection, with the only difference that the API's specify the atom `CLIPBOARD` instead of `PRIMARY`. In a simplex GNOME application, pressing Control-C causes the content of the primary selection to be copied into the clipboard.

In X11, performing a selection or a copy operation does not actually do anything to the content. Instead, it simply calls the function `XSetSelectionOwner` to tell the X-server which window owns the given selection. One of the arguments to this function is a value that indicates what type of selection it refers to (i.e. `PRIMARY` or `CLIPBOARD`).

Later, when an application wishes to paste something into its own window (from `PRIMARY` by middle-clicking, or from `CLIPBOARD` by pressing Control-V), the requesting client sends a message to the owner of the selection asking it what datatypes it supports. The requesting client can then perform another request to the owner to actually sent it in one of the formats that the previous request had returned.

On the clipboard owner's side, these requests come in in the form of a `SelectionRequest` event. This event is sent to the owner of the selection in question. One of the fields in the `SelectionRequest` event specifies what type of data is to be returned (for example, plain text, HTML, image, etc). One special datatype is the `TARGETS` type, which instructs the owner to return a list of the supported types.

### Other system's selection models

Unfortunately I don't have as much details about how other operating system's handle this, but my proposal that is outlined below attempts to be generic enough that it should be easy to make it work on other platforms too.

### Current copy&paste implementation in McCLIM

Currently, McCLIM has implemented a very thin abstraction on top of the X11 model. It simply exposes the concept of selection ownership, and forwards any incoming `SelectionRequest` event by calling a generic function so that the selection text can be returned.

The implementation of the `TARGETS` datatype is special, and always returns the same thing, an indication that only plain text is supported.

The current selection model also only supports `PRIMARY` and not `CLIPBOARD`. Both for sending and receiving data.

### Goals of the new implementation

The proposed new implementation aims to deal with the following issues:

- Support both `PRIMARY` and `CLIPBOARD`
- Support datatypes other than plain text
- Make it easier for arbitrary code to programmatically copy&paste
- Make the implementation less dependent on the X11 model

The point about other datatypes is particularly important. It will provide the possibility to support copying of complex Lisp objects between applications. Imagine being able to copy a graph, including its associated maths expressions from Climaxima into Second Climacs, even if they are running in different processes.

### Proposed implementation

The core of the idea is to decouple the ownership of the selection from the window (this is a very X11-specific concept, and other frameworks doesn't necessarily do the same) and instead represent a selection using an arbitrary object. McCLIM can then inquire the capabilities of this object to determine what datatypes this object can be converted into. This means that code that wants to copy something to the clipboard can do so by simply calling a single function. McCLIM will then handle the rest, including responding to requests for supported datatypes and actually sending that data to the requesting client.

In the current prototype implementation, taking ownership of the primary selection with a simple string is performed using the function `bind-clipboard` like so:

```
(bind-clipboard pane "foo" :clipboard-type :selection)
```

The first argument is a pane that this selection belongs to. This is needed for two reasons: The X11 implementation needs to bind the selection to a window. When this window disappears, the selection will be lost so it makes sense to bind it to the pane where the data conceptually comes from. The other reason is that even if (on some other desktop environment) there is no need to bind to a specific window, one still needs a way to associate the selection with a given port.

In the first iteration of the prototype, a standard generic function was created that allowed a developer to implement conversions of data to any of the supported datatypes (for example, HTML or images). This worked, but eventually I noted that the concept of conversions already exists in CLIM in the form of presentation types, so it was decided to try to take advantage of this.

In the current prototype, datatype conversions are performed using the presentation method `convert-clipboard-content`. For example, creating a custom object to HTML is done like so:

```
(define-presentation-method convert-clipboard-content (obj (type foo) (output-type (eql :html)) check-only)
  (get-foo-content-as-html obj))
```

If an object cannot be converted to the given type, `NIL` should be returned. The argument `check-only` is true if the caller isn't interested in the actual result but just wants to know if a conversion can be performed or not. This is used when McCLIM needs to determine what datatypes are supported (so that the CLX backend can respond to a `TARGETS` request). If the conversion process is extensive, the implementation can take a shortcut in this case and simply return true.

### Integration of the clipboard into the CLIM presentation system

Once conversion was performed using the presentation methods, it became clear that this could provide a basis for the ability to copy&paste presentation in any CLIM application.

The idea is to add new commands to the global command-table (i.e. the one that contains the `Describe` and `Help` commands). For now, the new command is called: `Copy to clipboard`. It accepts a single presentation as argument simply places this object onto the clipboard.

### Implementation problems when copying to clipboard

The implementation of `Copy to clipboard` is not obvious. The first attempt simply created a command `com-copy-to-clipboard` that specialised on all types.

This was shown to be problematic since when the command is called, the implementation has no knowledge of the presentation type of the object. For example, the argument may be a string, but its presentation type was `html-text`.

One possible solution to this is to define `com-copy-to-clipboard` like this:

```
(define-command
    (com-copy-to-clipboard :command-table global-command-table :name "Copy to clipboard")
    ((obj clipboard-object :prompt "object"))
  (bind-clipboard *standard-output* (clipboard-object-obj obj)
                                       :presentation-type (clipboard-object-presentation-type obj)))
```

In other words, instead of accepting arbitrary arguments, the type must be of type `clipboard-object`. One would then implement a translator like so:

```
(clim:define-presentation-translator object-to-clipboard-object (t clipboard-object global-command-table
    (object presentation)
  (make-instance 'clipboard-object :obj object :presentation-type (presentation-type presentation))
```

*The drawback of this* is that the function `com-copy-to-clipboard` would only accept this special wrapper object.

This solution would work, but the question is if it's actually the best approach.

### Further work

I would like to use this bug report to open a discussion as to what the final solution should look like.

This text has mainly focused on copying data out of McCLIM. This is mainly because I feel that pasting into an McCLIM application will be much easier.

**Comment by dkochmanski** [comment]
`even if they are running in different processes.` - does it apply to arbitrary lisp objects? if so, do you plan to serialize / deserialize them? or do you mean "running in different application frames"?

**Comment by dkochmanski** [comment]
I think it would be a nice idea to write a demo with the functionality mixed into your custom pane and commands being in this demo command table. So it is possible to experiment how it works between two frames implementing copy&paste mechanism.

**Comment by dkochmanski** [comment]
I don't understand the "drawback" with translator. Doesn't translator accept arbitrary presentation and then wraps it as part of the translation?

**Comment by dkochmanski** [comment]
`(bind-clipboard pane "foo" :clipboard-type :selection)`

- does this mean, that pane makes available string "foo" in its clipboard?
- what are available clipboard-types? what is a practical difference between them?
- how do you select text with a pointer instead of calling a function with arbitrary string?

**Comment by dkochmanski** [comment]
adding "paste" part will be also useful (i.e deserializing data, verifying if it may be pasted in this and this context, which pane receives such paste, is paste an event or a command - that things are not obvious to me)

**Comment by lokedhs** [comment]
> `(bind-clipboard pane "foo" :clipboard-type :selection)`
> 
>     * does this mean, that pane makes available string "foo" in its clipboard?

Conceptually there is only one clipboard system-wide. From the user's point of view, the string "foo" becomes available in the clipboard. The fact that it's managed by a specific object in a specific Lisp runtime is not really relevant.

Whoever held the clipboard prior to the copy operation will receive an event telling it that it has lost ownership of it.

>     * what are available clipboard-types? what is a practical difference between them?

Currently there are two clipboard types: `SELECTION` is the text that has been selected in the mouse drag operation. This is the same as selecting text in any other graphical application.

`CLIPBOARD` is the same as when you press control-c in a GNOME application. This operation copies the content of `SELECTION` into `CLIPBOARD`. The proposed API allows the programmer to directly place data in the `CLIPBOARD`, but a command that does something similar to control-c in GNOME could also be implemented. For example a CLIM command `Copy selection to clipboard`. It could also be bound to a key.

X11 has more types than this, but since they are very rarely used, and they aren't easily mapped to other window systems, I didn't see much need to consider supporting them.

>     * how do you select text with a pointer instead of calling a function with arbitrary string?

Selection text with the pointer can already be done in McCLIM, and it has been adopted to use the new API's. Functionally, there is no difference as even the old implementation also placed the selection into the Primary Selection.

Adding a `Copy selection to clipboard` would simply provide the same functionality as most applications have (by typing control-c)

**Comment by lokedhs** [comment]
> I don't understand the "drawback" with translator. Doesn't translator accept arbitrary presentation and then wraps it as part of the translation?

The drawback is that you won't be able to simply call `com-copy-to-clipboard` with a string, but a separate API will have to be used. That makes it less elegant, but perhaps I'm being too picky.

**Comment by dkochmanski** [comment]
shall we close this ticket?

**Comment by lokedhs** [comment]
Agreed. Any further changes should be done as part of a separate issue.
