### ISSUE TITLE
text-editor ignores :width and :height

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [McCLIM/McCLIM#545]
Here's a minimal example:

```
;; -*- Syntax: Common-Lisp; Package: CLIM-USER; Base: 10 -*-

(in-package :clim-user)

(define-application-frame useless-frame () ()
  (:panes
    (display text-editor :value "USELESS!"
	     :width 400 :height 400)
    (help text-editor :value
	  (format nil
		  (concatenate 'string 
			       "Moving keys are standard VI keys:~%"
			       "l: right~%"
			       "k: up~%"
			       "j: down~%"
			       "h: left~%"
			       "q: quit~%")) 
	  :width 400 :height 150))
  (:layouts
    (default
      (vertically ()
	display 
	help))))

(defun show-useless ()
  (let ((frame (make-application-frame 'useless-frame)))
    (run-frame-top-level frame)
    frame))
```
Here's a screenshot of this application-frame being displayed by a working CLIM implementation:

![image](https://user-images.githubusercontent.com/12368105/45673501-b01d8c80-badf-11e8-8e2d-b292e89c3572.png)

Here's the same application frame as displayed by McCLIM:
![image](https://user-images.githubusercontent.com/12368105/45673581-e65b0c00-badf-11e8-9690-8554ebf8b977.png)

Derived from this demo program: http://www.frank-buss.de/lisp/tilt-mazes.lisp.txt

**Comment by dkochmanski** [comment]
Thank you for the report. According to CLIM II specification[1] to set the size of a text-editor you provide `:nlines` and `:ncolumns` arguments. It is not specified whenever width/height arguments are ignored or not. That said I've just pushed a fix which fallbacks to provided width/height in case if ncolumns/nlines are not provided.

Please close this issue when you confirm that fix works for you.

**Comment by dkochmanski** [comment]
I've pushed one more commit which fixes off-by-one error when autoscrolling (when making a new line below pane-height).

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
It looks much better now. The screenshot is from Open Genera.
