### ISSUE TITLE
Pane width is higher than expected.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [McCLIM/McCLIM#550]
Like my last one, it's derived from the program at http://www.frank-buss.de/lisp/tilt-mazes.lisp.txt.

The thing that seems to trigger the unexpected behavior:

1. There's an `:application` pane with a width and a height.
2. There's a `text-editor` pane with only a width.

In Genera, the window as a whole will have the width specified by the
`:application` pane, and the `:application` pane will get exactly the width
it asked for.

In McCLIM, the width of both the `:application` pane and the window as a whole will be 
898 pixels, regardless of the `:width` given for the `:application` window. 

This causes the aspect ratio of the tilt-mazes game to be stretched on Linux because the game is programmed to scale the maze to the actual size of the window. 

```
;; -*- Syntax: Common-Lisp; Package: CLIM-USER; Base: 10 -*-

(in-package :clim-user)

(defgeneric draw-useless (frlame stream &key max-width max-height))

(define-application-frame useless-frame () ((x :initform 0) (y :initform 0))
  (:panes
    (display :application
             :display-function 'draw-useless
             :scroll-bars nil
             :width 400 :height 400)
    (help text-editor :value
          (format nil
                  (concatenate 'string
                               "Moving keys are standard VI keys:~%"
                               "l: right~%"
                               "k: up~%"
                               "j: down~%"
                               "h: left~%"
                               "q: quit~%"))
          :height 150))
  (:layouts
    (default
      (vertically ()
        display
        help))))

(defmethod draw-useless ((frame useless-frame) stream &key max-width max-height)
  (declare (ignore max-width max-height))
  (write-string (format nil "Drawing in a ~S by ~S frame~%"
                        (bounding-rectangle-width stream)
                        (bounding-rectangle-height stream))
                stream)
  (draw-rectangle* stream 10 10 20 20))



(defun show-useless ()
  (let ((frame (make-application-frame 'useless-frame)))
    (run-frame-top-level frame)
    frame))
```

**Comment by dkochmanski** [comment]
It seems it is Drei's fault that it sets default width for drei-panes to 900. Like the last time please close if you may confirm, that this works for you.
