### ISSUE TITLE
Clouseau: hash-table presentation is drawn strangely

### ISSUE THREAD

**Issue by scymtym** [McCLIM/McCLIM#552]
When the inspector presents a hash-table, as in
```lisp
(defclass foo () ((bar :initform (make-hash-table)))) (clouseau:inspector (make-instance 'foo))
```
it draws a graph and a string on top of the graph. The "Hash table" string is drawn with a vertical offset and also misaligned with respect to the presentation highlight.

**Comment by scymtym** [comment]
![screenshot](https://user-images.githubusercontent.com/150189/45829445-39f57180-bcfb-11e8-9840-6e192f6d4ba6.png)

**Comment by robert-strandh** [comment]
![clouseau](https://user-images.githubusercontent.com/1449025/45829711-d0299780-bcfb-11e8-8800-b1be6294b97d.png)
