### ISSUE TITLE
Does McCLIM depend on the foreign libraries?

### ISSUE THREAD

**Issue by thrashdin** [McCLIM/McCLIM#581]
So with the clx backend is this project written in pure cl, without any cfii, any c code and all that? Not sure if this is explicitly mentioned in the description.

**Comment by dkochmanski** [comment]
In principle yes – it is written in pure CL. Some extensions may depend on ffi (for instance extension for png images depends on opticl which depends on pngload which depends on static-vectors, which allocates memory via ffi). McCLIM with CLX backend is known to work on CL implementations without any FFI support.

**Comment by dkochmanski** [comment]
As of explicitly mentioning these things I have not encountered such preemptive practice anywhere.
