### ISSUE TITLE
Creating empty labels

### ISSUE THREAD

**Issue by thrashdin** [McCLIM/McCLIM#605]
For some reason creating label without :text and running the app reboots my user session. I was trying to set the text of the label, and discovered this. Funny thing is that in case some :text "text" is passed, it also reboots my user session, but only if I launch it once, then close and then launch it again.
    ` (screen :label :text "input")`

Also https://stackoverflow.com/questions/53224545/mcclim-text-labels-access

I have Debian, everything as latest as it can be, and i weekly dist-upgrade. If some update will fix the problem, I'll add it here.

**Comment by dkochmanski** [comment]
Hey, we already had this issue, this should be fixed in clx (to not send no-op requests with empty strings). Curiously enough some x11 servers crash and some don't.

**Comment by Sokolov57** [comment]
Is there any workaround then? Smith to replace labels without looking odd, and with same or similar functionality.

**Comment by nsrahmad** [comment]
>Is there any workaround then? Smth to replace labels without looking odd, and with same or similar functionality.

Assuming the functionality mentioned here is ability to display text that could change. Looking around in `clim-examples`, I found `clim-fig` uses `text-field` for this purpose. Note the 
status at the bottom:
![clim-fig-text-field-as-status](https://user-images.githubusercontent.com/10996250/66548748-7c385d80-eb5f-11e9-943b-a8953e029a9a.png)
That does look odd. A label would be better for that. Unfortunately, `label-pane` in CLIM is not specified to have a function that changes the label. However in McCLIM (after #866 is merged), `clim-extensions:label-pane-label` can be used to get a label and `(setf (clime:label-pane-label))` to change the label.

`clim-fig` with a label:
![clim-fig-after](https://user-images.githubusercontent.com/10996250/66549925-008be000-eb62-11e9-898e-7a666e98516a.png)
