### ISSUE TITLE
text-editor: ncolumns specifier doesn't take into account text-style

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#616]
Steps to reproduce:

```
(define-application-frame benchmarking ()
  ()
  (:pane (vertically ()
           (make-pane :text-editor :nlines 16 :ncolumns 8 :text-style (make-text-style :fix :roman 12)))))
```

Pane width is (empirically speaking) `(1- (* 2 ncolumns character-width))`. I suspect that the problem stemps from `text-style-width` which is calle in `compose-space` for `text-editor-gadget` – requires investiation.

**Comment by nsrahmad** [comment]
Fixed.
