### ISSUE TITLE
copy/paste in CLIM applications

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#62]
For instance to copy code snipped from web to CLIM Listener. Some valuable insight from @gabriel-laddel:

```
(uiop:run-program "xclip -o" :output :string)
^ anyways, wrap that up in a (define-command ..
I don't have the code in front of me, but the command table you use is the CLIMACS::BASE-TABLE
and to insert it at point (flexichain:insert-sequence (point) (coerce that-shell-code 'string))
```

**Comment by gabriel-laddel** [comment]
```
(in-package climacs-gui)
(define-command (com-yank-x-clipboard :name t :command-table drei-lisp-syntax::lisp-table) ()
  (flexichain:insert-sequence (point) (coerce (mm::rp "xclip -o" :string) 'string)))

(esa-io:set-key 'com-yank-x-clipboard 'drei-lisp-syntax::lisp-table '((#\y :META :CONTROL)))
```

**Comment by gabriel-laddel** [comment]
IMHO, there should be a file "usability-monkey-patches.lisp" that is loaded after everything else in CLIM and is included in the repo with the above + similar. Does else have an issue with this?

**Comment by dkochmanski** [comment]
yes, I think that it's better to have a separate issue for each patch. Monkey-patching things will just mask an issue (because we won't see the misbehaviour nor the users) and create a technical-debt.

**Comment by dkochmanski** [comment]
eventually we could create a system which *has to* be loaded manually after mcclim, which could be called monkey-patches

**Comment by TeMPOraL** [comment]
Can we have something that does *not* require shelling out to an external application?

Besides the general ugliness of the very concept, xclip is not available on some Linux platforms by default. Isn't there an API for X11 we can use (I only know one for Windows)? It could also allow to copy-paste other types of data than just textual strings.

**Comment by dkochmanski** [comment]
I think that CLX has or may have such extension and this would be a proper way to do that

**Comment by earl-ducaine** [comment]
I believe [dbus](https://www.freedesktop.org/wiki/Software/dbus/) the unix-like framework for desktop applications to interact with each other.  The X Windows clipboard is not powerful enough for most types of interaction, and in that sense xclip is mostly 'legacy'.   There are a couple of CL dbus libraries.  But I'm not sure of their features/completeness or how easy it would be to integrate with MCCLIME.  But ultimately that's probably the route to go, at least for linux/bsd desktop interoperability.

**Comment by gas2serra** [comment]
I did a few improvement (linux, clx):
> it is working in every drei pane
> I add a "copy" command

It will be nice to implement "xclip" using the text selection protocol (Core/clim-basic/text-selection.lisp).
Please, let me know what do you think.
A.

--------------------

(in-package drei)

(define-command (com-past-x-clipboard :name t :command-table drei:editing-table) ()
  (flexichain:insert-sequence (point) (uiop:run-program "xclip -selection clipboard -o" :output :string)))

(define-command (com-copy-x-clipboard :name t :command-table drei:view-table) ()
  (with-input-from-string (input-stream (coerce (kill-ring-yank *kill-ring*) 'string))
    (uiop:run-program "xclip -selection clipboard -i " :output nil :input input-stream)))

(esa-io::set-key 'com-past-x-clipboard 'drei:editing-table '((#\y :META :CONTROL)))
(esa-io::set-key 'com-copy-x-clipboard 'drei:view-table '((#\w :META :CONTROL)))

**Comment by dkochmanski** [comment]
As @TeMPOraL pointed out, it would be good, if we could do it without shelling out to. CLX has an example for that in `clx/demo/clipboard.lisp`

**Comment by gas2serra** [comment]
All selection protocol events are already used by Core/clim-basic/text-selection.lisp. If we want a solution using CLX we need to partially redesign text-selection.

**Comment by gas2serra** [comment]
Which version of Climacs do you use? quicklisp or Robert's one?

**Comment by nsrahmad** [comment]
With the work of @lokedhs and @dkochmanski , McCLIM now supports proper Copy/Paste.
