### ISSUE TITLE
glitches during long display

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#630]
Problem may be related to coordinate swizzling. When we display big quantities of text (preasumbly going outside the mirror size that is 32k) we have corrupted output on a sheet after some time. On multiple-mirror setup this is fixed after display is complete. On single-mirror setup glitches remain (that means, that output record history is corrupted).

![obraz](https://user-images.githubusercontent.com/6871201/49699652-02001b00-fbd4-11e8-8617-c21306c48952.png)

```common-lisp
(in-package #:clim-user)

(clim:define-application-frame bla ()
  ()
  (:panes (main :application
                :width 800
                :height 500
                :scroll-bars nil
                :display-function 'display-main))
  (:layouts (default
                (clim:scrolling (:scroll-bars t) main))))

(defun display-main (frame pane)
  (declare (ignore frame))
  (time (loop for i from 0 below 10000
              do (format pane "~R~%" i)
             (finish-output pane))))

(defun demo (&optional single)
  (let ((clim:*default-server-path*  (if single
                                         '(:clx-ttf :mirroring :single)
                                         '(:clx-ttf :mirroring :full))))
    (clim:run-frame-top-level (clim:make-application-frame 'clim-user::bla))))
```

**Comment by nsrahmad** [comment]
The output no longer curropts. Tried both single-mirror and multi-mirror in separate images.
