### ISSUE TITLE
CLX bold fonts don't show up

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#633]
When I open the font rendering demo and click on a font, instead of being drawn in bold (as I think should happen), the clicked on text disappears, as shown in the attached image.

I'm probably just missing a font, but it would be nice if there were some sort of warning or instructions on how to avoid the problem.

![screenshot from 2018-12-13 14-30-27](https://user-images.githubusercontent.com/327708/49971660-10a44600-fee4-11e8-9850-d02ed2c31397.png)

**Comment by scymtym** [comment]
Seems to a duplicate of #650 and #681.
