### ISSUE TITLE
possible non-conformant use of loop in examples/tabdemo.lisp

### ISSUE THREAD

**Issue by kpoeck** [McCLIM/McCLIM#648]
I believe https://github.com/McCLIM/McCLIM/blob/master/Examples/tabdemo.lisp#L114 is not strcitly following the ansi-spec and effectively gives a runtime error in clasp.

Reduced test-case:
```lisp
;;; in clasp
COMMON-LISP-USER>> (let ((old (list 1)))
  (loop while old
     for i = (random (length old))
     do (pop old)))
;;; Warning: Iteration in LOOP follows body code.
Current LOOP context: FOR I = (RANDOM (LENGTH OLD)) DO.

Debugger received error of type: TYPE-ERROR
0 is not of type (OR (INTEGER 1) (FLOAT (0.0))).
````

Looking at the ansi-spec it seems that  for clauses need to come before while clauses in loop, so the above use seem to be non-conformant although ecl, ccl and sbcl seem to have no problem with it.

Possible fix
```lisp
(define-tabdemo-command (com-randomize-tabdemo :name t)
    ()
  (setf (tab-layout-pages (tabdemo-layout))
	(let ((old (tab-layout-pages (tabdemo-layout)))
	      (new '()))
	  (loop while old
                ;;; #+clasp this used to be an non-conformant loop use, loop while .. for ... do must be loop for while do
             do (let ((i (random (length old))))
                  (push (elt old i) new)
                  (setf old (remove-if (constantly t) old :start i :count 1))))
	  new)))
````

**Comment by nsrahmad** [comment]
Much bettter would be to use Alexandria:
```lisp
(define-tabdemo-command (com-randomize-tabdemo :name t)
    ()
  (setf (tab-layout-pages (tabdemo-layout))
        (alexandria:shuffle (tab-layout-pages (tabdemo-layout)))))
```
I have pushed it to master branch. We do have plans to go through all examples and clean them.

BTW, whats the status of McCLIM with Clasp?

**Comment by kpoeck** [comment]
Regarding your question: Yesterday I could execute sucessfully all demos of (clim-demo:demodemo)  - i mean the left column of the dialog- for the first time in Clasp without errors.

You need my fork - and my fork of clx - but I should be able to clean that up shortly, so that my fork can dissapear

**Comment by nsrahmad** [comment]
Understood, Thank you for reporting this issue.
