### ISSUE TITLE
accepting-values key bindings

### ISSUE THREAD

**Issue by nsrahmad** [McCLIM/McCLIM#654]
From the wiki, Accepting values key-bindings are:
>  
- OK :keystroke `(#\[ :control)`
- Exit :keystroke `(#\] :control)`
- Abort :keystroke `(#\z :control)`
- Next :keystroke `(#\n :meta)`
- Previous :keystroke `(#\p :meta)`

When looking at the source (in `Core/clim-core/dialog.lisp`) I found:
- There never was a command named `OK` and `(#\[ :control)` was never bound.
- `Exit` command actually submits the dialog, and should be bound to `#\[ :control)` as `OK` action. Currently, It is bound to `(#\] :control)`.
- `Abort` command which is currently `(#\z :control)` actually cancels the dialog, and should be bound to `(#\] :control)` as `Cancel` action.

**Comment by lokedhs** [comment]
These keybindings are quite non-intuitive, even if the proposed corrections are made. I'd like to see Meta-RET to submit a form.

**Comment by duuqnd** [comment]
I'd like to ask about what the difference between Exit and Abort is supposed to be. I can't quite see how they would be different. Would it be acceptable to have them both do the same thing?

**Comment by nsrahmad** [comment]
@duuqnd I think I made a mistake interpreting what those keys meant. On looking up in Symbolics guide it cleared up. There are only two command needed here which are Exit (which submits the dialog) and Abort (which aborts the dialog).

So "OK" is just a label for Exit and "Cancel" is label for Abort. In Symbolics CLIM, corresponding labels are "Exit" and "Abort".
