### ISSUE TITLE
Regression in CONVERT-TO-GESTURE

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#668]
The change 104b3157d871cfb445a9521dc2225caad503dac9 introduces a regression where it is no longer possible to detect when shift is used together with return.

The problem can most easily be seen in Climaxima where Shift-Return is used to introduce a newline into a command. After this change, shift-return now results in a message `Return not bound`.

**Comment by dkochmanski** [comment]
this code was modified further at later date to use standard mechanism stream-process-gesture. Are you sure it is this change? The only place where the problem could occur is `key-press-event` leg of a typecase, but it looks quite similar to the method.

Please try compiling this in climi package and see if it helps
```
(defmethod stream-process-gesture ((stream standard-extended-input-stream) gesture type)
  (declare (ignore type))
  (typecase gesture
    ((or character symbol pointer-button-event)
     (values gesture (type-of gesture)))
    (key-press-event
     (let ((modifiers (event-modifier-state gesture))
           (character (keyboard-event-character gesture)))
       (if (and (or (zerop modifiers)
                    (eql modifiers +shift-key+))
                character)
           (values (char-for-read character) 'standard-character)
           (values gesture (type-of gesture)))))
    (otherwise
     nil)))
```

if it does, please modify this method in stream-input and make a pull request.

**Comment by lokedhs** [comment]
Thank you. The fix does work. I'll create a pull request.
