### ISSUE TITLE
tabify-buffer-region in Libraries/Drei/base.lisp is slightly wrong

### ISSUE THREAD

**Issue by wbooze** [McCLIM/McCLIM#678]
I tried M-x Tabify Region many times over in Climacs, and some words looked almost like written together.
But upon closer inspection one could observe the Cursor disappear in between the words.
I thought maybe it's a font-issue, or some issue with presentation types. I looked at the file via emacs in a terminal and there was no hint of something being wrong. The almost together written words had a real space in there. 
The Bug also made the Climacs window split upon completion.

It's some off by one error. No resolution yet!

**Comment by nsrahmad** [comment]
Could you try replacing function definition of `maybe-update-recordings` in `McCLIM/Libraries/Drei/views.lisp` with below version:
```lisp
(defun maybe-update-recordings (stream tabify)
  (with-accessors ((space-width recorded-space-width)
                   (tab-width recorded-tab-width)
                   (recorded-stream recorded-stream)) tabify
    (unless (eq stream recorded-stream)
      ;; Update the recorded values.
      ;; Width of space is usually zero, what is really needed here is advance-width
      ;; --NSR 2019-01-21
      (setf space-width (climb:font-glyph-dx (climb:text-style-to-font
					      (find-port)
					      (medium-text-style stream))
					     (char-code #\Space))
            tab-width (stream-character-width stream #\Tab)
            recorded-stream stream))))
```
