### ISSUE TITLE
streams: text-margin treatment doesn't conform to the specification

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#680]
http://bauhh.dyndns.org:8000/clim-spec/29-4.html#_1672 (see annotations)

We treat text-margin as the right margin coordinate. Description (ignoring "default value" which contradicts what is told in the same paragraph) indicates, that we should treat it as a space on the left and on the right of the text area (wrapping-wise).

On the following picture space after red line should be 50% smaller and that 50% should be put on the left:

![obraz](https://user-images.githubusercontent.com/6871201/50891630-01d68380-13fd-11e9-8baa-c2367da326fc.png)

**Comment by dkochmanski** [comment]
stream-text-margin returns right margin position indeed: http://bauhh.dyndns.org:8000/clim-spec/15-4.html#_809

**Comment by dkochmanski** [comment]
```
(defclass standard-extended-output-stream (extended-output-stream
                                           standard-output-stream)
  ((cursor :accessor stream-text-cursor)
   (foreground :initarg :foreground :reader foreground)
   (background :initarg :background :reader background)
   (text-style :initarg :text-style :reader stream-text-style)
   (vspace :initarg :vertical-spacing :reader stream-vertical-spacing)
   (left-margin :initarg :text-left-margin :reader clime:stream-text-left-margin)
   (right-margin :initarg :text-left-margin :reader clime:stream-text-right-margin)
   ;; Should we leave :text-margin vaguely specified and upkeep its current
   ;; workings (1) or should we fix it to the correct interpretation (2)?
   ;;
   ;; (1) - :text-margin indicates x coordinate of the right margin
   ;; (2) - :text-margin indicates free space around text area (if we wrap)
   ;;
   ;; nb: stream-text-margin reader and writer specification is very clear that
   ;; they are about x coordinate. We discuss the initarg. -- jd 2018-01-09
   (margin :initarg :text-margin #|:writer (setf stream-text-margin)|#)
   (eol :initarg :end-of-line-action :accessor stream-end-of-line-action)
   (eop :initarg :end-of-page-action :accessor stream-end-of-page-action)
   (view :initarg :default-view :accessor stream-default-view)
   (baseline :initform 0 :reader stream-baseline)
   ;; the max char height of the current line
   (char-height :initform 0 :accessor %stream-char-height))
  (:default-initargs
   :foreground +black+ :background +white+ :text-style *default-text-style*
   :vertical-spacing 2 :end-of-page-action :scroll
   :text-margin nil :text-left-margin 0 :text-right-margin 0 :end-of-line-action :wrap
   :default-view +textual-view+))
```

**Comment by nsrahmad** [comment]
>how much space is left around the inside edge of the pane

This specifically said the `inside edge` not `edges`. "around" can be used for a single edge. It looks like it only tallks about the right edge.

There's also `filling-output`[http://bauhh.dyndns.org:8000/clim-spec/20-3.html#_1014](http://bauhh.dyndns.org:8000/clim-spec/20-3.html#_1014) which seems to already implement word wrap and specifically controls the right edge. For left edge, there is `indenting-output`[http://bauhh.dyndns.org:8000/clim-spec/20-2.html#_1012](http://bauhh.dyndns.org:8000/clim-spec/20-2.html#_1012). 

For an example, run the following and try different window sizes.
```lisp
;;;; Load McCLIM first.

(in-package :clim-user)

(define-application-frame wrap-test ()
  ()
  (:pane
   :application
   :display-function #'display-wrap-test))

(defun display-wrap-test (frame pane)
  (declare (ignore frame))
  (let ((margin 60))
    (indenting-output (pane margin :move-cursor t)
      (filling-output (pane :fill-width (- (stream-text-margin pane) margin) :break-characters '(#\SPACE))
	(format pane "Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget, lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet tortor.  Nam euismod tellus id erat.")))))

(define-wrap-test-command (com-refresh :menu t)
    ())

(defun run-wrap-test ()
  (run-frame-top-level (make-application-frame 'wrap-test)))

(clim-user::run-wrap-test)
```

And FYI, Dynamic Windows had something called `margin-mixin` which was quite comprehensive. A screenshot from the Part A of the manual:

![dynamic-windows-margin](https://user-images.githubusercontent.com/10996250/50943411-61429b00-14b2-11e9-960f-49efd7f292d5.png)

Dynamic Windows manual is available in in two parts:
[Part A: 17 MB pdf](http://www.bitsavers.org/pdf/symbolics/software/genera_7/999025_Programming_the_User_Interface_Sep86.pdf)
[Part B: 22 MB pdf](http://www.bitsavers.org/pdf/symbolics/software/genera_7/999029_Programming_the_User_Interface_Volume_B_Aug86.pdf)

If something looks underspecified in CLIM, please take a look in these mauals to see if you could find something related for better understanding.

**Comment by dkochmanski** [comment]
thank you for the references. I'll read through them and see if they map well into what I've implemented. For work in progress see input-refactor branch (I've implemented stream-margin-mixin).

**Comment by dkochmanski** [comment]
After reading the spec and skimming through Dynamic Windows documentation here's what I think about all that:

- I find margins and indenting/filling orthogonal mechanisms (the latter could be used to overwrite margins temporarily i.e to indent block of code, while margins show general output geometry)

- text-formatting facilities doesn't give any control over vertical margins (we could work that out with `with-local-coordinates` macro, but again it seems to be orthogonal mechanism for temporal amendment). both facilities might find useful margins to achieve their goals though (maybe simplifying stream class hierarchy), *I'm curious how feasible that would be*.

- I agree that `stream-text-margin` (and its `setf` method) are about the right margin position in sheet coordinates

-  under any interpretation `:text-margin` is implemented wrong (because value put there sets the right margin coordinate, not a "space around) – so we have to change it. I think splitting margin between left and right will be more useful UX-wise – also I can't read `around edge` other way, if it is around "right margin position", then factual right margin is half the width put here, so it contradicts itself.

- after skimming through DW documentation (thank you for that, I was looking for these documents a week ago or so) indicates, that "their" margins were a mashup of CLIM text-formatting, bordered-output and (missing) margin protocols – I think it won't be very useful for us to implement that.

nb: input-refactor has almost complete implementation of margins. I still have some small adjustements to do. After that I plan to write a protocol draft and (if accepted) put it in the manual.

I'd love to hear your thoughts about above conclusions. @nsrahmad @scymtym @lokedhs @slyrus

**Comment by scymtym** [comment]
> under any interpretation :text-margin is implemented wrong (because value put there sets the right margin coordinate, not a "space around) – so we have to change it. I think splitting margin between left and right will be more useful UX-wise – also I can't read around edge other way, if it is around "right margin position", then factual right margin is half the width put here, so it contradicts itself.

I think interpreting `:text-margin` as the x coordinate at which the end-of-line action is triggered could be the best option:
* That would be analogous to `*print-right-margin*`in the sense that both specify an offset from the left edge in appropriate units
* It would match the behavior of the similarly named `stream-text-margin`
* The description of the default value suggests this interpretation
* I think
  >These options specify the default text margin (that is, how much space is left around the inside edge of the pane) [...]

  can be interpreted as "the option controls the margin by specifying the x coordinate" and the text in parenthesis can be taken to just explain the word "margin"

I agree that distributing the specified margin between the left and right edges would often be more convenient but it doesn't seem consistent to me.

**Comment by dkochmanski** [comment]
Still, we should fix wording in the spec about `:text-margin` argument that it is the right margin position.
