### ISSUE TITLE
list-pane makes invisible selected item

### ISSUE THREAD

**Issue by josrr** [McCLIM/McCLIM#681]
If you select an item that is not the first one, it becomes invisible; I can't reopen the issue [650](https://github.com/McCLIM/McCLIM/issues/650), so I created a new one.

I'm using SBCL 1.4.15 in Linux.

[screenshot](https://www.rufina.link/archivos/drawing-test01.png)

**Comment by admich** [comment]
It's depends on implementation. It's the same of issue  #650. The issue was closed because nsrahmad reported that in sbcl 1.4.15  he wasn't able to reproduce it. Anyway I also have the same problem in 1.4.15.

**Comment by nsrahmad** [comment]
I usually keep the debug and safety to 3 in SBCL. When I reverted to default settings, I can reproduce this.

To confirm this, 
1) Please put `(proclaim '(optimize (debug 3) (speed 0) (safety 3) (compilation-speed 0)))` in your `.sbclrc`. 
2) Delete the cache dir with `rm -R ~/.cache/common-lisp/sbcl*`. 
3) Load the demos and check the list test demo.

If the bug disappears, then it is a bug in SBCL. Changing optimize settings shouldn't change the behaviour. It cannot be reproduced in CCL, which also confirms this.

**Comment by josrr** [comment]
yes I can confirm it, the bug disappeared when I changed the SBCL optimization options.

**Comment by pouar** [comment]
reported it upstream
https://bugs.launchpad.net/sbcl/+bug/1811623
did a bisect on SBCL itself and it seems to have been introduced in sbcl/sbcl@70f85676b
