### ISSUE TITLE
Aborted command invokes redisplay

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#710]
Redisplay should only be invoked after successful command completion. Steps to reproduce: compile this file (it should open the window right away) and type `C-c` a few times in the interactor:

```common-lisp
(in-package #:clim-user)

(defun display (frame pane)
  (let ((x (random 100))
        (y (random 100)))
   (draw-rectangle* pane x y (+ x 100) (+ y 100))))

(define-application-frame clim-asdf ()
  ()
  (:panes (int :interactor :end-of-line-action :allow)
          (app :application :display-function 'display))
  (:layouts (default (horizontally () int app))))

(run-frame-top-level (make-application-frame 'clim-asdf))
```

Expected: no redisplay is invoked (rectangle on the right doesn't change its position)
Observed: redisplay is invoked

![image](https://user-images.githubusercontent.com/6871201/52636045-cb909600-2ecb-11e9-90dd-e82824edbef3.png)
![image](https://user-images.githubusercontent.com/6871201/52636059-d519fe00-2ecb-11e9-8cf5-9de2d98fadaf.png)

**Comment by dkochmanski** [comment]
nb: "just" hitting enter does the same (no command is being executed).

**Comment by josrr** [comment]
The [specification](http://bauhh.dyndns.org:8000/clim-spec/29-4.html#_1669) says that redisplaying must occur after the execution of a command if the option `:display-time` is `:command-loop`. But this option can also have the values `nil` and `t`; other behaviors should be followed in the latter two cases.

**Comment by dkochmanski** [comment]
yes, that's what I mean. default display time for application pane is command-loop.

**Comment by josrr** [comment]
I have a fix to this issue, I wanted to do a pull request, but I messed up:  the new branch (redisplay-fix) that I created  also includes the changes to the drawing tests, so here is the code:

[frames.lisp](https://github.com/josrr/McCLIM/blob/redisplay-fix/Core/clim-core/frames.lisp#L473)
