### ISSUE TITLE
Enabling margins adds extra vertical space in interactor pane

### ISSUE THREAD

**Issue by lokedhs** [McCLIM/McCLIM#737]
If a command outputs graphics wrapped in `WITH-ROOM-FOR-GRAPHICS` and the interactor pane uses text margins, some extra space is added after the graphics. If the margins are removed, this doesn't happen.

This is the result of running the test program:
![with-margins](https://user-images.githubusercontent.com/1028755/54507434-49890680-497c-11e9-8bfa-ff82e0a231b0.png)
If the margins are removed, then the output is as expected:
![without-margins](https://user-images.githubusercontent.com/1028755/54507450-560d5f00-497c-11e9-9a8c-bf7cd21cae83.png)

**Comment by lokedhs** [comment]
Here is the test program:
```
(clim:define-application-frame foo-frame ()
  ()
  (:panes (interaction-pane :interactor
                            :text-margins '(:left (:absolute 10)
                                            :right (:relative 10))))
  (:layouts (default (clim:vertically ()                     
                       interaction-pane)))
  (:geometry :width 600 :height 600))

(defun open-foo-frame ()
  (let ((frame (clim:make-application-frame 'foo-frame)))
    (clim:run-frame-top-level frame)))

(define-foo-frame-command (cmd-foo :name "Foo")
    ()
  (let ((stream (clim:find-pane-named clim:*application-frame* 'interaction-pane)))
    (clim:with-room-for-graphics (stream :first-quadrant nil)
      (clim:surrounding-output-with-border (stream :ink clim:+blue+)
        (format stream "Foo")))))
```

**Comment by lokedhs** [comment]
The extra space seems to be added here:

https://github.com/McCLIM/McCLIM/blob/master/Core/clim-core/frames.lisp#L521

**Comment by lokedhs** [comment]
The cause seems to be this function in `stream-output.lisp`:
```
(defmethod stream-start-line-p ((stream standard-extended-output-stream))
  (multiple-value-bind (x y) (stream-cursor-position stream)
    (declare (ignore y))
    (= x (stream-cursor-initial-position stream))))
```

If the call to `=` is changed to `<=`, then the problem goes away.

However, it is arguable that the cursor position should never be less than the margin.

**Comment by dkochmanski** [comment]
in short the problem is caused by with-output-to-output record (and position fixups in wrfg and sowb  it assumes that cursor initial position is 0,0 while margins may be different. I think that solution requires more than setting it to the cursor-initial-position or temporarily change margins.
