### ISSUE TITLE
"Accepting With List Pane View" demo hangs

### ISSUE THREAD

**Issue by scymtym** [McCLIM/McCLIM#739]
## Steps to reproduce

1. `(clim-demo:demodemo)`

2. Select "Accepting Values Test"

3. Select "Accepting With List Pane View"

## Expected behavior

A working list pane for accepting values should appear in the bottom stream pane (I think).

## Actual behavior

Nothing appears and both stream panes become unresponsive. Scrollbars and other gadgets still respond visually.

Canceling the command with `C-c` causes an error

```
#<DREI:DREI-AREA TEXTUAL-DREI-SYNTAX-VIEW {1004810783}> is not contained in #<CLIM-CLX::|CLX-736-CLIM:INTERACTOR-PANE| CLIM-DEMO::INTERACTOR {1009CC7013}>.
```

to be signaled.

**Comment by dkochmanski** [comment]
I can't reproduce the problem locally, could you confirm that it is fixed?

**Comment by scymtym** [comment]
Can't reproduce now (with ff2d0a79) either. Maybe the problem was fixed accidentally by some other change.
