### ISSUE TITLE
make-clim-stream: space value is not based on inner stream

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#742]
Steps to reproduce:

Compile the following:
```
(in-package #:clim-user)
(define-application-frame bug-xxx () ()
  (:pane :application  :width '(64 :character) :height '(16 :line)))
(run-frame-top-level (make-application-frame 'bug-xxx))
```

Expected: single pane of width 64x16
Observed:
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM:STREAM-LINE-HEIGHT (2)>
when called with arguments
  (#<CLIM-CLX::CLX-876-BORDER-PANE "(Unnamed Pane)" {10066E0933}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]
```

The issue is caused by the fact that application-pane is wrapped in bordered pane and scrolling pane, if we add `:borders nil :scroll-bars nil` debugger won't be invoked and application will start without a problem. That said it is only a symptom.

`width` and `height` are passed to the border (or scroller) pane instead of the inner application pane, so during compose-space user-specified options are merged against one of the panes upon creation. That calls in turn `spacing-vaue-to-device-units`:

```
(defmethod spacing-value-to-device-units (pane x)
  (cond ((realp x) x)
        ((consp x)
         (ecase (cadr x)
           (:pixels (car x))
           (:point  (* (car x) (graft-pixels-per-inch (graft pane)) 1/72))
           (:mm     (* (car x) (graft-pixels-per-millimeter (graft pane))))
           (:character (* (car x) (text-style-character-width (pane-text-style pane)
                                                               (sheet-medium pane)
                                                               #\m)))
           (:line  (* (car x)
                      (stream-line-height pane)))))))
```

`:line` option depends on stream having line-height and of course bordered-pane doesn't have it. Arguably that should depend on `text-style-height` (think about tit in this ticket!). `:width` "just" passes because even bordered-pane seems to have text-style associated with it, but that is equally wrong.

Here comes `make-clim-stream-pane`:
```
(defun make-clim-stream-pane (&rest options
                              &key (type 'clim-stream-pane)
                                (scroll-bar :vertical)
                                (scroll-bars scroll-bar)
                                (borders t)
                                &allow-other-keys)
  (with-keywords-removed (options (:type :scroll-bar :scroll-bars :borders))
    ;; The user space requirement options belong to the scroller ..
    (let* ((space-keys '(:width :height :max-width :max-height
			 :min-width :min-height))
	   (user-sr nil)
	   (pane-options nil))
      (loop  for (key value) on options by #'cddr
         if (and (member key space-keys :test #'eq)
                 (not (eq value :compute)))
         nconc (list key value) into space-options
         else
         nconc (list key value) into other-options
         end
         finally (progn
                   (setq user-sr space-options)
                   (setq pane-options other-options)))
      (let* ((pane (apply #'make-pane type (append pane-options
						   (unless (or scroll-bars
							       borders)
						     user-sr))))
	     (stream pane))
	(when scroll-bars
	  (setq pane (apply #'make-pane 'scroller-pane
			    :scroll-bar scroll-bars
			    :contents (list (make-pane 'viewport-pane
						       :contents (list pane)))
			    (unless borders
			      user-sr))))
	(when borders
	  (setq pane (apply #'make-pane 'border-pane
                            :border-width (if (not (numberp borders))
                                              1
                                              borders)
                            :contents (list pane)
                            user-sr)))
	(values pane stream)))))
```

notice, that user-sr (that is user-space-request) is carefully carried to the outermost pane, so this issue is introduced purposefully to attain required size of the "whole pack", otherwise overall pane would be bigger with innermost having the requested size. IMO that would be a correct behavior, I'm asking about the viewport and borders and scroll-bars are just decorations.

**Comment by dkochmanski** [comment]
as @lokedhs  pointed out one of space options should be called `:pixel`, not `:pixels`. See `formatting-table` for the reference. Name should be simply changed since it is default unit and we do not advertise incorrect version anywhere.

**Comment by kc-** [comment]
> notice, that user-sr (that is user-space-request) is carefully carried to the outermost pane, so this issue is introduced purposefully to attain required size of the "whole pack", otherwise overall pane would be bigger with innermost having the requested size. IMO that would be a correct behavior, I'm asking about the viewport and borders and scroll-bars are just decorations.

In my opinion, space requirements a user specifies for an application pane should correspond to the outermost border of that pane, including decorations and scrollbars. Your commit 06b469aa mitigates this issue by looking through all `sheet-children` and obtaining the maximum value for `:character` or `:line` requests.

We discussed this on IRC, and you opined that there should only be one set of space keyword parameters, so one behaviour should be chosen. In that case, my vote is for the current behaviour to be considered correct.
