### ISSUE TITLE
Loss of command table on redefining application frame

### ISSUE THREAD

**Issue by heshrobe** [McCLIM/McCLIM#751]
If you have defined an application frame with a command table, then define commands for that application and then redefine the application-frame (e.g. when working with slime) then you lose all the commands.

The fix to this is straightforward: In the macro-expansion of define-application-frame, you always generate this form: (clim:define-command-table <table-name>).  This should be changed to (unless (clim:find-command-table <table-name> :errorp nil) (clim:define-command-table <table-name>))

**Comment by dkochmanski** [comment]
I'm not sure if we are allowed to that according to the spec: http://bauhh.dyndns.org:8000/clim-spec/28-2.html#_1480

```
:command-table name-and-options, where name-and-options is a list consisting of the name of the application frame's command table followed by some keyword-value pairs. The keywords can be :inherit-from or :menu (which are as in define-command-table). The default is to create a command table with the same name as the application frame. 
```

**Comment by heshrobe** [comment]
I think the spec is silent on the issue of what happens when an application-frame is redefined.  II can look at the original CLIM’s implementation to see what it does.  But it definitely had the behavior of not losing the menu items in the command table on redefinition of the application-frame.  The code might need to be more complicated than my suggestion due to the options part.  If the options change, maybe the implication is that you’d need to make a new command table.  The core point for me was that losing my menu items when I redefine an application-frame during development is a major pain in the posterior.

> On Apr 10, 2019, at 12:25, Daniel Kochmanski <notifications@github.com> wrote:
> 
> I'm not sure if we are allowed to that according to the spec: http://bauhh.dyndns.org:8000/clim-spec/28-2.html#_1480
> 
> :command-table name-and-options, where name-and-options is a list consisting of the name of the application frame's command table followed by some keyword-value pairs. The keywords can be :inherit-from or :menu (which are as in define-command-table). The default is to create a command table with the same name as the application frame. 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by heshrobe** [comment]
On further consideration, this really comes to what the behavior of define-comand-table is.  Define-application-frame simply generates a call to define-command-table with all the arguments provided.  

What define-command-table ought to do then is check whether there’s an existing command-table and if so use it but update any fields that are specified in the current invocation of define-command-table.  If there’s no existing table then you just make the new one.  This is the behavior of the original CLIM implementation.

> On Apr 10, 2019, at 12:25, Daniel Kochmanski <notifications@github.com> wrote:
> 
> I'm not sure if we are allowed to that according to the spec: http://bauhh.dyndns.org:8000/clim-spec/28-2.html#_1480
> 
> :command-table name-and-options, where name-and-options is a list consisting of the name of the application frame's command table followed by some keyword-value pairs. The keywords can be :inherit-from or :menu (which are as in define-command-table). The default is to create a command table with the same name as the application frame. 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by heshrobe** [comment]
And on further investigation, it’s the macro-expansion of define-command-table that’s at fault:

(defmacro define-command-table (name &key inherit-from menu inherit-menu)
  `(let ((old-table (gethash ',name *command-tables* nil))
	 (inherit-from-arg (or ',inherit-from '(global-command-table))))
     (if old-table
	 (with-slots (inherit-from menu) old-table
	   (setq inherit-from inherit-from-arg
		 menu (menu-items-from-list ',menu))
	   old-table)
   …

If you don’t provide a menu keyword argument, then it will null out the menu in the existing command table.  

I think this code would be better:

(defmacro define-command-table (name &key inherit-from (menu nil menu-supplied-p) inherit-menu)
  `(let ((old-table (gethash ',name *command-tables* nil))
	 (inherit-from-arg (or ',inherit-from '(global-command-table))))
     (if old-table
	 (with-slots (inherit-from menu) old-table
	   (setq inherit-from inherit-from-arg)
	   (when ,menu-supplied-p
	     (setq menu (menu-items-from-list ',menu)))
	   old-table)
	 (make-command-table ',name
			     :inherit-from inherit-from-arg
                             :inherit-menu ,inherit-menu
			     :menu ',menu
			     :errorp nil))))


> On Apr 10, 2019, at 13:09, Howard Shrobe <hes@csail.mit.edu> wrote:
> 
> On further consideration, this really comes to what the behavior of define-comand-table is.  Define-application-frame simply generates a call to define-command-table with all the arguments provided.  
> 
> What define-command-table ought to do then is check whether there’s an existing command-table and if so use it but update any fields that are specified in the current invocation of define-command-table.  If there’s no existing table then you just make the new one.  This is the behavior of the original CLIM implementation.
> 
>> On Apr 10, 2019, at 12:25, Daniel Kochmanski <notifications@github.com> wrote:
>> 
>> I'm not sure if we are allowed to that according to the spec: http://bauhh.dyndns.org:8000/clim-spec/28-2.html#_1480
>> 
>> :command-table name-and-options, where name-and-options is a list consisting of the name of the application frame's command table followed by some keyword-value pairs. The keywords can be :inherit-from or :menu (which are as in define-command-table). The default is to create a command table with the same name as the application frame. 
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> Howard Shrobe
> 
> Principal Research Scientist and
> Director CyberSecurity@CSAIL
> MIT Computer Science and Artificial Intelligence Laboratory
> hes@csail.mit.edu
> 617-253-7877 work
> 617-312-6439 cell
> 
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
that makes sense. also, looking at the code I think that inherit-from argument is also mishandled, especially due to phrasing: `If no inheritance is specified, the command table will be made to inherit from CLIM's global command table. ` - I read it that it is possible to specify inheritance to NIL (so it should be handled the same way as you propose for the menu).

I imagine it as something like this (not tested):

```common-lisp
(defmacro define-command-table (name &key (inherit-from nil inherit-supplied-p)
                                          (menu nil menu-supplied-p)
                                          inherit-menu)
  `(let ((old-table (gethash ',name *command-tables* nil))
	 (inherit-from-arg (or ',inherit-from '(global-command-table))))
     (if old-table
         (with-slots (inherit-from menu) old-table
           ,(if inherit-supplied-p
                `(setq inherit-from ',inherit-from)
                `(setq inherit-from '(global-command-table)))
           ,(when menu-supplied-p
              `(setq menu (menu-items-from-list ',menu)))
           old-table)
         (make-command-table ',name
			     :inherit-from ,(if inherit-supplied-p
                                                `',inherit-from
                                                `'(global-command-table))
                             :inherit-menu ,inherit-menu
			     :menu ',menu
			     :errorp nil))))
```

please make a pull request with a change and if nobody else get to it before me I'll test it and merge it *after* I'm done with peer reviewing a big pull request with clipboard changes.

thank you!

**Comment by heshrobe** [comment]
I’ll do that as soon as I can (hopefully tomorrow). Your additions to my additions look right.

> On Apr 10, 2019, at 17:04, Daniel Kochmanski <notifications@github.com> wrote:
> 
> that makes sense. also, looking at the code I think that inherit-from argument is also mishandled, especially due to phrasing: If no inheritance is specified, the command table will be made to inherit from CLIM's global command table. - I read it that it is possible to specify inheritance to NIL (so it should be handled the same way as you propose for the menu).
> 
> I imagine it as something like this (not tested):
> 
> (defmacro define-command-table (name &key (inherit-from nil
>  inherit-supplied-p)
>                                           (menu 
> nil
>  menu-supplied-p)
>                                           inherit-menu)
>   `(
> let ((old-table (gethash ',name *command-tables* nil
> ))
> 	 (inherit-from-arg (
> or
>  ',inherit-from '(global-command-table))))
>      (
> if
>  old-table
>          (with-slots (inherit-from menu) old-table
>            ,(
> if
>  inherit-supplied-p
>                 `(
> setq
>  inherit-from ',inherit-from)
>                 `(
> setq
>  inherit-from '(global-command-table)))
>            ,(
> when
>  menu-supplied-p
>               `(
> setq
>  menu (menu-items-from-list ',menu)))
>            old-table)
>          (make-command-table ',name
> 			     :inherit-from ,(
> if
>  inherit-supplied-p
>                                                 `',inherit-from
>                                                 `'(global-command-table))
>                              :inherit-menu ,inherit-menu
> 			     :menu ',menu
> 			     :errorp 
> nil))))
> please make a pull request with a change and if nobody else get to it before me I'll test it and merge it after I'm done with peer reviewing a big pull request with clipboard changes.
> 
> thank you!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
maybe it is worth to make 
`&key (inherit-from '(global-command-table) inherit-supplied-p)` for clarity
also inherit-from-arg could be safely removed now, and in that case
whole if could be replaced with
`(setq inherit-from ',inherit-from)` ;(because of default value)

**Comment by heshrobe** [comment]
In other projects this has been the process:
1) Create a branch with the fix
2) Make the updates
3) Push it to GitHub
4) Submit the pull request.

Unfortunately, I don’t have the permissions to push my branch to the repo.  


> 
> please make a pull request with a change and if nobody else get to it before me I'll test it and merge it after I'm done with peer reviewing a big pull request with clipboard changes.
> 
> thank you!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
it is almost the same in this case:
1. create a fork
2. clone your forked repository
3. make the updates (directly in master branch if you prefer to)
4. push it to github
4. submit the pull request

**Comment by heshrobe** [comment]
I just checked the clim user’s guide and the clim 2 spec both of  which says that define-command-table takes 3 keyword arguments as we currently have it.
You’re right that this is probably unnecessary but I don’t want to violate the spec gratuitously.  I’ll submit the pull request for this issue in a minute or two.

> On Apr 11, 2019, at 03:04, Daniel Kochmanski <notifications@github.com> wrote:
> 
> maybe it is worth to make
> &key (inherit-from '(global-command-table) inherit-supplied-p) for clarity
> also inherit-from-arg could be safely removed now, and in that case
> whole if could be replaced with
> (setq inherit-from ',inherit-from) ;(because of default value)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


> On Apr 10, 2019, at 17:04, Daniel Kochmanski <notifications@github.com> wrote:
> 
> that makes sense. also, looking at the code I think that inherit-from argument is also mishandled, especially due to phrasing: If no inheritance is specified, the command table will be made to inherit from CLIM's global command table. - I read it that it is possible to specify inheritance to NIL (so it should be handled the same way as you propose for the menu).
> 
> I imagine it as something like this (not tested):
> 
> (defmacro define-command-table (name &key (inherit-from nil
>  inherit-supplied-p)
>                                           (menu 
> nil
>  menu-supplied-p)
>                                           inherit-menu)
>   `(
> let ((old-table (gethash ',name *command-tables* nil
> ))
> 	 (inherit-from-arg (
> or
>  ',inherit-from '(global-command-table))))
>      (
> if
>  old-table
>          (with-slots (inherit-from menu) old-table
>            ,(
> if
>  inherit-supplied-p
>                 `(
> setq
>  inherit-from ',inherit-from)
>                 `(
> setq
>  inherit-from '(global-command-table)))
>            ,(
> when
>  menu-supplied-p
>               `(
> setq
>  menu (menu-items-from-list ',menu)))
>            old-table)
>          (make-command-table ',name
> 			     :inherit-from ,(
> if
>  inherit-supplied-p
>                                                 `',inherit-from
>                                                 `'(global-command-table))
>                              :inherit-menu ,inherit-menu
> 			     :menu ',menu
> 			     :errorp 
> nil))))
> please make a pull request with a change and if nobody else get to it before me I'll test it and merge it after I'm done with peer reviewing a big pull request with clipboard changes.
> 
> thank you!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by heshrobe** [comment]
I just checked the clim user’s guide and the clim 2 spec both of  which says that define-command-table takes 3 keyword arguments as we currently have it.
You’re right that this is probably unnecessary but I don’t want to violate the spec gratuitously.  I’ll submit the pull request for this issue in a minute or two.

> On Apr 11, 2019, at 03:04, Daniel Kochmanski <notifications@github.com> wrote:
> 
> maybe it is worth to make
> &key (inherit-from '(global-command-table) inherit-supplied-p) for clarity
> also inherit-from-arg could be safely removed now, and in that case
> whole if could be replaced with
> (setq inherit-from ',inherit-from) ;(because of default value)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
```common-lisp
(defmacro define-command-table (name &key (inherit-from '(global-command-table)) 
                                          (menu nil menu-supplied-p)
                                          inherit-menu)
  `(if-let ((old-table (gethash ',name *command-tables* nil)))
     (with-slots (inherit-from menu) old-table
       (setq inherit-from ',inherit-from)
       ,(when menu-supplied-p
          `(setq menu (menu-items-from-list ',menu)))
       old-table)
     (make-command-table ',name
			 :inherit-from ',inherit-from
                         :inherit-menu ,inherit-menu
			 :menu ',menu
			 :errorp nil)))
```

above version accepts three keyword arguments, it just removes probing if inherit-from was supplied (because we simply use default value). also (looking at the pull request) - please use if-let, it is a macro used in codebase and it reduces code verbosity

**Comment by heshrobe** [comment]
This looks OK to me.  You’re right that we don’t need the supplied-p argument for inherit-from.

> On Apr 23, 2019, at 06:09, Daniel Kochmanski <notifications@github.com> wrote:
> 
> (defmacro define-command-table
>  (name &key (inherit-from '(global-command-table)) 
>                                           (menu 
> nil
>  menu-supplied-p)
>                                           inherit-menu)
>   `(
> if-let ((old-table (gethash ',name *command-tables* nil
> )))
>      (with-slots (inherit-from menu) old-table
>        (
> setq
>  inherit-from ',inherit-from)
>        ,(
> when
>  menu-supplied-p
>           `(
> setq
>  menu (menu-items-from-list ',menu)))
>        old-table)
>      (make-command-table ',name
> 			 :inherit-from ',inherit-from
>                          :inherit-menu ,inherit-menu
> 			 :menu ',menu
> 			 :errorp 
> nil)))
> above version accepts three keyword arguments, it just removes probing if inherit-from was supplied (because we simply use default value). also (looking at the pull request) - please use if-let, it is a macro used in codebase and it reduces code verbosity
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell
