### ISSUE TITLE
postscript regression: can't start due to page margins

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#753]
Postscript-script inherits from standard-extended-output-stream. During initialize instance we have:

1. create instance
2. call page-region :after method (which indirectly queries medium because region is +everywhere+
3. call permanent-medium-mixin :after method which sets the medium

but in 2. we call text-tyle-width, which needs access to medium - nil is returned, so there is call to (port nil), what yields a condition. problem is masked for seos because seos always have a bound region, so this code branch is not triggered.

Steps to reproduce:
1.start drawing-tests
2. run test for postscript backend

**Comment by scymtym** [comment]
Fixed in 268f2d19c.
