### ISSUE TITLE
command-menu pane initially displays wrong

### ISSUE THREAD

**Issue by heshrobe** [McCLIM/McCLIM#754]
In an application frame, with command menu whose display function is clim:display-command-menu: Initially the frame displays incorrectly with the command menu items text printing vertically and overwriting the pane above the menu.

You can get the same behavior by calling 
(redisplay-frame-pane <application-frame> <menu-pane> :force-p t).  

You can then get the display correct by issuing any command in the application-frame or by 
by (redisplay-frame-pane <application-frame> <menu-pane> :force-p nil).  

I've done enough poking around to determine that display-comand-menu eventually calls formatting-item-list and that in  the output-record hierarchy produced by this the text-records consist of a sequence of one-character records whose x remains 0 and whose y increases (i.e. it's writing the string vertically).  

I'm not sure what's causing this.

**Comment by dkochmanski** [comment]
That's what most probably is happening:

- space allocation protocol is invoked too late (see #748), only after initial display
- menu pane width is 0 and end-of-line-action is `:wrap`, so to prevent infinite recursion it wraps after at least one character printed

**Comment by dkochmanski** [comment]
workaround would be ensuring, that eol-action is `:allow`, proper fix requires reviewing space allocation code flow and fixing that.

**Comment by heshrobe** [comment]
Thanks Daniel,

Sort of what I thought vaguely.  I’ll look more into it more (once I’m less frustrated).

> On Apr 13, 2019, at 12:50, Daniel Kochmanski <notifications@github.com> wrote:
> 
> That's what most probably is happening:
> 
> 	• space allocation protocol is invoked too late (see #748), only after initial display
> 	• menu pane width is 0 and end-of-line-action is :wrap, so to prevent infinite recursion it wraps after at least one character printed
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by heshrobe** [comment]
I've spent a lot of time trying to narrow the problem down.  Here's a much more succinct description:

Redipslay-frame-pane calls window-clear (if :force-p is t).

Window-clear on the command-menu-pane leaves the mirror-region of the pane set to x 0:1 y 0:1.

At that point trying to do output wraps after the first character.  Here's a simple test case:

(clim:window-clear <command-menu-pane>)
(write-string "Foobar" <comand-menu-pane>)

Doing the same thing on an application pane or an interaction pane  does not leave the mirror-region in this state.

I'll investigate more when I have time.

**Comment by heshrobe** [comment]
One more observation:
the last few lines of window-clear are: 
 (setf (stream-width pane) 0)
  (setf (stream-height pane) 0)
  (scroll-extent pane 0 0)
  (change-space-requirements pane)

Change-space-requirements goes through a complicated path of method invocation which are different for command-menu-panes and application (or listener) panes.

The first method just recursively calls change-space-requirements on sheet-parent of the pane.

This parent for command-menu-panes does not have viewport-pane as a superclass but the other pane types do.  The primary method is therefore different.  For command menu panes it's from layout-protocol-mixin but for the other panes its from viewport-pane.  The method for layout-protocol-mixin  recurses up to the top level sheet while the method for viewport-pane doesn't.

That's what leads to the different behavior.

**Comment by heshrobe** [comment]
One other related issue.  In the panes section of an application frame definition you can't specify the :borders option for a command-menu pane and although you can specify :scroll-bar it's ignored.  This is because the path for command-menu goes through make-pane, not make-clim-stream-pane (which removes the :borders option before calling make-pane) and deals with the :scroll-bar option

**Comment by heshrobe** [comment]
In summary, the root cause is that command-menu-panes are treated differently than other standard pane types.  The following code fixes this; I've highlighted the relevant lines:


;;; from panes
**(defun make-clim-command-menu-pane (&rest options)
  (apply #'make-clim-stream-pane :type 'command-menu-pane options))**

;;; from frames
(defun do-pane-creation-form (name form)
  (cond
    ;; Single form which is a function call
    ((and (= (length form) 1)
	  (listp (first form)))
     `(coerce-pane-name ,(first form) ',name))
    ;; Standard pane denoted by a keyword (i.e `:application')
    ((keywordp (first form))
     (case (first form)
       (:application `(make-clim-application-pane
                       :name ',name
                       ,@(cdr form)))
       (:interactor `(make-clim-interactor-pane
                      :name ',name ,@(cdr form)
                      ,@(cdr form)))
       (:pointer-documentation `(make-clim-pointer-documentation-pane
                                 :name ',name
                                 ,@(cdr form)))
       **(:command-menu `(make-clim-command-menu-pane
       			:name ',name
       			,@(cdr form)))**
       (otherwise `(make-pane ,(first form) :name ',name ,@(cdr form)))))
    ;; Non-standard pane designator fed to the `make-pane'
    (t `(make-pane ',(first form) :name ',name ,@(cdr form)))))

**Comment by dkochmanski** [comment]
fixed by #759
