### ISSUE TITLE
Implementation of (setf* pointer-position) and (setf* stream-pointer-position) 

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#768]
McCLIM doesn't implement the `(setf* pointer-position)` and  `(setf* stream-pointer-position)` that are in specification (sec. 22.4 and 22.2).

I think the implementation is not difficult but it is necessary to think well about coordinate convention for `pointer-position` (Discussion already made in issue #466) . 

Now in McCLIM `pointer-position` return the position in the coordinate system of the sheet that the pointer is currently over as stated in Franz manual.   

I find more logical that `pointer-position` return position in the coordinate system of the graft (as suggested in an annotation of clim specification). Using the pointer-sheet coordinate for `pointer-position` is also problematic because sometimes the pointer is not over a clim sheet and some sheets, like menu, are very volatile (this was a cause of bugs in scigraph when `stream-pointer-position` was based on `pointer-position`, solved with PR #468) .

If McCLIM want continue to adhere to Franz manual I think that it will be necessary to implement also the following functions present in Franz manual:
`pointer-native-position` and `pointer-set-native-position`  that return and set the pointer in the graft coordinate system.

**Comment by dkochmanski** [comment]
I'll answer quickly for the latter part: we are bound by CLIM II spec, Franz additions are considered extensions in my eyes. As of the rest of the issue I will attend to it not before I'm done with clipboard stuff.

**Comment by dkochmanski** [comment]
closing as per merge request
