### ISSUE TITLE
sheet-transformation problem

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#769]
With PR #691 the sheet-transformation of the t-l-s of a frame  moved off-screen it is not set to a translation with negative dx and/or dy, but to the identity-transformation.

This solves the bug reported in issue #499 but now the sheet-transformation is wrong, it is no more 
> the transformation that converts coordinates in the sheet sheet's coordinate system into coordinates in its parent's coordinate system

as stated in the clim specification.

The cause of the bug is explained by @scymtym  in the message of commit a894385 and it is 
that the translation with negative dx and dy was stored both in sheet-transformation and in the sheet-native-transformation.

So why don't store the translation only in the sheet-transformation and maintain the sheet-native-transformation to the identity?

**Comment by dkochmanski** [comment]
is there any visible behavior associated with this issue? if so, could you write steps to reproduce?

**Comment by admich** [comment]
There is no visible behavior associated with this issue because the wrong `sheet-transformation` is compensated with the `sheet-native-transformation`. 

I wrote a solution in PR #774
