### ISSUE TITLE
automatic-clx-server-path doesn't parse all conceivable paths correctly.

### ISSUE THREAD

**Issue by kc-** [McCLIM/McCLIM#783]
`automagic-clx-server-path` does not function properly unless there's a ':' in that string.

On my machine (macos with XQuartz), `$DISPLAY` is set to `computer-name.network-name`, and the fault leads to the `use-localhost` restart.

Since the `use-localhost` restart calls `parse-clx-server path` with the empty string as `:host` argument, so automagic-clx-server-path should accept the empty string when the environment variable DISPLAY is set to it, as well.

4ce5e0e fixes this.

**Comment by dkochmanski** [comment]
fixed by recent merge.
