### ISSUE TITLE
Error: No connection could be made because the target machine actively refused it. (error #10061) 

### ISSUE THREAD

**Issue by wislin** [McCLIM/McCLIM#799]
when I try in windows 10 allway get follow error:

? (clim-demo:demodemo)

    Error: No connection could be made because the target machine actively refused it. (error #10061) during attempt to connect to 127.0.0.1:6000:6000
    While executing: SOCKET-ERROR, in process listener(1).
    Type :POP to abort, :R for a list of available restarts.
    Type :? for other options.

How to resolve this error?

**Comment by scymtym** [comment]
Thank you for your report.

The error message looks like McCLIM is attempting to connect to an X server. Did you install and start an X server for Windows?

See [the Backends wiki page](https://github.com/McCLIM/McCLIM/wiki/Backends) for a description of available backends and how to configure them on different platforms.
