### ISSUE TITLE
defgeneric* miscompiles &key argument

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#802]
Person who takes this macro should also familiarize themselves with #96 and close both issues.

Steps to reproduce:

macroexpand:

```common-lisp
(defgeneric* (setf stream-pointer-position) (x y stream &key pointer))

(PROGN
 (DEFSETF STREAM-POINTER-POSITION (POINTER)
   (X Y STREAM &KEY)
   `(FUNCALL #','(SETF CLIM::.STREAM-POINTER-POSITION-STAR.) ,X ,Y ,STREAM
             ,&KEY ,POINTER))
 (DEFGENERIC (SETF CLIM::.STREAM-POINTER-POSITION-STAR.)
     (X Y STREAM &KEY POINTER)))
```

funcall is incorrect, because it takes `&key` at face value. That prevents implementation of the specified method `(setf stream-pointer-position)`. 

See also: http://bauhh.dyndns.org:8000/clim-spec/B-4.html#_1904

**Comment by bmansurov** [comment]
@dkochmanski,

[Here](https://github.com/McCLIM/McCLIM/blob/master/Core/clim-basic/extended-streams/encapsulate.lisp#L46) is a generic function lambda list parser that, I hope, can be re-used (with minor modifications) for this task. I wonder what the right way of using it though. Should that function be moved to somewhere else to indicate its use case in different places? Or is it better to create another function just for `defgeneric*`?

Another question I have is about the comment [here](http://bauhh.dyndns.org:8000/clim-spec/B-4.html#_1904):

> LAMBDA-LIST may also have &KEY values (definitely used), and presumably &OPTIONAL values or an &REST list. It might be better to say that the last REQUIRED argument in LAMBDA-LIST is intended to be class specialized. The same argument applies to DEFMETHOD*, below, as well. [edit]
-- Alastair Bridgewater 2011-03-30 22:36Z

Should I consider the "last REQUIRED argument" as the class specialized argument?

**Comment by dkochmanski** [comment]
yes, the point of defgeneric* is to be able to define methods like this:

```
(defmethod* (setf foo) (x y (p point) &key (coordinates :cartesian))
  (do-something p))
```

so it may be called like this:

```
(setf (foo my-point :coordinates :angular) (values x y))
```

where the method is dispatched on my-point.

regarding using the utility in the macro, how about the alexandria utility `parse-ordinary-lambda-list`, does it do the same thing as this CLIM utility you've found? maybe we could use it in both places.

**Comment by bmansurov** [comment]
@dkochmanski should I worry about the other generic function lambda list keywords (`&allow-other-keys`, `&optional`, and `&rest`) in this task?

**Comment by dkochmanski** [comment]
defgeneric* should work like an ordinary defgeneric with an additional feature of handling multiple-value setf. Also, part of this task will be writing some unit tests.
