### ISSUE TITLE
:default keyword in accept and command's arguments doesn't work with non standard presentation types

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#839]
If I define a presentation type (also implicitly with a defclass) and the I call accept with a default value, and then press RETURN the accept function return nil and not the default value.

for example in a clim-listener:

> CLIM-USER> (defclass new-class ()())
> CLIM-USER> (accept 'new-class :default (make-instance 'new-class))
> Enter new class[#<NEW-CLASS {100A03B193}>]: 
> 0  NIL
> 1  NEW-CLASS`

I had pressed Return at the accept prompt but the function return NIL.
There is the same problem  in commands with arguments with default.

**Comment by dkochmanski** [comment]
this is due to the fallback method at the bottom of input-editing.lisp. a working workaround is to redefine it to

```
(define-default-presentation-method accept
    (type stream (view textual-view) &key default (default-type type))
  (multiple-value-bind (result ptype)
      (accept-using-read stream type :read-eval t)
    (if (presentation-typep result ptype)
        (values result ptype)
        (values default default-type))))
```

I'm thinking about improving accept-using-read to actually signal a condition and try to handle it here and then use the default
