### ISSUE TITLE
button release results in spurious slider event firing

### ISSUE THREAD

**Issue by slyrus** [McCLIM/McCLIM#852]
In the latest HEAD (69371014), if I select a scroll bar, hold the mouse button down, move over to a slider and release the mouse button, I get an event firing on the slider, which isn't what I would expect. Sorry for not having a clean test case. If the broken behavior isn't obvious, I can try to generate one.

**Comment by dkochmanski** [comment]
There are a few things which need to be taken into consideration:

- when we drag something between sheets, then release-event should be delivered to the target sheet
- pressed sheet needs to receive release event for obvious reasons

what would be a desired behavior in that case? I'd say: slider should honor armed/unarmed state.

**Comment by dkochmanski** [comment]
fix pushed to branch and created a pull request.
