### ISSUE TITLE
climb:text-style-to-font there is no applicable method for ps/pdf/raster-image backends

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#854]
For the output only backends ps pdf and raster-image there isn't applicabe  method for the generic function `climb:text-style-to-font` that is called from generic function `climb:text-style-character-width`. Maybe it is not the only missing method. I have found the error trying to print a scigraph plot to a pdf file.

**Comment by lokedhs** [comment]
Do you have a way to reproduce this issue?

**Comment by admich** [comment]
I have found the problem with scigraph. For example you can try the slyrus scigraph demo:
https://github.com/slyrus/scigraph-demo
to reproduce the error.

**Comment by admich** [comment]
@lokedhs Here a very minimum code to reproduce the issue:
```
(in-package :clim-user)
(with-open-file (s "tmp.pdf"
                   :direction :output
                   :if-exists :supersede
                   :element-type '(unsigned-byte 8))
  (clim-pdf:with-output-to-pdf-stream (stream s)
    (let ((offset (stream-character-width stream #\M)))
      (draw-text* stream "TEXT" offset 100))))

```

**Comment by admich** [comment]
The problem was introduced by commit ee418f15 from which the `clx-fb` backend use the new font infrastructure in `Backends/font/fonts.lisp`. This commit redefined  the method `text-style-character-width`
```
(defmethod text-style-character-width (text-style medium char)
     (climb:font-character-width (text-style-to-font (port medium) text-style) char))
```
The pdf/ps/raster-image backends doesn't have a method for `text-style-to-font` (and maybe many other generics) and so produce errors.
The original unspecialized `text-style-character-width`, that would work with pd/pdf backends, is still in `clim-basic/decls.lisp` but overwritten by the new one.

So, there are several strategy to solve this bug:

1. specialize `text-style-to-font` (and maybe other generics) for ps/pdf/raster-image backends, in such a way that all the backends use the new common font infrastructure. This is the more elegant but more difficult.

2. specialize `text-style-character-width` for ps/pdf/raster-image medium in such a way that they don't use the standard (T T T) method.

3. Specialize in some way the defmethod of `text-style-character-width` present in `Backends/common/fonts.lisp` in such a way that it is used only from clx backends and the other use the standard version present in `clim-basic/decls.lisp`.

What do you think?

**Comment by admich** [comment]
Few reflections about `climb:text-style-to-font`. Seems to me that this is a replica of the clim-standard generic `text-style-mapping`: it has port and text-style as arguments and return a font. In McCLIM code  `climb:text-style-to-font` is used as front-end function (it is called from many functions, ps backend is an execpiton on this) and `climb:text-style-to-font` call `text-style-mapping` for caching. I think It will be better to remove `climb:text-style-to-font`, call directly `text-style-mapping` and for caching there are already `climi:port-text-style-mappings`.
