### ISSUE TITLE
accepting-values does not work in listener

### ISSUE THREAD

**Issue by nsrahmad** [McCLIM/McCLIM#859]
`accepting-values` itself work fine in demodemo. When I try to run a command in `clim-listener` without giving any arguments (e.g `,run⏎`), I get:
```lisp
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)>
when called with arguments
  (#<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [ABORT] Return to application command loop.
 2: [RETRY] Retry SLIME REPL evaluation request.
 3: [*ABORT] Return to SLIME's top level.
 4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1005899BC3}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)> #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>) [fast-method..
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)> (#<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>))
  2: ((FLET CLIM-INTERNALS::DO-ACCEPT-PRESENT-DEFAULT :IN STREAM-ACCEPT) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>)
  3: ((FLET "CONTINUATION44" :IN STREAM-ACCEPT) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>)
  4: ((FLET "CONTINUATION12" :IN CLIM-INTERNALS::INVOKE-FORMATTING-CELL) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>)
  5: ((FLET CLIM-INTERNALS::DO-IT :IN CLIM-EXTENSIONS:INVOKE-WITH-TEMPORARY-PAGE))
  6: ((:METHOD CLIM-EXTENSIONS:INVOKE-WITH-TEMPORARY-PAGE (STANDARD-ENCAPSULATING-STREAM T)) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}> #<CLOSURE (FLET "CONTINUATION12" :IN CLIM-INTERNALS::INV..
  7: ((LAMBDA (STREAM CLIM-INTERNALS::RECORD) :IN CLIM-INTERNALS::INVOKE-FORMATTING-CELL) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}> #<unused argument>)
  8: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}> #<CLOSURE (LAMBDA (CLIM-INTERNALS::INNER-STR..
  9: ((FLET "CONTINUATION42" :IN STREAM-ACCEPT) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}> #<unused argument>)
 10: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}> #<CLOSURE (LAMBDA (CLIM-INTERNALS::INNER-STR..
 11: ((:METHOD STREAM-ACCEPT (CLIM-INTERNALS::ACCEPTING-VALUES-STREAM T)) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}> STRING :PROMPT "Command" :QUERY-IDENTIFIER #:COMMAND-PROMPT-ID13) [fast-met..
 12: (ACCEPT STRING :STREAM #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}> :PROMPT "Command" :QUERY-IDENTIFIER #:COMMAND-PROMPT-ID13)
 13: ((FLET "ACCEPTING-VALUES-CONTINUATION38" :IN CLIM-LISTENER::COM-RUN%PARTIAL%2660) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {100B257D03}>)
 14: ((LABELS #:.CONT.46 :IN CLIM-INTERNALS::INVOKE-ACCEPTING-VALUES) #<unused argument>)
 15: ((FLET "CONTINUATION14" :IN CLIM-INTERNALS::INVOKE-FORMATTING-TABLE) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}>)
 16: ((:METHOD INVOKE-WITH-OUTPUT-RECORDING-OPTIONS (OUTPUT-RECORDING-STREAM T T T)) #<CLIM-CLX::CLX-831-LISTENER-INTERACTOR-PANE CLIM-LISTENER::INTERACTOR {100B0538F3}> #<CLOSURE (FLET "CONTINUATION14" :I..
 17: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (MEDIUM T T)) #<CLIM-CLX:CLX-RENDER-MEDIUM {100B054193}> #<CLIM-CLX:CLX-RENDER-MEDIUM {100B054193}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS..
 18: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS (MEDIUM T)) #<CLIM-CLX:CLX-RENDER-MEDIUM {100B054193}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN INVOKE-WITH-DRAWING-OPTIONS) {7FCEC30B360B}>) ..
 19: ((LABELS #:G5 :IN INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX:CLX-RENDER-MEDIUM {100B054193}>)
 --more--
```

**Comment by admich** [comment]
I think this is related to a similar issue that I have if I try to provide the arguments of a command not in line but pressing `RETURN`. For example in Address Book demo if i write Describe in the interactor and the press `RETURN` I have the following error:

> There is no applicable method for the generic function
>   #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)>
> when called with arguments
>   (#<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>).
>    [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
> See also:
>   Common Lisp Hyperspec, 7.6.6 [:section]
> 
> Restarts:
>  0: [RETRY] Retry calling the generic function.
>  1: [ABORT] Return to application command loop.
>  2: [ABORT] Return to application command loop.
>  3: [RETRY] Retry SLIME REPL evaluation request.
>  4: [*ABORT] Return to SLIME's top level.
>  5: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {1002086943}>)
> 
> Backtrace:
>   0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)> #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>) [fast-method]
>   1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CLIM:ENCAPSULATING-STREAM-STREAM (1)> (#<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>))
>   2: ((FLET CLIM-INTERNALS::DO-ACCEPT-PRESENT-DEFAULT :IN CLIM:STREAM-ACCEPT) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>)
>   3: ((FLET "CONTINUATION44" :IN CLIM:STREAM-ACCEPT) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>)
>   4: ((FLET "CONTINUATION12" :IN CLIM-INTERNALS::INVOKE-FORMATTING-CELL) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>)
>   5: ((FLET CLIM-INTERNALS::DO-IT :IN CLIM-EXTENSIONS:INVOKE-WITH-TEMPORARY-PAGE))
>   6: ((:METHOD CLIM-EXTENSIONS:INVOKE-WITH-TEMPORARY-PAGE (CLIM:STANDARD-ENCAPSULATING-STREAM T)) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}> #<CLOSURE (FLET "CONTINUATION12" :IN CLIM-INTERNALS..
>   7: ((LAMBDA (STREAM CLIM-INTERNALS::RECORD) :IN CLIM-INTERNALS::INVOKE-FORMATTING-CELL) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}> #<unused argument>)
>   8: ((:METHOD CLIM:INVOKE-WITH-NEW-OUTPUT-RECORD (CLIM:OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}> #<CLOSURE (LAMBDA (CLIM-INTERNALS::INNER-STREA..
>   9: ((FLET "CONTINUATION42" :IN CLIM:STREAM-ACCEPT) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}> #<unused argument>)
>  10: ((:METHOD CLIM:INVOKE-WITH-NEW-OUTPUT-RECORD (CLIM:OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}> #<CLOSURE (LAMBDA (CLIM-INTERNALS::INNER-STREA..
>  11: ((:METHOD CLIM:STREAM-ACCEPT (CLIM-INTERNALS::ACCEPTING-VALUES-STREAM T)) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}> CLIM:EXPRESSION :PROMPT "object" :QUERY-IDENTIFIER #:COMMAND-PROMPT-ID..
>  12: (CLIM:ACCEPT CLIM:EXPRESSION :STREAM #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}> :PROMPT "object" :QUERY-IDENTIFIER #:COMMAND-PROMPT-ID12)
>  13: ((FLET "ACCEPTING-VALUES-CONTINUATION28" :IN CLIM-INTERNALS::COM-DESCRIBE%PARTIAL%32) #<CLIM-INTERNALS::ACCEPTING-VALUES-STREAM {1003D75383}>)
>  14: ((LABELS #:.CONT.46 :IN CLIM-INTERNALS::INVOKE-ACCEPTING-VALUES) #<unused argument>)
>  15: ((FLET "CONTINUATION14" :IN CLIM-INTERNALS::INVOKE-FORMATTING-TABLE) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}>)
>  16: ((:METHOD CLIM:INVOKE-WITH-OUTPUT-RECORDING-OPTIONS (CLIM:OUTPUT-RECORDING-STREAM T T T)) #<CLIM-CLX::CLX-5957-INTERACTOR-PANE CLIM-DEMO::INTERACTOR {10034F87B3}> #<CLOSURE (FLET "CONTINUATION14" :IN ..
>  17: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (CLIM:MEDIUM T T)) #<CLIM-CLX:CLX-RENDER-MEDIUM {10034F9013}> #<CLIM-CLX:CLX-RENDER-MEDIUM {10034F9013}> #<CLOSURE (FLET CLIM-INTERNALS::GRA..
>  18: ((:METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS (CLIM:MEDIUM T)) #<CLIM-CLX:CLX-RENDER-MEDIUM {10034F9013}> #<CLOSURE (FLET CLIM-INTERNALS::GRAPHICS-OP :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) {7F963B..
>  19: ((LABELS #:G5 :IN CLIM:INVOKE-WITH-DRAWING-OPTIONS) #<CLIM-CLX:CLX-RENDER-MEDIUM {10034F9013}>)
>  --more--
> 
So the problem seems not specific of `clim-listener` but of `interactor-pane`.
