### ISSUE TITLE
elliptical-thing: change internal representation

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#884]
Currently we represent ellipses as their center and transformation from polar coordinates. This approach is suboptimal for a few reasons:

- approximation errors which are proportional to the ellipses radii,
- radii is not in any kind of canonical form (algorithms complexity grows)
- most (not all) of the region protocol methods assume some kind of canonical form, so we convert it to the "simplified representation" over and over again - that takes time, also simplified representation has approximation issue with radii, so they must be computed again neverless
- transforming such region sometimes leads to `irreversible transformation` error, that is especially visible when output recording comes into play

I propose the representation resembling "simplified representation" which coincidentally is similar to what SVG *and* cl-vectors do. Elliptical thing should be represented as:

- center point
- xy-axis aligned radii (canonicalized)
- start/end angle
- rotation transformation
- (optionally) polar->native transformation for methods which are more performant using that

**Comment by dkochmanski** [comment]
Thank you for the feedback.

elliptical-thing is a base class for both standard-ellipse and standard-elliptical-arc (both are regions). Operations on said regions are described in a geometry substrate (region protocols). Also there is draw-design.

- why would we need two focus points?
- by xy-axis aligned radii I mean the length of semi-minor and semi-major axes, why would we need to keep the length of the major axis?

**Comment by admich** [comment]
Because the ellipse can be defined from the two focus and from the major axis so all can be calculated only from these 5 numbers. For example a point is inside the ellipse if the sum of the distance between it and the two focus points is less than the major axis.

**Comment by dkochmanski** [comment]
the new representation is already merged to master.
