### ISSUE TITLE
Numpad numbers don't work

### ISSUE THREAD

**Issue by goose121** [McCLIM/McCLIM#892]
It seems that McCLIM won't recognize numbers entered on the numpad as characters, due to `xlib:keysym->character` returning `nil` for them, so they don't show up when typed. I'm not sure if this is CLIM's issue or CLX's, as I'm not sure whether or not that function should return a character for those keysyms, so thoughts on that would be appreciated.

**Comment by dkochmanski** [comment]
related to: https://github.com/McCLIM/McCLIM/issues/35
please also see references to the clx repository.

**Comment by goose121** [comment]
Oh yeah, this does seem related; any fix to that issue would probably end up addressing this one as a consequence. Also, I think that this particular issue falls under sharplispers/clx#119, so I'm going to close it here since it duplicates that one and any code to fix it probably wouldn't belong in McCLIM.
