### ISSUE TITLE
print-object methods don't handle unbound slots

### ISSUE THREAD

**Issue by pouar** [McCLIM/McCLIM#915]
this breaks printing the prototype which breaks Sly (alternative SLIME implementation) when it tries to show the prototype in the inspector. Want me to open a PR that uses slot-boundp everywhere where a print-object method is defined? Might take a while to write it.

**Comment by nsrahmad** [comment]
>Want me to open a PR that uses slot-boundp everywhere

I suspect that would not be required as the problem might be with Sly. An inspector should not have any difficulty showing unbound slots. Please try whatever you are doing in SLIME, and see if you have problems.

P.S if you do have further problems, at least show the error with backtrace.

**Comment by pouar** [comment]
seems to work in Slime

**Comment by pouar** [comment]
how would this be handled? because I tried wrapping it in ignore-errors and it still came up, or does this need to be handled on the elisp side?

**Comment by pouar** [comment]
was wondering if I could patch it myself

**Comment by pouar** [comment]
opened the bug here
https://github.com/joaotavora/sly/issues/287

**Comment by joaotavora** [comment]
It was indeed a problem in SLY, I believe I just fixed it, please try out the latest master.

**Comment by pouar** [comment]
tried it, it works
