### ISSUE TITLE
Unhandled memory fault at #x0. on macOS

### ISSUE THREAD

**Issue by jimka2001** [McCLIM/McCLIM#918]
I'm trying to run a program which uses mccclim on macOS.   I'm not even sure whether this is a supported archecture.    I've tried with mcclim quicklisp version and also latest version and in both cases I get 'Unhandled memory fault at #x0.'

I'm trying to run the `app-main` sample program from the following code
```lisp
(defpackage "APP"
  (:use :clim :clim-lisp)
  (:export "APP-MAIN"))

(in-package :app)

(define-application-frame superapp ()
  ()
  (:panes
   (int :interactor :height 400 :width 600))
  (:layouts
   (default int)))

(defun app-main ()
  (run-frame-top-level (make-application-frame 'superapp)))

(setf mcclim-truetype:*truetype-font-path* #p"/Library/fonts/")

(app-main)
```

Unhandled memory fault at #x0.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [CLEAR-PANE-TRY-AGAIN] Clear the output history of the pane and reattempt forceful redisplay
 1: [CLEAR-PANE] Clear the output history of the pane, but don't redisplay
 2: [SKIP-REDISPLAY] Skip this redisplay
 3: [ABORT] Return to application command loop
 4: [RETRY] Retry SLIME REPL evaluation request.
 5: [*ABORT] Return to SLIME's top level.
 --more--

Backtrace:
  0: (CLIM-INTERNALS::INVOKE-DISPLAY-FUNCTION #<SUPERAPP {1006938233}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}>)
  1: ((FLET "UPDATING-OUTPUT-CONTINUATION41" :IN REDISPLAY-FRAME-PANE) #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}>)
  2: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> #<CLOSURE (FLET "CONTINUATION12" :IN CLIM-INTERNALS::%INVOKE-UPDATING) {665..
  3: (CLIM-INTERNALS::%INVOKE-UPDATING #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  CLIM-INTERNALS::TOP-LEVEL {1007350D73}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> #<CLOSURE..
  4: ((FLET "CONTINUATION46" :IN INVOKE-UPDATING-OUTPUT) #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0d0:0.0d0 Y 0.0d0:0.0d0  CLIM-INTERNALS::TOP-LEVEL {1007..
  5: ((:METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)) #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> #<CLOSURE (FLET "CONTINUATION46" :IN INVOKE-UPDATING-OUTPUT) {665A41B}> STA..
  6: ((:METHOD INVOKE-UPDATING-OUTPUT (CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN T T T T T T)) #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> #<CLOSURE (FLET "UPDATING-OUTPUT-CONTINUATION41" :IN ..
  7: ((:METHOD REDISPLAY-FRAME-PANE (APPLICATION-FRAME CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN)) #<SUPERAPP {1006938233}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> :FORCE-P T) [fast-method..
  8: ((SB-PCL::EMF REDISPLAY-FRAME-PANE) #<unused argument> #<unused argument> #<SUPERAPP {1006938233}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> :FORCE-P T)
  9: ((:METHOD REDISPLAY-FRAME-PANE :AROUND (APPLICATION-FRAME T)) #<SUPERAPP {1006938233}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}> :FORCE-P T) [fast-method]
 10: ((:METHOD MAP-OVER-SHEETS (T BASIC-SHEET)) #<CLOSURE (LAMBDA (SHEET) :IN REDISPLAY-FRAME-PANES) {1006EF1AFB}> #<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}>) [fast-method]
 11: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (LAMBDA (CLIM-INTERNALS::CHILD) :IN MAP-OVER-SHEETS) {100706F7FB}> (#<CLIM-CLX::CLX-795-INTERACTOR-PANE INT {1006B66BF3}>))
 12: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (LAMBDA (CLIM-INTERNALS::CHILD) :IN MAP-OVER-SHEETS) {100706C2EB}> (#<CLIM-CLX::CLX-795-SCROLL-BAR-PANE #1="(Unnamed Pane)" {1006CC74A3}> #<CLIM-CLX::CLX-7..
 13: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (LAMBDA (CLIM-INTERNALS::CHILD) :IN MAP-OVER-SHEETS) {100706B0AB}> (#<CLIM-CLX::CLX-795-SCROLLER-PANE "(Unnamed Pane)" {1006CB2F93}>))
 14: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (LAMBDA (CLIM-INTERNALS::CHILD) :IN MAP-OVER-SHEETS) {1007069E7B}> (#<CLIM-CLX::CLX-795-BORDER-PANE #1="(Unnamed Pane)" {1006D14F83}> #<CLIM-CLX::CLX-795-M..
 15: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (LAMBDA (CLIM-INTERNALS::CHILD) :IN MAP-OVER-SHEETS) {100706853B}> (#<CLIM-CLX::CLX-795-VRACK-PANE "(Unnamed Pane)" {1006D408F3}>))
 16: ((:METHOD DEFAULT-FRAME-TOP-LEVEL (APPLICATION-FRAME)) #<SUPERAPP {1006938233}> :COMMAND-PARSER COMMAND-LINE-COMMAND-PARSER :COMMAND-UNPARSER COMMAND-LINE-COMMAND-UNPARSER :PARTIAL-COMMAND-PARSER COMM..
 17: ((:METHOD RUN-FRAME-TOP-LEVEL (APPLICATION-FRAME)) #<SUPERAPP {1006938233}>) [fast-method]
 18: ((:METHOD RUN-FRAME-TOP-LEVEL :AROUND (APPLICATION-FRAME)) #<SUPERAPP {1006938233}>) [fast-method]
 19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APP-MAIN) #<NULL-LEXENV>)
 --more--

**Comment by scymtym** [comment]
Which SBCL version is this? I have a hunch regarding which error this could be. If the hunch is accurate, the problem should be fixed in recent SBCL versions.

If you can't/don't want to upgrade, supplying a valid `:display-function` to the `int` pane could help.

**Comment by jimka2001** [comment]
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_FR.UTF-8
This is SBCL 1.4.10, an implementation of ANSI Common Lisp.

**Comment by jimka2001** [comment]
I see that there is a newer tag, 1.5.9.  Should I update to there?

**Comment by jimka2001** [comment]
I updated sbcl to 1.5.9, and slime to 2.24, and I also updated all my quicklisp libraries.  `(ql:update-dist "quicklisp")`  It seems to work now.  Thanks
