### ISSUE TITLE
Cannot load Clouseau via Quicklisp (SBCL on Mac OS X Catalina)

### ISSUE THREAD

**Issue by deterministic-arts** [McCLIM/McCLIM#928]
The following happens with the current McCLIM version downloaded via quicklisp. It happens when I do 

```
(ql:quickload 'clim-debugger)
```

as well as when I directly issue a 

```
(ql:quickload 'clouseau)
```

It happens on a freshly built SBCL 2.0.0 (see error message below) as well as on an older 1.5.5. I tried to load the module multiple times, removing the `~/.cache/common-lisp/...` directory tree between attempts. Everything's running on a MacBook Pro with MacOSX 10.15.2 (Catalina). Right now, I cannot test it under CCL since the Catalina update broke my CCL instance.

As the error message states, this might actually be a bug in the SBCL implementation. Posting this here in the hopes, that someone else has already seen this error and knows something about it.

```
[package clouseau].....................
; 
; caught ERROR:
;   (during macroexpansion of (SB-PCL::%DEFMETHOD-EXPANDER INSPECT-OBJECT-USING-STATE ...))
;     failed AVER: (= SB-C::COMPONENT-TLF-NUM SB-C::TLF-NUM)
;   This is probably a bug in SBCL itself. (Alternatively, SBCL might have been
;   corrupted by bad user code, e.g. by an undefined Lisp operation like
;   (FMAKUNBOUND 'COMPILE), or by stray pointers from alien code or from unsafe
;   Lisp code; or there might be a bug in the OS or hardware that SBCL is running
;   on.) If it seems to be a bug in SBCL itself, the maintainers would like to know
;   about it. Bug reports are welcome on the SBCL mailing lists, which you can find
;   at <http://sbcl.sourceforge.net/>.

; 
; caught ERROR:
;   (during macroexpansion of (SB-PCL::%DEFMETHOD-EXPANDER INSPECT-OBJECT-USING-STATE ...))
;   (during macroexpansion of (SB-PCL::%DEFMETHOD-EXPANDER INSPECT-OBJECT-USING-STATE ...))
;     failed AVER: (= SB-C::COMPONENT-TLF-NUM SB-C::TLF-NUM)
;   This is probably a bug in SBCL itself. (Alternatively, SBCL might have been
;   corrupted by bad user code, e.g. by an undefined Lisp operation like
;   (FMAKUNBOUND 'COMPILE), or by stray pointers from alien code or from unsafe
;   Lisp code; or there might be a bug in the OS or hardware that SBCL is running
;   on.) If it seems to be a bug in SBCL itself, the maintainers would like to know
;   about it. Bug reports are welcome on the SBCL mailing lists, which you can find
;   at <http://sbcl.sourceforge.net/>.
.
While evaluating the form starting at line 11, column 0
  of #P"/Users/dirk/Development/DocIndex2/loadup.lisp":.
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 2 ERROR conditions

CL-USER> (lisp-implementation-version)
"2.0.0"
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> 
```

**Comment by deterministic-arts** [comment]
After experimenting a bit, this seems to be a genuine SBCL problem. I'll try to reduce it to something more minimal and report it there.

**Comment by scymtym** [comment]
Hi, I have seen similar errors but I thought they had been fixed (in SBCL). Do you `proclaim` certain `optimize` settings in your initialization files or similar? I'm not suggesting that your are doing something wrong, just looking for information that might be needed to reproduce the issue.

**Comment by deterministic-arts** [comment]
Not that I am aware of. I even did download and compile a fresh SBCL 2.0 thinking, that I botched my 1.5.5 version by upgrading to Catalina recently. But that did not help either. 

I think that there is something fishy going on with SBCL's load-time `defmethod` support code, maybe due to the fact, that the method body is entirely macro-generated, but that's only an uneducated guess. The `TLF-NUM` stuff refers to the "top-level form number" of the source of a form if I remember this correctly, i.e., the problem seems to happen somewhere deep in the compiler's database of functions/macros/whatever. If I comment out the body of the `defmethod` then the fasl file is loaded normally.

As I said: I assume that the problem is somewhere in SBCL land, and not in the Clouseau code.
