### ISSUE TITLE
Duplicate definitions

### ISSUE THREAD

**Issue by scymtym** [McCLIM/McCLIM#942]
* [ ] `text-style-character-width t t t`
  * `Backends/common/fonts.lisp:227`
  * `Core/clim-basic/decls.lisp:1203`
* [ ] `stream-set-cursor-position`
  * `Core/clim-basic/extended-streams/stream-output.lisp:206`
  * `Core/clim-basic/decls.lisp:508`
* [ ] `make-activation-gestures`
  * `Core/clim-core/input-editing.lisp:81`
  * `Core/clim/input-editing-drei.lisp:81`
* [ ] `make-delimiter-gestures`
  * `Core/clim-core/input-editing.lisp:93`
  * `Core/clim/input-editing-drei.lisp:93`
---
* [ ] `drei-lisp-syntax:default-image`
  * `Libraries/Drei/lisp-syntax-swank.lisp:47`
  * `Libraries/Drei/lisp-syntax.lisp:137`
---
* [x] `clim-demo:com-do-nothing`
  * `Examples/bordered-output-examples.lisp:171`
  * `Examples/misc-tests.lisp:190`
* [x] `clim-demo:refresh`
  * `Examples/patterns.lisp:380`
  * `Examples/patterns-overlap.lisp:37`
* [x] `clim-demo:com-refresh`
  * `Examples/text-multiline-positioning.lisp:60`
  * `Examples/hierarchy-tool.lisp:303`
  * `Examples/text-transformation-test.lisp:133`
  * `Examples/accepting-values-test.lisp:66`
* [x] `clim-demo:com-quit`
  * …

**Comment by dkochmanski** [comment]
clim-demo conflicts resolved in pr #962.
