### ISSUE TITLE
Proposal: WITH-OUTPUT-TO-PDF-FILE macro

### ISSUE THREAD

**Issue by admich** [McCLIM/McCLIM#945]
The PDF backend is used through `WITH-OUTPUT-TO-PDF-STREAM` that is
based on the analogous macro for Postscript backend defined in the
Spec.

I think it is better to define for PDF backend a
`WITH-OUTPUT-TO-PDF-FILE` with a string or a pathname as argument
instead of a stream. In this way the user don't have to open the file
stream (the user needs also to known that the stream must be open with
keyword `:element-type '(unsigned-byte 8)`). If we remove the
WITH-OUTPUT-TO-PDF-STREAM McCLIM can remove the dependency to
FLEXI-STREM system.

The difference from PDF to Postscript is giustified because PDF is a
file format so the output is ever a file, instead the Postscript
output can be send on a stream directly atttached to a postscript
printer.

We can also add a `WITH-OUTPUT-TO-POSTSCRIPT-FILE` macro without remove
the `WITH-OUTPUT-TO-POSTSCRIPT-STREAM` defined in the Specification.

**Comment by dkochmanski** [comment]
as suggested on the mailing list, imo we should use -stream variant where file-var may be coerced to a stream when it contains a pathname designator by opening a file.

**Comment by scymtym** [comment]
Fixed by #959.
