### ISSUE TITLE
Commands with arguments in menus

### ISSUE THREAD

**Issue by heshrobe** [McCLIM/McCLIM#955]
This issue concerns how the define-command macro (and similar command defining macros created by define-application-frame) handle commands that go into a menu (i.e. :menu t is specified).  clim:Define-command expands into clim-internals::%define-command which then expands into a variety of function and method definitions as well as a call to clim:add-command-to-command-table.  This call has a keyword argument :menu-command whose value is a list of the command name followed by as many occurrences of clim:*unsupplied-argument-marker* as there are arguments to the command.  For example (from an application of mine) a command with one argument
```
(define-aplan-command (com-load-model :name t :menu t)
    ((pathname 'clim:pathname)) 
...)
```
expands into:
```
(clim:add-command-to-command-table 'com-load-model 'aplan :name t :menu 't
                                    :keystroke 'nil :errorp nil :menu-command
                                    (list 'com-load-model
                                          clim:*unsupplied-argument-marker*))
```
the value of clim:*unsupplied-argument-marker* is CLIM-INTERNALS::%UNSUPPLIED-ARGUMENT-MARKER%.

This has two consequences one annoying and one serious:
1) If the menu item is clicked on rather than prompting for the arguments, it tells you you're missing arguments.
2) If the menu is in an application frame with a pointer-documentation pane then just moving the mouse over the menu item will cause an error.  The reason for this is that the pointer documentation pane will attempt to present the command, which in turn attempts to present the arguments.  But the present method for the argument is passed the symbol CLIM-INTERNALS::%UNSUPPLIED-ARGUMENT-MARKER% as the object and the presentation type of the argument (in my example above clim:pathname).   In this example, this means that the presentation method for pathnames is invoked but is passed a symbol as the object.  This can easily cause an error.

None of this occurs in the existing implementation of CLIM (e.g. the ACL one).  In the existing implementations, the call to add-command-to-command-table would supply just (list 'com-load-model) as the :menu-command argument.  As a result the pointer-documentation pane just displays the command name.  The command parser in the ACL implementation prompts for the remaining arguments.  Making the macro expansion do what the ACL implementation does would be easy and would prevent an error from being signaled, solving issue 2, but I don't understand the command parser well enough to solve issue 1.  Anybody have some guidance to offer?

**Comment by heshrobe** [comment]
Further information:

In all elements (and I guess in the spec, although I haven't checked), the command-table menu entries are lists with INTERNALS::%UNSUPPLIED-ARGUMENT-MARKER% elements for each argument.  So that's not the cause of the problem.

Here's a better (partial) analysis:
display-command-menu calls display-command-table-menu to do the actual work.  In previous implementations, this presents the menu items with the command-menu-element presentation-type.  In McClim it's presented with presentation-type command,

The issue with the pointer-documentation window is resolved in previous implementations because what's displayed there is based on the available presentation-translators and there is one for command-menu-element.  Document-presentation-translator calls presentation-translator-documentation or presentation-translator-pointer-documentation.  There is a presentation-translator from command-menu-element to command.  It's :documentation  option uses the documentation if it was provided but otherwise calls document-presentation-to-command-translator which just presents the command name.

**Comment by heshrobe** [comment]
Filling in and Summarizing: In McClim command-menu-items are presented with presentation-type command.  The pointer-documentation window works by finding the innermost presentation under the mouse which in this case winds up being the default translator (from t to nil) and then calling its documentation function.  If the presentation-type (i.e. command) has a :description option that is displayed if it's a string or called with the object and the presentation-type (and a variety of other) arguments.  Command doesn't have  a :description option.  If there isn't a :description option, it then just tries to present the object within the presentation, which in this case is a list of the command-name and as many unsullied-argument-markers as there are arguments to the command.  The present method for commands calls the unparsed for the command (generated by the define-command macro) which prints the command name and then tries to present each argument with its corresponding presentation type.  This causes the error because we wind up calling a present method with an object that isn't of the type corresponding to the presentation-type argument.

The existing CLIM2 implementations avoid this by presenting the command-menu items with the presentation-type command-menu-element for which there is a special translator from command-menu-element to command

**Comment by dkochmanski** [comment]
we should close issues after merging to master, so we know what "is in". I'm reopening this for now.

n.b: if you put in the commit message a string "fixes #955" (or for other issues their number), then when the pull request is merged to master the issue will close automatically.

**Comment by dkochmanski** [comment]
thank you for this thoughtful investigation and description.

**Comment by dkochmanski** [comment]
could you provide a minimal example which reproduces the issue? I'm trying

```
(in-package #:clim-user)

(define-application-frame my-frame () ()
  (:pane :interactor)
  (:pointer-documentation t))

(define-my-frame-command (quxbar  :name t :menu t) ((arg 'integer))
  (format t "integer: ~a~%" arg))

(run-frame-top-level (make-application-frame 'my-frame))
```

and when I click on the menu item, I'm prompted for arguments, so that seems to work fine.

**Comment by heshrobe** [comment]
In this example, if you move the mouse over the quxbar menu item, you’ll get an error (you don’t even need to click on it!)
(in-package #:clim-user)

(define-application-frame my-frame () ()
  (:panes 
   (pointer :pointer-documentation
            :borders t
            :height 12
            :max-height 12)
   (menu :command-menu
	 :max-height '(4 :line)
         :display-function '(clim:display-command-menu :n-columns 4 :row-wise t)
         :scroll-bars t
         :borders t
	 )
   (interactor :interactor
	       :scroll-bars :vertical
	       :end-of-line-action :wrap
	       :borders t))
  (:layouts
   (default
    (clim:vertically ()
      menu
      pointer
      (:fill interactor)))))
  

(define-my-frame-command (quxbar  :name t :menu t)
    ((arg1 (list 'integer))
     (arg2 `(second ,arg1)))
  (format t "integer: ~a ~a~%" arg1 arg2))

(run-frame-top-level (make-application-frame 'my-frame))



> On Aug 28, 2020, at 11:54, Daniel Kochmanski <notifications@github.com> wrote:
> 
> 
> could you provide a minimal example which reproduces the issue? I'm trying
> 
> (in-package #:clim-user)
> 
> (define-application-frame my-frame () ()
>   (:pane :interactor)
>   (:pointer-documentation t))
> 
> (define-my-frame-command (quxbar  :name t :menu t) ((arg 'integer))
>   (format t "integer: ~a~%" arg))
> 
> (run-frame-top-level (make-application-frame 'my-frame))
> 
> and when I click on the menu item, I'm prompted for arguments, so that seems to work fine.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by scymtym** [comment]
> ```lisp
> (define-my-frame-command (quxbar  :name t :menu t)
>     ((arg1 (list 'integer))
>      (arg2 `(second ,arg1)))
>   (format t "integer: ~a ~a~%" arg1 arg2))
>  ```

Could you explain how this works? Is the *presentation type* of the second argument computed based on the *value* of the first argument? If so, that type would be `(second SOMETHING)` which is not a presentation type unless `second` is defined as one somewhere else.

**Comment by heshrobe** [comment]
You’re right, but substitute a ptype that takes an argument for second, e.g. member-alist

**Comment by scymtym** [comment]
> You’re right, but substitute a ptype that takes an argument for second, e.g. member-alist

OK, I can see how this is supposed to work. And when typed into the interactor, it does work. I can also confirm that clicking the menu item causes "Argument 1 not supplied" to be printed.

That said, defining the command with just one argument seems to demonstrate the problem already.

**Comment by heshrobe** [comment]
Here’s a better version, without the confusion:


(in-package #:clim-user)

(define-application-frame my-frame () ()
  (:menu-bar nil)
  (:panes 
   (pointer :pointer-documentation
            :borders t
            :height 12
            :max-height 12)
   (menu :command-menu
	 :max-height '(4 :line)
         :display-function '(clim:display-command-menu :n-columns 4 :row-wise t)
         :scroll-bars t
         :borders t
	 )
   (interactor :interactor
	       :scroll-bars :vertical
	       :end-of-line-action :wrap
	       :borders t))
  (:layouts
   (default
    (clim:vertically ()
      menu
      pointer
      (:fill interactor)))))
  

(define-my-frame-command (quxbar  :name t :menu t)
    ((arg1 `(clim:sequence integer))
     (arg2 `(member ,@arg1)))
  (format t "integer: ~a ~a~%" arg1 arg2))

(run-frame-top-level (make-application-frame 'my-frame))

to avoid confusion over menu-bar vs the command-menu-pane, I provided (:menu-bar nil)

The command quxbar takes 2 arguments, the first is a sequence of integers and the 2nd is a member of that sequence.  (The real example involved accepting an application object first the 1sr argument and a member of a set of things related to that object).

In this example, if you move the mouse over the quxbar menu item, the application will throw an error.


> On Aug 29, 2020, at 15:11, Jan Moringen <notifications@github.com> wrote:
> 
> 
> You’re right, but substitute a ptype that takes an argument for second, e.g. member-alist
> 
> OK, I can see how this is supposed to work. And when typed into the interactor, it does work. I can also confirm that clicking the menu item causes "Argument 1 not supplied" to be printed.
> 
> That said, defining the command with just one argument seems to demonstrate the problem already.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by dkochmanski** [comment]
this is perfect, thank you.
