### ISSUE TITLE
Some thoughts in defgeneric* and defmethod*

### ISSUE THREAD

**Issue by ailisp** [McCLIM/McCLIM#96]
As in clim-basic/setf-star.lisp, the defgeneric_, defmethod_ defined by Mr. Moore, `(defgeneric* foo ...)` will expand to `(defsetf foo ...)` and `(defgeneric foo-star ...)`. Theoretically, the `#'foo` should be a generic function, not a macro, and foo-star may cause conflict with user defined symbols.
But if we do set `#'foo` as a generic function, `(setf (foo bar) (values 1 2))` will not work, since `(foo bar)` is not a `(values ...)` form, `setf` will evaluate `(values 1 2)` to `1`, not a multiple value setf form.  So `foo` may have to be a macro to expand to avoid `(values 1 2)` becomes `1`. A way to keep `(defgeneric foo-star)` away from user may be set it into a new package (`gensym` is not suitable, since this name must be used from `defmethod*`). 
Another possible approach, may be, is it possible to  make `defgeneric*` and `defmethod*` expand to something like `(defgeneric ,name ... (:generic-function-class a-gf-class-for-multiple-value-setf))` to solve this problem?
At last, a not desirable approach may be modify the setf in clim-lisp package.
This is not an urgent issue, but may be considered after majority of works done, so I leave it here.

**Comment by dkochmanski** [comment]
if we name generic function foo - is there any conflict though? Doesn't defsetf defined symbol live in it's own namespace? For that instance:

```common-lisp
(defun xxx () "hi")
(defsetf xxx (x) (y) `(format t "~s ~s~%" ,x ,y))

CL-USER> (xxx)
"hi"
CL-USER> (setf (xxx 1) 2)
1 2
NIL
```

**Comment by ailisp** [comment]
Thanks. Maybe not, since #'(setf xxx) is occupied by defsetf's expension,
not #'xxx. When use defgeneric*, we actually write (defgeneric* (setf
xxx)... ). if (setf xxx) is defined by defsetf, so we can (setf (xxx foo)
bar), then we can't have (defgeneric (setf xxx)...) also in defgeneric*'s
expansion, that cause confliction. so currently McCLIM names (defgeneric
(setf xxx)...) to .xxx-star. . I think this is a problem, since we use
defgeneric* (setf xxx), we want #'(setf xxx) be a generic function, not a
function calls another generic function .xxx-star. .
About setf in CLHS: The long form defsetf resembles defmacro. The
lambda-list describes the arguments of access-fn. The store-variables
describe the value or values to be stored into the place. The body must
compute the expansion of a setf of a call on access-fn. The expansion
function is defined in the same lexical environment in which the defsetf
form appears.

2016年10月2日 上午2:26，"Daniel Kochmanski" <notifications@github.com>写道：
