### ISSUE TITLE
text-field gadget issues

### ISSUE THREAD

**Issue by dkochmanski** [McCLIM/McCLIM#966]
- if `:value` initarg is not provided debugger is invoked, it should default to empty string
- when pane is created inside `with-output-as-gadget` debugger is invoked due to a missing slot

**Comment by thrashdin** [comment]
Just to add more to this, I used your code and it worked apart from the fact that after I set any text-field to anything, whenever I try to close the application window, I get

```
#<DREI:DREI-AREA TEXTUAL-DREI-SYNTAX-VIEW {100B899AC3}> is not contained in #<CLIM-CLX::CLX-833-INTERACTOR-PANE INT {10076EFB33}>.
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [ABORT] Return to application command loop.
 1: [RETRY] Retry SLY mREPL evaluation request.
 2: [*ABORT] Return to SLY's top level.
 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1002384933}>)

```

**Comment by dkochmanski** [comment]
thank you for adding this information. fyi at some point in the future I want to remove dependency of input-editing in CLIM core on the Drei library. There is plenty of flowers like that. This will come after refactor-input-streams though.
