### ISSUE TITLE
Exhausting control stack

### ISSUE THREAD

**Issue by watkinsr** [McCLIM/McCLIM#981]
Please see image as discussed on IRC, seems to be some kind of recursive error where CLIM is mapping output records and updating them which blows the heap.

Before this I was just using a browser inside DOORS, an X11 WM using MCCLIM. I guess I was playing the video fullscreen and maybe went out of fullscreen to see this error? I guess also the fact I'm using an external screen may be relevant?

![DSC_0215-min](https://user-images.githubusercontent.com/14998530/76253065-ddb14500-6241-11ea-92e3-0ef3ff0e8b5a.JPG)

**Comment by watkinsr** [comment]
Extra side note: No issues so far inside a nested Xorg inside Xephyr

**Comment by watkinsr** [comment]
WARNING:
   Received CLX WINDOW-ERROR (25) in process #<CLIM-DOORS::DOORS-PORT :HOST "" :DISPLAY-ID 2 {1008132553}>'s event process. for display #<DISPLAY :2 (The X.Org Foundati
on R12007000)>.
WARNING:
   Received CLX WINDOW-ERROR (7) in process #<CLIM-DOORS::DOORS-PORT :HOST "" :DISPLAY-ID 2 {1008132553}>'s event process. for display #<DISPLAY :2 (The X.Org Foundatio
n R12007000)>.
WARNING:
   Received CLX WINDOW-ERROR (25) in process #<CLIM-DOORS::DOORS-PORT :HOST "" :DISPLAY-ID 2 {1008132553}>'s event process. for display #<DISPLAY :2 (The X.Org Foundati
on R12007000)>.
WARNING:
   Received CLX WINDOW-ERROR (7) in process #<CLIM-DOORS::DOORS-PORT :HOST "" :DISPLAY-ID 2 {1008132553}>'s event process. for display #<DISPLAY :2 (The X.Org Foundatio
n R12007000)>.
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution
Heap exhausted during garbage collection: 48 bytes available, 80 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 1   13913      0   1262      0      0      0    5   496465056    789344   308543130   15175   1  1.3998
 2   13267      0    801      0      0      0   25   460252704    727520    10737418   14068   0  0.6319
 3    1887      9    801     96      0     57  125    91115152   2273648     2000000    2850   0  0.0000
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6     425      2    183     55      0     10    0    21563872    554528     2000000     675   0  0.0000
           Total bytes allocated    =    1069396784
           Dynamic-space-size bytes =    1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 9616(tid 0x7f1d8ab57700):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.

**Comment by watkinsr** [comment]
I'm still working on seeing what this is regarding and I have a slight hunch it's something to do with creating a swank server while running McCLIM with DOORS? Could also be some other weird stuff related to how I have my xorg. But for now I have relatively stable McCLIM, if it stays relatively stable I think it would be fine to close the issue

**Comment by dkochmanski** [comment]
I'll close it. If the problem occurs again and you have a better test case to reproduce then please reopen.
