### ISSUE TITLE
format-graph-from-roots problem when output is to a recording stream

### ISSUE THREAD

**Issue by john-a-carroll** [McCLIM/McCLIM#987]
The function `format-graph-from-roots` produces incorrect output when output is to a recording stream. Here's some code that shows how it can impact an application:
```
(in-package :clim-user)

(define-application-frame graphtest ()  ()
  (:menu-bar nil)
  (:panes
    (p1
      (make-pane 'application-pane
        :max-width :compute
        :max-height :compute
        :display-function #'display-graph)))
  (:layouts
    (default
      (scrolling ()
        (spacing (:thickness 1) p1)))))

(defun display-graph (frame stream)
  (declare (ignore frame))
  (format-graph-from-roots
    (list (find-class 'clim:action-gadget))
    #'(lambda (object s)
       (write-string (string (class-name object)) s))
    #'sb-mop:class-direct-subclasses
    :stream stream
    :orientation :horizontal)
  (format *terminal-io* "~&display-graph: ~A ~A~%"
    (bounding-rectangle (stream-current-output-record stream))
    (stream-drawing-p stream)))
  
(defmethod run-frame-top-level :before ((frame graphtest) &key &allow-other-keys)
  (format *terminal-io* "~&run-frame-top-level: ~A~%"
    (sheet-region (find-pane-named frame 'p1))))

(run-frame-top-level (make-application-frame 'graphtest))
```
Here's the terminal output and result:
```
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:547.0d0 Y 0:246.15625d0> NIL
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:547.0d0 Y 0:246.15625d0> NIL
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:823.0d0 Y 0:118.078125d0> NIL
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:823.0d0 Y 0:118.078125d0> NIL
run-frame-top-level: #<STANDARD-BOUNDING-RECTANGLE X 0:547.0d0 Y 0:118.078125d0>
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:823.0d0 Y 0:118.078125d0> NIL
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:823.0d0 Y 0:118.078125d0> NIL
display-graph: #<STANDARD-TREE-OUTPUT-HISTORY X 0:823.0d0 Y 0:118.078125d0> T
display-graph: #<STANDARD-SEQUENCE-OUTPUT-RECORD X 0:823.0d0 Y 0:118.078125d0> NIL
```
<img width="329" alt="Screenshot 2020-03-31 at 15 21 32" src="https://user-images.githubusercontent.com/31476017/78040445-5601b680-7367-11ea-8571-285f79385861.png">

The content of pane p1 is only 118 pixels high, but the scroller pane shows more than twice as much vertically than this, filling in with the background colour. Also, the frame can't be resized horizontally wider than 547 pixels to show all of p1's content at once.

I think what's happening is as follows. The scroller runs its child pane's display function with output to a recording stream to compute the pane's bounding rectangle. In this recording stream, the right text margin is 100 pixels and end-of-line action is :wrap (the clim-stream-pane defaults); this means that the output of the node object-printer (wrongly) has a newline inserted every 100 pixels. When the graph orientation is :horizontal, the bounding rectangle height ends up too large. Is this explanation correct?

I suggest this as a fix: in
`(defmethod generate-graph-nodes ((graph-output-record standard-graph-output-record) ...)`
wrap 
`(with-end-of-line-action (stream :allow) ...)`
around
`(funcall object-printer child stream)`

If this is approved, I'm happy for the approver to make the change.

**Comment by nsrahmad** [comment]
@john-a-carroll That looks right to me. Thank you for the fix. I will open a pull request shortly.
