### ISSUE TITLE
Mark issues with difficulty level so that newcomers can pickup easier ones

### ISSUE THREAD

**Issue by bmansurov** [McCLIM/McCLIM#994]
It'd be nice to know which issues are easier to work on for someone like me, who knows very little about McCLIM but is willing to learn its internals.

**Comment by scymtym** [comment]
I don't know whether this has been answered via other channels already: we use the "good first issue" issue label to mark issues which should be relatively easy to work on. That said, there aren't too many issues of this kind and we are probably also not doing the best job labeling them.
